Sprite Class Reference
#include <Sprite.h>
Public Member Functions
Sprite ()
Sprite (std::string fileName, SDL_Renderer *renderer, int x=0, int y=0)
int getWidth ()
int getHeight ()
int getX ()
int getY ()
Texture getTexture ()
void setY (int y)
void setX (int x)
void setColor (int r, int g, int b)
void render (SDL_Renderer *renderer)
void free ()
bool loadMedia (SDL_Renderer *renderer)
Private Attributes
int posX
int posY
int width
int height
std::string spriteFile
Texture texture
Detailed Description
Base sprite class, all graphical sprites will inherit this class
Definition at line 7 of file Sprite.h.
Constructor & Destructor Documentation
Sprite() [1/2]
Sprite::Sprite ()
Definition at line 3 of file Sprite.cpp.
References posX, posY, and spriteFile.
{
    posX = 0;
    posY = 0;
    spriteFile = "";
}
Sprite() [2/2]
Sprite::Sprite (std::string fileName, SDL_Renderer * renderer, int x = 0, int y = 0)
Definition at line 10 of file Sprite.cpp.
                                                                      : posX(x),
      posY(y), spriteFile(fileName)
{
}
Member Function Documentation
free()
void Sprite::free ()
Definition at line 55 of file Sprite.cpp.
References Texture::free(), and texture.
Referenced by NPC::freeBox().
{
    texture.free();
}
getHeight()
int Sprite::getHeight ()
Definition at line 20 of file Sprite.cpp.
References height.
{
    return height;
}
getTexture()
Texture Sprite::getTexture ()
Definition at line 15 of file Sprite.cpp.
References texture.
{
    return texture;
}
getWidth()
int Sprite::getWidth ()
Definition at line 25 of file Sprite.cpp.
References width.
Referenced by TextBox::createStrings(), and TextBox::loadText().
{
    return width;
}
getX()
int Sprite::getX ()
Definition at line 30 of file Sprite.cpp.
References posX.
Referenced by NPC::LoadBox(), NPC::move(), and TextBox::renderComment().
{
    return posX;
}
getY()
int Sprite::getY ()
Definition at line 35 of file Sprite.cpp.
References posY.
Referenced by NPC::LoadBox(), NPC::move(), and TextBox::renderComment().
{
    return posY;
}
loadMedia()
bool Sprite::loadMedia (SDL_Renderer * renderer)
Definition at line 65 of file Sprite.cpp.
References Texture::getHeight(), Texture::getWidth(), height, Texture::loadFromFile(), spriteFile, texture, and width.
Referenced by NPC::LoadBox().
{
    //Loading success flag
    bool success = true;
    //Load dot texture
    if (!texture.loadFromFile(spriteFile, renderer))
    {
        printf("Failed to load texture!\n");
        success = false;
    }
        width = texture.getWidth();
        height = texture.getHeight();
    return success;
}
render()
void Sprite::render (SDL_Renderer * renderer)
Definition at line 50 of file Sprite.cpp.
References posX, posY, Texture::render(), and texture.
Referenced by NPC::renderBox().
{
    texture.render(posX, posY, renderer);
}
setColor()
void Sprite::setColor (int r, int g, int b)
Definition at line 60 of file Sprite.cpp.
References Texture::setColor(), and texture.
Referenced by NPC::evaluateEmotionLevel().
{
    texture.setColor(r, g, b);
}
setX()
void Sprite::setX (int x)
Definition at line 40 of file Sprite.cpp.
References posX.
Referenced by NPC::LoadBox(), and NPC::move().
{
    posX = x;
}
setY()
void Sprite::setY (int y)
Definition at line 45 of file Sprite.cpp.
References posY.
Referenced by NPC::LoadBox(), and NPC::move().
{
    posY = y;
}
Member Data Documentation
height
int Sprite::height [private]
Definition at line 30 of file Sprite.h.
Referenced by getHeight(), and loadMedia().
posX
int Sprite::posX [private]
Definition at line 29 of file Sprite.h.
Referenced by getX(), render(), setX(), and Sprite().
posY
int Sprite::posY [private]
Definition at line 29 of file Sprite.h.
Referenced by getY(), render(), setY(), and Sprite().
spriteFile
std::string Sprite::spriteFile [private]
Definition at line 31 of file Sprite.h.
Referenced by loadMedia(), and Sprite().
texture
Texture Sprite::texture [private]
Definition at line 33 of file Sprite.h.
Referenced by free(), getTexture(), loadMedia(), render(), and setColor().
width
int Sprite::width [private]
Definition at line 30 of file Sprite.h.
Referenced by getWidth(), and loadMedia().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Sprite.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Sprite.cpp