Room Class Reference
#include <Room.h>
Public Member Functions
Room ()
Room (int groupNum, int x, int y, int width, int height, std::string NPCSprite, std::string TextBoxSprite, SDL_Renderer *renderer, Group grp)
std::pair< int, int > getRoomPosition (int pos)
return the rooms positions
void LoadNPCs (SDL_Renderer *renderer)
render the NPCs to the scene
void LoadConversation (SDL_Renderer *renderer, bool time, std::string boredomLevel, TTF_Font *font)
render the NPC conversations in the room
void HandleMove (SDL_Renderer *renderer)
handle NPC movement
void basicPath (std::shared_ptr< NPC > npc, SDL_Renderer *renderer)
generate a basic path for the NPC to follow
int findOpenGroup (int exclude)
return the id of any open groups
void leaveGroup (std::shared_ptr< NPC > npc)
remove an npc from a group
void joinGroup (std::shared_ptr< NPC > npc, int id)
add an npc to a group
bool checkGroup (int id)
check if any groups have finished conversing
void cleanUpGroups ()
remove any inactive groups
Private Attributes
int roomWidth
int roomHeight
int roomX
int roomY
std::vector< std::shared_ptr< NPC > > roomNPCs
std::vector< std::shared_ptr< Base_Group > > roomGroups
std::vector< std::shared_ptr< Node > > roomNodes
std::string roomsubject
Detailed Description
Definition at line 6 of file Room.h.
Constructor & Destructor Documentation
Room() [1/2]
Room::Room ()
Definition at line 3 of file Room.cpp.
{}
Room() [2/2]
Room::Room (int groupNum, int x, int y, int width, int height, std::string NPCSprite, std::string TextBoxSprite, SDL_Renderer * renderer, Group grp)
Definition at line 5 of file Room.cpp.
References getRoomPosition(), Group::getTopics(), roomGroups, roomHeight, roomNodes, roomNPCs, roomWidth, roomX, and roomY.
{
    roomWidth = width;
    roomHeight = height;
    roomX = x;
    roomY = y;
    int id = 0;
    int groupID = 0;
    for (int i = 0; i < groupNum; i++)
    {
        // Get a random number for the number of NPCs
        std::mt19937 rng;
        rng.seed(std::random_device()());
        std::uniform_int_distribution<std::mt19937::result_type> distGroup(2, 6);
        int random = distGroup(rng);
        // Get an availale position in the room
        std::pair<int, int> positions = getRoomPosition(i);
        // Create a group within the room
        std::shared_ptr<Base_Group> group(new NPC_Group(positions.first, positions.second, random,
       TextBoxSprite, NPCSprite, renderer, grp.getTopics()[i]));
        
        // Generate a random number if NPCs and add them to the new group
        for (int n = 0; n < random; n++)
        {
            std::shared_ptr<NPC> nNPC(new NPC(TextBoxSprite, NPCSprite, "", renderer, 0, 0));
            nNPC->setID(id);
            nNPC->setGroupID(groupID);
            group->AddToGroup(nNPC);
            roomNPCs.push_back(nNPC);
            id++;
        }
        // Set the group ID
        group->setID(groupID);
        // Add the group to the room
        roomGroups.push_back(group);
        groupID++;
        // Surround the group with Nodes
        std::shared_ptr<Node> node1(new Node(positions.first - 50, positions.second - 50));
        std::shared_ptr<Node> node2(new Node(positions.first + 80, positions.second - 50));
        std::shared_ptr<Node> node3(new Node(positions.first - 50, positions.second + 80));
        std::shared_ptr<Node> node4(new Node(positions.first + 80, positions.second + 80));
        roomNodes.push_back(node1);
        roomNodes.push_back(node2);
        roomNodes.push_back(node3);
        roomNodes.push_back(node4);
        int size = roomGroups[i]->getNPCList().size();
        std::cout << "Group of index " << i << " has: " << size << " NPCs" << std::endl;
    }
}
Member Function Documentation
basicPath()
void Room::basicPath (std::shared_ptr< NPC > npc, SDL_Renderer * renderer)
generate a basic path for the NPC to follow
Creates a basic path for the NPC to walk to
Definition at line 283 of file Room.cpp.
Referenced by HandleMove().
{
    std::vector<std::shared_ptr<Node>> basicPath;
    basicPath.push_back(std::shared_ptr<Node>(new Node(npc->getEndGoal().first, npc->getEndGoal().
      second)));
    npc->setPath(basicPath);
    std::cout << "The goal Node for NPC: " << npc->getID() << " is: " << basicPath[0]->getX() << " , " <<
      basicPath[0]->getY() << std::endl;
}
checkGroup()
bool Room::checkGroup (int id)
check if any groups have finished conversing
Check if a group exists in the room
Definition at line 171 of file Room.cpp.
References roomGroups.
Referenced by HandleMove().
{
    for (int i = 0; i < roomGroups.size(); i++)
    {
        if (roomGroups[i]->getID() == id)
            return true;
    }
    return false;
}
cleanUpGroups()
void Room::cleanUpGroups ()
remove any inactive groups
Checks to see if any groups have finished their conversations and then removes them from the room
Definition at line 258 of file Room.cpp.
References roomGroups, and roomNPCs.
Referenced by HandleMove().
{
    for (int g = 0; g < roomGroups.size(); g++)
    {
        if (roomGroups[g]->getScript().size() == 0)
        {
            for (int n = 0; n < roomNPCs.size(); n++)
            {
                if (roomNPCs[n]->getGroupID() == roomGroups[g]->getID()) {
                    if (!(roomGroups[g]->inGroup(roomNPCs[n])))
                    {
                        roomNPCs[n]->setGroupID(-1);
                        roomNPCs[n]->setIdle(true);
                    }
                }
            }
            roomGroups[g]->cleanUpGroup();
            roomGroups.erase(roomGroups.begin() + g);
        }
    }
}
findOpenGroup()
int Room::findOpenGroup (int exclude)
return the id of any open groups
Checks if any groups have any available space
Definition at line 124 of file Room.cpp.
References roomGroups.
Referenced by HandleMove().
{
    for (int i = 0; i < roomGroups.size(); i++)
    {
        if (roomGroups[i]->isAvailable() && roomGroups[i]->getID() != exclude)
        {
            return roomGroups[i]->getID();
        }
    }
    return -1;
}
getRoomPosition()
std::pair< int, int > Room::getRoomPosition (int pos)
return the rooms positions
Returns a pair of integers that hold the X and Y of the available room spaces.
Definition at line 64 of file Room.cpp.
References roomHeight, roomWidth, roomX, and roomY.
Referenced by Room().
{
    std::pair<int, int> XYPos;
    switch (pos)
    {
    case 0:
        XYPos.first = roomWidth / 2;
        XYPos.second = roomHeight / 2;
        break;
    case 1:
        XYPos.first = roomWidth - roomX;
        XYPos.second = roomHeight - roomY;
        break;
    case 2:
        XYPos.first = roomX;
        XYPos.second = roomY;
        break;
    case 3:
        XYPos.first = roomWidth - roomX;
        XYPos.second = roomY;
        break;
    case 4:
        XYPos.first = roomX;
        XYPos.second = roomHeight - roomY;
        break;
    }
    return XYPos;
}
HandleMove()
void Room::HandleMove (SDL_Renderer * renderer)
handle NPC movement
Handles the NPCs movement between groups
Definition at line 184 of file Room.cpp.
References basicPath(), checkGroup(), cleanUpGroups(), findOpenGroup(), joinGroup(), leaveGroup(), and roomNPCs.
{
    for (int i = 0; i < roomNPCs.size(); i++)
    {
        // Check if the NPCs group is still active
        bool gCheck = checkGroup(roomNPCs[i]->getGroupID());
        if (roomNPCs[i]->getGroupID() == -1 || !gCheck)
        {
            roomNPCs[i]->setIdle(true);
        }
        // Check if an NPC is currently idle
        if (roomNPCs[i]->getIdle())
        {
            if (!roomNPCs[i]->getMoving())
            {
                // Remove any groups in the scene that are no longer active
                cleanUpGroups();
                // Check if an NPCs group exists in the room
                int gID = findOpenGroup(roomNPCs[i]->getGroupID());
                if (gID > -1)
                {
                    // Remove the NPC from the his current group
                    leaveGroup(roomNPCs[i]);
                    // Move the NPC to a new group
                    joinGroup(roomNPCs[i], gID);
                    // Call the basic move method and set the NPC to move
                    basicPath(roomNPCs[i], renderer);
                    roomNPCs[i]->setMoving(true);
                    // Free up any lingereing speech the NPC had left from the previous conversation
                    roomNPCs[i]->freeBox();
                }
                // if there are no existing rooms, move the NPC off the screen to be deleted.
                if (gID == -1)
                {
                    leaveGroup(roomNPCs[i]);
                    roomNPCs[i]->setEndGoal(std::pair<int, int>(800, 800));
                    basicPath(roomNPCs[i], renderer);
                    roomNPCs[i]->setMoving(true);
                    roomNPCs[i]->freeBox();
                }
            }
            else
            {
                // If an NPC is idle, call the movement method to start his movement process
                roomNPCs[i]->move();
                // Check if the NPC has met his end goal
                if (roomNPCs[i]->getX() == roomNPCs[i]->getEndGoal().first &&
      roomNPCs[i]->getY() == roomNPCs[i]->getEndGoal().second)
                {
                    // If the NPC has met his goal he is no longer idle or bored
                    roomNPCs[i]->setIdle(false);
                    roomNPCs[i]->setMoving(false);
                    roomNPCs[i]->setBoredom(0);
                    // If the NPC has reached here, then he is no longer in the room
                    if (roomNPCs[i]->getX() == 800 && roomNPCs[i]->getY() == 800)
                    {
                        roomNPCs.erase(roomNPCs.begin() + i);
                    }
                }
            }
        }
    }
}
joinGroup()
void Room::joinGroup (std::shared_ptr< NPC > npc, int id)
add an npc to a group
Adds an NPC to a group
Definition at line 156 of file Room.cpp.
References roomGroups.
Referenced by HandleMove().
{
    for (int i = 0; i < roomGroups.size(); i++)
    {
        if (roomGroups[i]->getID() == id)
        {
            roomGroups[i]->joinSpace(npc);
            npc->setMoving(true);
        }
    }
}
leaveGroup()
void Room::leaveGroup (std::shared_ptr< NPC > npc)
remove an npc from a group
Removes an NPC from a group
Definition at line 139 of file Room.cpp.
References roomGroups.
Referenced by HandleMove().
{
    for (int i = 0; i < roomGroups.size(); i++)
    {
        for (int n = 0; n < roomGroups[i]->getNPCList().size(); n++)
        {
            if (roomGroups[i]->getNPCList()[n]->getID() == npc->getID())
            {
                roomGroups[i]->leaveSpace(npc);
            }
        }
    }
}
LoadConversation()
void Room::LoadConversation (SDL_Renderer * renderer, bool time, std::string boredomLevel, TTF_Font * font)
render the NPC conversations in the room
Simulate and render each conversation happening in the room
Definition at line 111 of file Room.cpp.
References roomGroups.
{
    std::vector<std::shared_ptr<Base_Group>>::iterator groupIterator;
    for (groupIterator = roomGroups.begin(); groupIterator !=
      roomGroups.end(); groupIterator++)
    {
        (*groupIterator)->simulateConversation(renderer, time, boredomLevel, font);
        (*groupIterator)->renderConversation(renderer);
    }
}
LoadNPCs()
void Room::LoadNPCs (SDL_Renderer * renderer)
render the NPCs to the scene
Call each of the NPC's render functions to render each of there sprites to the screen.
Definition at line 97 of file Room.cpp.
References roomNPCs.
{
    std::vector<std::shared_ptr<NPC>>::iterator npcIterator;
    for (npcIterator = roomNPCs.begin(); npcIterator != roomNPCs.end(); npcIterator++)
    {
        (*npcIterator)->loadMedia(renderer);
        (*npcIterator)->evaluateEmotionLevel();
        (*npcIterator)->render(renderer);
    }
}
Member Data Documentation
roomGroups
std::vector<std::shared_ptr<Base_Group> > Room::roomGroups [private]
Definition at line 46 of file Room.h.
Referenced by checkGroup(), cleanUpGroups(), findOpenGroup(), joinGroup(), leaveGroup(), LoadConversation(), and Room().
roomHeight
int Room::roomHeight [private]
Definition at line 43 of file Room.h.
Referenced by getRoomPosition(), and Room().
roomNodes
std::vector<std::shared_ptr<Node> > Room::roomNodes [private]
Definition at line 47 of file Room.h.
Referenced by Room().
roomNPCs
std::vector<std::shared_ptr<NPC> > Room::roomNPCs [private]
Definition at line 45 of file Room.h.
Referenced by cleanUpGroups(), HandleMove(), LoadNPCs(), and Room().
roomsubject
std::string Room::roomsubject [private]
Definition at line 48 of file Room.h.
roomWidth
int Room::roomWidth [private]
Definition at line 43 of file Room.h.
Referenced by getRoomPosition(), and Room().
roomX
int Room::roomX [private]
Definition at line 43 of file Room.h.
Referenced by getRoomPosition(), and Room().
roomY
int Room::roomY [private]
Definition at line 43 of file Room.h.
Referenced by getRoomPosition(), and Room().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Room.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Room.cpp