Base_Group Class Reference
#include <Base_Group.h>
Public Member Functions
Base_Group ()
Base_Group (int x, int y, int size, std::string tBoxFile, std::string npcFile, SDL_Renderer *renderer, Topic tp)
void renderConversation (SDL_Renderer *renderer)
Renders the conversation to the SDL window.
int getID ()
Retrieves the group ID.
void setID (int id)
Set the group ID.
bool AddToGroup (std::shared_ptr< NPC > nNPC)
Add an NPC to the group.
std::vector< Comment > getScript ()
Get the script of comments.
bool isAvailable ()
Checks to if there is any avaialbe space in the groups.
std::pair< int, int > getSpace ()
Retrieves an open space from a group of NPC's.
void leaveSpace (std::shared_ptr< NPC > npc)
Called when the NPC wants to leave a group.
bool joinSpace (std::shared_ptr< NPC > npc)
Called when an NPC wants to join a group.
void cleanUpGroup ()
Clean up call, called when the group has nothing to talk about.
int getLastSpoken ()
Get the last NPC who spoke in the conversation.
void setLastSpoken (int spoke)
Set the last spoken NPC.
bool getIsReply ()
Check if the current comment is a reply.
void setIsReply (bool reply)
Set a bool to indicate the next comment is a reply.
float getPolar ()
Get the NPC's polarity score.
void setPolar (float polar)
Set the NPC's polarity score.
void updateScript ()
Update the script.
bool inGroup (std::shared_ptr< NPC > npc)
Returns a bool to indicate the parsed in NPC belongs to the group.
int GetRandomNumber ()
virtual void simulateConversation (SDL_Renderer *renderer, bool time, std::string boredomLevel, TTF_Font *font)
Template methods to be inherited by child classes, these are the core classes for simulating conversation.
virtual bool evaluateSpeaker ()
virtual void setSpeaker (std::string boredomLevel)
std::vector< std::shared_ptr< NPC > > getNPCList ()
Return the list of NPCs.
Private Attributes
std::vector< std::shared_ptr< NPC > > NPCs
std::vector< Comment > script
int ID
std::vector< std::pair< int, int > > availableSpace
bool speakerDesignated = false
bool topicRead = true
std::string topicString
int currentComment = 0
bool isReply
int lastSpoken
float polar
int GroupX
int GroupY
int GroupSize
Detailed Description
The Base class for the Group classes within the project
Definition at line 14 of file Base_Group.h.
Constructor & Destructor Documentation
Base_Group() [1/2]
Base_Group::Base_Group ()
Definition at line 11 of file Base_Group.cpp.
{
}
Base_Group() [2/2]
Base_Group::Base_Group (int x, int y, int size, std::string tBoxFile, std::string npcFile, SDL_Renderer * renderer, Topic tp)
Definition at line 16 of file Base_Group.cpp.
References availableSpace, Topic::getComments(), Topic::getTopic(), GroupX, GroupY, script, and topicString.
                                                                                                           
                 : GroupX(x), GroupY(y), GroupSize(size)
{
    script = tp.getComments();
    topicString = tp.getTopic();
    availableSpace.push_back(std::pair<int, int>(GroupX,
      GroupY - 35));
    availableSpace.push_back(std::pair<int, int>(GroupX + 35,
      GroupY - 17));
    availableSpace.push_back(std::pair<int, int>(GroupX + 35,
      GroupY + 17));
    availableSpace.push_back(std::pair<int, int>(GroupX,
      GroupY + 35));
    availableSpace.push_back(std::pair<int, int>(GroupX - 35,
      GroupY + 17));
    availableSpace.push_back(std::pair<int, int>(GroupX - 35,
      GroupY - 17));
}
Member Function Documentation
AddToGroup()
bool Base_Group::AddToGroup (std::shared_ptr< NPC > nNPC)
Add an NPC to the group.
Definition at line 95 of file Base_Group.cpp.
References availableSpace, getSpace(), isAvailable(), and NPCs.
{
    bool success = false;
    if (NPCs.size() < 6)
    {
        if (isAvailable())
        {
            std::pair<int, int> newPos = getSpace();
            nNPC->setEndGoal(newPos);
            nNPC->setX(newPos.first);
            nNPC->setY(newPos.second);
            availableSpace.erase(std::remove(availableSpace.begin(),
      availableSpace.end(), availableSpace[0]),
      availableSpace.end());
            if (NPCs.size() == 0)
            {
                nNPC->setSpeaking(true);
            }
            NPCs.push_back(nNPC);
            success = true;
        }
        else
            return success;
    }
    else
    {
        return success;
    }
    return success;
}
cleanUpGroup()
void Base_Group::cleanUpGroup ()
Clean up call, called when the group has nothing to talk about.
Definition at line 224 of file Base_Group.cpp.
References leaveSpace(), and NPCs.
{
    for (int i = 0; i < NPCs.size(); i++)
    {
        NPCs[i]->setIdle(true);
        NPCs[i]->setSpeaking(false);
        NPCs[i]->setReading(false);
        NPCs[i]->setText("");
        NPCs[i]->setGroupID(-1);
        leaveSpace(NPCs[i]);
    }
}
evaluateSpeaker()
bool Base_Group::evaluateSpeaker () [virtual]
Reimplemented in NPC_Group, and User_Group.
Definition at line 254 of file Base_Group.cpp.
{
    return false;
}
getID()
int Base_Group::getID ()
Retrieves the group ID.
Definition at line 73 of file Base_Group.cpp.
References ID.
Referenced by leaveSpace(), User_Group::setSpeaker(), and NPC_Group::setSpeaker().
{
    return ID;
}
getIsReply()
bool Base_Group::getIsReply ()
Check if the current comment is a reply.
Definition at line 148 of file Base_Group.cpp.
References isReply.
Referenced by NPC_Group::simulateConversation().
{
    return isReply;
}
getLastSpoken()
int Base_Group::getLastSpoken ()
Get the last NPC who spoke in the conversation.
Definition at line 138 of file Base_Group.cpp.
References lastSpoken.
Referenced by NPC_Group::simulateConversation().
{
    return lastSpoken;
}
getNPCList()
std::vector< std::shared_ptr< NPC > > Base_Group::getNPCList ()
Return the list of NPCs.
Definition at line 133 of file Base_Group.cpp.
References NPCs.
Referenced by User_Group::evaluateSpeaker(), NPC_Group::evaluateSpeaker(), User_Group::setSpeaker(), NPC_Group::setSpeaker(), and NPC_Group::simulateConversation().
{
    return NPCs;
}
getPolar()
float Base_Group::getPolar ()
Get the NPC's polarity score.
Definition at line 158 of file Base_Group.cpp.
References polar.
Referenced by NPC_Group::simulateConversation().
{
    return polar;
}
GetRandomNumber()
int Base_Group::GetRandomNumber ()
Definition at line 171 of file Base_Group.cpp.
References lastSpoken, and NPCs.
Referenced by User_Group::setSpeaker(), and NPC_Group::setSpeaker().
{
    if (NPCs.size() > 0)
    {
        int gSize = NPCs.size();
        std::mt19937 rng;
        rng.seed(std::random_device()());
        std::uniform_int_distribution<std::mt19937::result_type> distGroup(0, gSize - 1);
        int random = distGroup(rng);
        //if the random number matches our current NPC, change its value
        if (random == lastSpoken)
        {
            if (random == NPCs.size() - 1)
                random--;
            else
                random++;
        }
        if (random < 0)
            random = NPCs.size() - 1;
        if (NPCs[random]->getIdle() == true)
        {
            random--;
            if (random == lastSpoken)
                random + 2;
        }
        if (random < 0)
            random = NPCs.size() - 1;
        return random;
    }
    return 0;
}
getScript()
std::vector< Comment > Base_Group::getScript ()
Get the script of comments.
Definition at line 125 of file Base_Group.cpp.
References script.
Referenced by User_Group::setSpeaker(), and NPC_Group::simulateConversation().
{
    return script;
}
getSpace()
std::pair< int, int > Base_Group::getSpace ()
Retrieves an open space from a group of NPC's.
Definition at line 36 of file Base_Group.cpp.
References availableSpace, and isAvailable().
Referenced by AddToGroup(), and joinSpace().
{
    if (isAvailable()) {
        std::pair<int, int> recoveredSpace = availableSpace[0];
        return recoveredSpace;
    }
}
inGroup()
bool Base_Group::inGroup (std::shared_ptr< NPC > npc)
Returns a bool to indicate the parsed in NPC belongs to the group.
Definition at line 237 of file Base_Group.cpp.
References NPCs.
{
    for (int i = 0; i < NPCs.size(); i++)
    {
        if (NPCs[i] == npc)
            return true;
    }
    return false;
}
isAvailable()
bool Base_Group::isAvailable ()
Checks to if there is any avaialbe space in the groups.
Definition at line 28 of file Base_Group.cpp.
References availableSpace.
Referenced by AddToGroup(), getSpace(), and joinSpace().
{
    if (availableSpace.size() > 0)
        return true;
    else
        return false;
}
joinSpace()
bool Base_Group::joinSpace (std::shared_ptr< NPC > npc)
Called when an NPC wants to join a group.
Definition at line 44 of file Base_Group.cpp.
References availableSpace, getSpace(), ID, isAvailable(), and NPCs.
{
    bool success = false;
    if (NPCs.size() < 6)
    {
        if (isAvailable())
        {
            std::pair<int, int> newPos = getSpace();
            availableSpace.erase(std::remove(availableSpace.begin(),
      availableSpace.end(), availableSpace[0]),
      availableSpace.end());
            npc->setEndGoal(newPos);
            if (NPCs.size() == 0)
            {
                npc->setSpeaking(true);
            }
            npc->setGroupID(ID);
            NPCs.push_back(npc);
            success = true;
        }
        else
            return success;
    }
    else
    {
        return success;
    }
    return success;
}
leaveSpace()
void Base_Group::leaveSpace (std::shared_ptr< NPC > npc)
Called when the NPC wants to leave a group.
Definition at line 83 of file Base_Group.cpp.
References availableSpace, getID(), and NPCs.
Referenced by cleanUpGroup().
{
    for (int i = 0; i < NPCs.size(); i++)
    {
        if (NPCs[i]->getID() == npc->getID())
        {
            availableSpace.push_back(std::pair<int, int>(npc->getX(), npc->getY()));
            NPCs.erase(std::remove(NPCs.begin(), NPCs.end(), npc),
      NPCs.end());
        }
    }
}
renderConversation()
void Base_Group::renderConversation (SDL_Renderer * renderer)
Renders the conversation to the SDL window.
Definition at line 211 of file Base_Group.cpp.
References NPCs.
{
    std::vector<std::shared_ptr<NPC>>::iterator npcIterator;
    for (npcIterator = NPCs.begin(); npcIterator != NPCs.end(); npcIterator++)
    {
        //render the comment of the NPC currently speaking
        if ((*npcIterator)->getSpeaking()) {
            (*npcIterator)->renderBox(renderer);
            (*npcIterator)->renderComment(renderer);
        }
    }
}
setID()
void Base_Group::setID (int id)
Set the group ID.
Definition at line 78 of file Base_Group.cpp.
References ID.
{
    ID = id;
}
setIsReply()
void Base_Group::setIsReply (bool reply)
Set a bool to indicate the next comment is a reply.
Definition at line 153 of file Base_Group.cpp.
References isReply.
Referenced by NPC_Group::simulateConversation().
{
    isReply = reply;
}
setLastSpoken()
void Base_Group::setLastSpoken (int spoke)
Set the last spoken NPC.
Definition at line 143 of file Base_Group.cpp.
References lastSpoken.
Referenced by NPC_Group::simulateConversation().
{
    lastSpoken = spoke;
}
setPolar()
void Base_Group::setPolar (float polar)
Set the NPC's polarity score.
Definition at line 163 of file Base_Group.cpp.
References polar.
Referenced by NPC_Group::simulateConversation().
{
    polar = pol;
}
setSpeaker()
void Base_Group::setSpeaker (std::string boredomLevel) [virtual]
Reimplemented in NPC_Group, and User_Group.
Definition at line 259 of file Base_Group.cpp.
{}
simulateConversation()
void Base_Group::simulateConversation (SDL_Renderer * renderer, bool time, std::string boredomLevel, TTF_Font * font) [virtual]
Template methods to be inherited by child classes, these are the core classes for simulating conversation.
Reimplemented in NPC_Group, and User_Group.
Definition at line 252 of file Base_Group.cpp.
{}
updateScript()
void Base_Group::updateScript ()
Update the script.
Definition at line 247 of file Base_Group.cpp.
References script.
Referenced by NPC_Group::simulateConversation().
{
    if (script.size() > 0)
        script.erase(script.begin());
}
Member Data Documentation
availableSpace
std::vector<std::pair<int, int> > Base_Group::availableSpace [private]
Definition at line 88 of file Base_Group.h.
Referenced by AddToGroup(), Base_Group(), getSpace(), isAvailable(), joinSpace(), and leaveSpace().
currentComment
int Base_Group::currentComment = 0 [private]
Definition at line 94 of file Base_Group.h.
GroupSize
int Base_Group::GroupSize [private]
Definition at line 102 of file Base_Group.h.
GroupX
int Base_Group::GroupX [private]
Definition at line 100 of file Base_Group.h.
Referenced by Base_Group().
GroupY
int Base_Group::GroupY [private]
Definition at line 101 of file Base_Group.h.
Referenced by Base_Group().
ID
int Base_Group::ID [private]
Definition at line 86 of file Base_Group.h.
Referenced by getID(), joinSpace(), and setID().
isReply
bool Base_Group::isReply [private]
Definition at line 96 of file Base_Group.h.
Referenced by getIsReply(), and setIsReply().
lastSpoken
int Base_Group::lastSpoken [private]
Definition at line 97 of file Base_Group.h.
Referenced by getLastSpoken(), GetRandomNumber(), and setLastSpoken().
NPCs
std::vector<std::shared_ptr<NPC> > Base_Group::NPCs [private]
Definition at line 84 of file Base_Group.h.
Referenced by AddToGroup(), cleanUpGroup(), User_Group::evaluateSpeaker(), NPC_Group::evaluateSpeaker(), getNPCList(), GetRandomNumber(), inGroup(), joinSpace(), leaveSpace(), renderConversation(), User_Group::setSpeaker(), NPC_Group::setSpeaker(), and NPC_Group::simulateConversation().
polar
float Base_Group::polar [private]
Definition at line 98 of file Base_Group.h.
Referenced by getPolar(), and setPolar().
script
std::vector<Comment> Base_Group::script [private]
Definition at line 85 of file Base_Group.h.
Referenced by Base_Group(), getScript(), and updateScript().
speakerDesignated
bool Base_Group::speakerDesignated = false [private]
Definition at line 90 of file Base_Group.h.
topicRead
bool Base_Group::topicRead = true [private]
Definition at line 91 of file Base_Group.h.
topicString
std::string Base_Group::topicString [private]
Definition at line 93 of file Base_Group.h.
Referenced by Base_Group().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Base_Group.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Base_Group.cpp