Topic Class Reference
#include <Topic.h>
Public Member Functions
Topic ()
Topic (std::string nId, std::string nTopic, std::vector< Comment > nComments)
std::string getId ()
std::string getTopic ()
std::vector< Comment > getComments ()
void setId (std::string nId)
void setTopic (std::string nTopic)
void setComments (std::vector< Comment > nComments)
Private Attributes
std::string id
std::string topic
std::vector< Comment > comments
Friends
bool operator== (const Topic &c1, const Topic &c2)
Detailed Description
Model representation for the comment object within the program
Definition at line 6 of file Topic.h.
Constructor & Destructor Documentation
Topic() [1/2]
Topic::Topic ()
Definition at line 3 of file Topic.cpp.
{
}
Topic() [2/2]
Topic::Topic (std::string nId, std::string nTopic, std::vector< Comment > nComments)
Definition at line 8 of file Topic.cpp.
References setComments(), setId(), and setTopic().
{
    setId(nId);
    setTopic(nTopic);
    setComments(nComments);
}
Member Function Documentation
getComments()
std::vector< Comment > Topic::getComments ()
Definition at line 25 of file Topic.cpp.
References comments.
Referenced by Base_Group::Base_Group().
{
    return comments;
}
getId()
std::string Topic::getId ()
Definition at line 15 of file Topic.cpp.
References id.
{
    return id;
}
getTopic()
std::string Topic::getTopic ()
Definition at line 20 of file Topic.cpp.
References topic.
Referenced by Base_Group::Base_Group().
{
    return topic;
}
setComments()
void Topic::setComments (std::vector< Comment > nComments)
Definition at line 40 of file Topic.cpp.
Referenced by Topic().
{
    comments = nComments;
}
setId()
void Topic::setId (std::string nId)
Definition at line 30 of file Topic.cpp.
Referenced by Topic().
{
    id = nId;
}
setTopic()
void Topic::setTopic (std::string nTopic)
Definition at line 35 of file Topic.cpp.
References topic.
Referenced by Topic().
{
    topic = nTopic;
}
Friends And Related Function Documentation
operator==
bool operator== (const Topic & c1, const Topic & c2) [friend]
Definition at line 45 of file Topic.cpp.
{
    return (t1.id == t2.id) && (t1.topic == t2.topic) && (t1.comments == t2.comments);
}
Member Data Documentation
comments
std::vector<Comment> Topic::comments [private]
Definition at line 22 of file Topic.h.
Referenced by getComments(), and operator==().
id
std::string Topic::id [private]
Definition at line 20 of file Topic.h.
Referenced by getId(), and operator==().
topic
std::string Topic::topic [private]
Definition at line 21 of file Topic.h.
Referenced by getTopic(), operator==(), and setTopic().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Topic.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Topic.cpp