Group Class Reference
#include <Group.h>
Public Member Functions
Group ()
Group (std::string nId, std::vector< Topic > nTopics)
std::string getId ()
std::vector< Topic > getTopics ()
void setId (std::string nId)
void setTopics (std::vector< Topic > nTopics)
Private Attributes
std::string id
std::vector< Topic > topics
Friends
bool operator== (const Group &c1, const Group &c2)
Custom compare operator.
Detailed Description
Model representation for the Group object within the program
Definition at line 6 of file Group.h.
Constructor & Destructor Documentation
Group() [1/2]
Group::Group ()
Definition at line 3 of file Group.cpp.
{}
Group() [2/2]
Group::Group (std::string nId, std::vector< Topic > nTopics)
Definition at line 5 of file Group.cpp.
References setId(), and setTopics().
{
    setId(nId);
    setTopics(nTopics);
}
Member Function Documentation
getId()
std::string Group::getId ()
Definition at line 11 of file Group.cpp.
References id.
{
    return id;
}
getTopics()
std::vector< Topic > Group::getTopics ()
Definition at line 16 of file Group.cpp.
References topics.
Referenced by Room::Room().
{
    return topics;
}
setId()
void Group::setId (std::string nId)
Definition at line 21 of file Group.cpp.
Referenced by Group().
{
    id = nId;
}
setTopics()
void Group::setTopics (std::vector< Topic > nTopics)
Definition at line 26 of file Group.cpp.
References topics.
Referenced by Group().
{
    topics = nTopics;
}
Friends And Related Function Documentation
operator==
bool operator== (const Group & c1, const Group & c2) [friend]
Custom compare operator.
Definition at line 31 of file Group.cpp.
{
    return (t1.id == t2.id) && (t1.topics == t2.topics);
}
Member Data Documentation
id
std::string Group::id [private]
Definition at line 21 of file Group.h.
Referenced by getId(), and operator==().
topics
std::vector<Topic> Group::topics [private]
Definition at line 22 of file Group.h.
Referenced by getTopics(), operator==(), and setTopics().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Group.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Group.cpp