User_Group Class Reference
#include <User_Group.h>
Public Member Functions
User_Group (int x, int y, int size, std::string tBoxFile, std::string npcFile, SDL_Renderer *renderer, Topic tp)
void simulateConversation (SDL_Renderer *renderer, bool time, std::string boredomLevel, TTF_Font *font)
Template methods to be inherited by child classes, these are the core classes for simulating conversation.
bool evaluateSpeaker ()
void setSpeaker (std::string boredomLevel)
Detailed Description
Definition at line 4 of file User_Group.h.
Constructor & Destructor Documentation
User_Group()
User_Group::User_Group (int x, int y, int size, std::string tBoxFile, std::string npcFile, SDL_Renderer * renderer, Topic tp)
Definition at line 5 of file User_Group.cpp.
                                                                                                           
                : Base_Group(x, y, size, tBoxFile, npcFile, renderer, tp)
{}
Member Function Documentation
evaluateSpeaker()
bool User_Group::evaluateSpeaker () [virtual]
Reimplemented from Base_Group.
Definition at line 13 of file User_Group.cpp.
References Base_Group::getNPCList(), and Base_Group::NPCs.
Referenced by setSpeaker().
{
    std::vector<std::shared_ptr<NPC>> NPCs = getNPCList();
    for (int i = 0; i < NPCs.size(); i++)
    {
        if (NPCs[i]->getSpeaking())
            return true;
    }
    return false;
}
setSpeaker()
void User_Group::setSpeaker (std::string boredomLevel) [virtual]
Reimplemented from Base_Group.
Definition at line 24 of file User_Group.cpp.
References evaluateSpeaker(), Base_Group::getID(), Base_Group::getNPCList(), Base_Group::GetRandomNumber(), Base_Group::getScript(), and Base_Group::NPCs.
{
    if (!evaluateSpeaker()) {
        int r = GetRandomNumber();
        std::vector<std::shared_ptr<NPC>> NPCs = getNPCList();
        std::vector<Comment> comms = getScript();
        for (int i = 0; i < NPCs.size(); i++)
        {
            if (NPCs[i]->getID() != NPCs[r]->getID())
            {
                std::string pred = NPCs[i]->getCurrentUser();
                /*
                if (std::find_if(comms.begin(), comms.end(), CommentComp(pred)) != comms.end())
                {
                };
                */
            }
        }
        NPCs[r]->setSpeaking(true);
    }
}
simulateConversation()
void User_Group::simulateConversation (SDL_Renderer * renderer, bool time, std::string boredomLevel, TTF_Font * font) [virtual]
Template methods to be inherited by child classes, these are the core classes for simulating conversation.
Reimplemented from Base_Group.
Definition at line 8 of file User_Group.cpp.
{
    // TODO: implement algorithm 2
}
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/User_Group.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/User_Group.cpp