Json::OurReader Class Reference
Classes
class ErrorInfo
struct StructuredError
class Token
Public Types
typedef char Char
typedef const Char * Location
Public Member Functions
OurReader (OurFeatures const &features)
bool parse (const char *beginDoc, const char *endDoc, Value &root, bool collectComments=true)
JSONCPP_STRING getFormattedErrorMessages () const
std::vector< StructuredError > getStructuredErrors () const
bool pushError (const Value &value, const JSONCPP_STRING &message)
bool pushError (const Value &value, const JSONCPP_STRING &message, const Value &extra)
bool good () const
Private Types
enum TokenType {
tokenEndOfStream = 0,
tokenObjectBegin,
tokenObjectEnd,
tokenArrayBegin,
tokenArrayEnd,
tokenString,
tokenNumber,
tokenTrue,
tokenFalse,
tokenNull,
tokenNaN,
tokenPosInf,
tokenNegInf,
tokenArraySeparator,
tokenMemberSeparator,
tokenComment,
tokenError
 }
typedef std::deque< ErrorInfo > Errors
typedef std::stack< Value * > Nodes
Private Member Functions
OurReader (OurReader const &)
void operator= (OurReader const &)
bool readToken (Token &token)
void skipSpaces ()
bool match (Location pattern, int patternLength)
bool readComment ()
bool readCStyleComment ()
bool readCppStyleComment ()
bool readString ()
bool readStringSingleQuote ()
bool readNumber (bool checkInf)
bool readValue ()
bool readObject (Token &token)
bool readArray (Token &token)
bool decodeNumber (Token &token)
bool decodeNumber (Token &token, Value &decoded)
bool decodeString (Token &token)
bool decodeString (Token &token, JSONCPP_STRING &decoded)
bool decodeDouble (Token &token)
bool decodeDouble (Token &token, Value &decoded)
bool decodeUnicodeCodePoint (Token &token, Location &current, Location end, unsigned int &unicode)
bool decodeUnicodeEscapeSequence (Token &token, Location &current, Location end, unsigned int &unicode)
bool addError (const JSONCPP_STRING &message, Token &token, Location extra=0)
bool recoverFromError (TokenType skipUntilToken)
bool addErrorAndRecover (const JSONCPP_STRING &message, Token &token, TokenType skipUntilToken)
void skipUntilSpace ()
Value & currentValue ()
Char getNextChar ()
void getLocationLineAndColumn (Location location, int &line, int &column) const
JSONCPP_STRING getLocationLineAndColumn (Location location) const
void addComment (Location begin, Location end, CommentPlacement placement)
void skipCommentTokens (Token &token)
Private Attributes
Nodes nodes_
Errors errors_
JSONCPP_STRING document_
Location begin_
Location end_
Location current_
Location lastValueEnd_
Value * lastValue_
JSONCPP_STRING commentsBefore_
OurFeatures const features_
bool collectComments_
Detailed Description
Definition at line 1137 of file jsoncpp.cpp.
Member Typedef Documentation
Char
typedef char Json::OurReader::Char
Definition at line 1139 of file jsoncpp.cpp.
Errors
typedef std::deque<ErrorInfo> Json::OurReader::Errors [private]
Definition at line 1196 of file jsoncpp.cpp.
Location
typedef const Char* Json::OurReader::Location
Definition at line 1140 of file jsoncpp.cpp.
Nodes
typedef std::stack<Value*> Json::OurReader::Nodes [private]
Definition at line 1238 of file jsoncpp.cpp.
Member Enumeration Documentation
TokenType
enum Json::OurReader::TokenType [private]
Enumerator
tokenEndOfStream
tokenObjectBegin
tokenObjectEnd
tokenArrayBegin
tokenArrayEnd
tokenString
tokenNumber
tokenTrue
tokenFalse
tokenNull
tokenNaN
tokenPosInf
tokenNegInf
tokenArraySeparator
tokenMemberSeparator
tokenComment
tokenError
Definition at line 1162 of file jsoncpp.cpp.
                 {
    tokenEndOfStream = 0,
    tokenObjectBegin,
    tokenObjectEnd,
    tokenArrayBegin,
    tokenArrayEnd,
    tokenString,
    tokenNumber,
    tokenTrue,
    tokenFalse,
    tokenNull,
    tokenNaN,
    tokenPosInf,
    tokenNegInf,
    tokenArraySeparator,
    tokenMemberSeparator,
    tokenComment,
    tokenError
  };
Constructor & Destructor Documentation
OurReader() [1/2]
Json::OurReader::OurReader (OurFeatures const & features)
Definition at line 1255 of file jsoncpp.cpp.
    : errors_(), document_(), begin_(), end_(),
      current_(), lastValueEnd_(),
      lastValue_(), commentsBefore_(),
      features_(features), collectComments_() {
}
OurReader() [2/2]
Json::OurReader::OurReader (OurReader const &) [private]
Member Function Documentation
addComment()
void Json::OurReader::addComment (Location begin, Location end, CommentPlacement placement) [private]
Definition at line 1565 of file jsoncpp.cpp.
References collectComments_, Json::commentAfterOnSameLine, commentsBefore_, JSONCPP_STRING, lastValue_, Json::normalizeEOL(), and Json::Value::setComment().
Referenced by readComment().
                                                                              {
  assert(collectComments_);
  const JSONCPP_STRING& normalized = normalizeEOL(begin, end);
  if (placement == commentAfterOnSameLine) {
    assert(lastValue_ != 0);
    lastValue_->setComment(normalized, placement);
  } else {
    commentsBefore_ += normalized;
  }
}
addError()
bool Json::OurReader::addError (const JSONCPP_STRING & message, Token & token, Location extra = 0) [private]
Definition at line 1973 of file jsoncpp.cpp.
References errors_, Json::OurReader::ErrorInfo::extra_, Json::OurReader::ErrorInfo::message_, and Json::OurReader::ErrorInfo::token_.
Referenced by addErrorAndRecover(), decodeDouble(), decodeString(), decodeUnicodeCodePoint(), decodeUnicodeEscapeSequence(), parse(), and readValue().
                                                                               {
  ErrorInfo info;
  info.token_ = token;
  info.message_ = message;
  info.extra_ = extra;
  errors_.push_back(info);
  return false;
}
addErrorAndRecover()
bool Json::OurReader::addErrorAndRecover (const JSONCPP_STRING & message, Token & token, TokenType skipUntilToken) [private]
Definition at line 1995 of file jsoncpp.cpp.
References addError(), and recoverFromError().
Referenced by readArray(), and readObject().
                                                          {
  addError(message, token);
  return recoverFromError(skipUntilToken);
}
currentValue()
Value & Json::OurReader::currentValue () [private]
Definition at line 2002 of file jsoncpp.cpp.
References nodes_.
Referenced by decodeDouble(), decodeNumber(), decodeString(), readArray(), readObject(), and readValue().
{ return *(nodes_.top()); }
decodeDouble() [1/2]
bool Json::OurReader::decodeDouble (Token & token) [private]
Definition at line 1802 of file jsoncpp.cpp.
References begin_, currentValue(), Json::OurReader::Token::end_, Json::Value::setOffsetLimit(), Json::Value::setOffsetStart(), Json::OurReader::Token::start_, and Json::Value::swapPayload().
Referenced by decodeNumber().
                                         {
  Value decoded;
  if (!decodeDouble(token, decoded))
    return false;
  currentValue().swapPayload(decoded);
  currentValue().setOffsetStart(token.start_ - begin_);
  currentValue().setOffsetLimit(token.end_ - begin_);
  return true;
}
decodeDouble() [2/2]
bool Json::OurReader::decodeDouble (Token & token, Value & decoded) [private]
Definition at line 1812 of file jsoncpp.cpp.
References addError(), Json::OurReader::Token::end_, Json::fixNumericLocaleInput(), JSONCPP_STRING, and Json::OurReader::Token::start_.
                                                         {
  double value = 0;
  const int bufferSize = 32;
  int count;
  ptrdiff_t const length = token.end_ - token.start_;
  // Sanity check to avoid buffer overflow exploits.
  if (length < 0) {
    return addError("Unable to parse token length", token);
  }
  size_t const ulength = static_cast<size_t>(length);
  // Avoid using a string constant for the format control string given to
  // sscanf, as this can cause hard to debug crashes on OS X. See here for more
  // info:
  //
  //
       http://developer.apple.com/library/mac/#DOCUMENTATION/DeveloperTools/gcc-4.0.1/gcc/Incompatibilities.html
  char format[] = "%lf";
  if (length <= bufferSize) {
    Char buffer[bufferSize + 1];
    memcpy(buffer, token.start_, ulength);
    buffer[length] = 0;
    fixNumericLocaleInput(buffer, buffer + length);
    count = sscanf(buffer, format, &value);
  } else {
    JSONCPP_STRING buffer(token.start_, token.end_);
    count = sscanf(buffer.c_str(), format, &value);
  }
  if (count != 1)
    return addError("'" + JSONCPP_STRING(token.start_, token.end_) +
                        "' is not a number.",
                    token);
  decoded = value;
  return true;
}
decodeNumber() [1/2]
bool Json::OurReader::decodeNumber (Token & token) [private]
Definition at line 1752 of file jsoncpp.cpp.
References begin_, currentValue(), Json::OurReader::Token::end_, Json::Value::setOffsetLimit(), Json::Value::setOffsetStart(), Json::OurReader::Token::start_, and Json::Value::swapPayload().
Referenced by readObject(), and readValue().
                                         {
  Value decoded;
  if (!decodeNumber(token, decoded))
    return false;
  currentValue().swapPayload(decoded);
  currentValue().setOffsetStart(token.start_ - begin_);
  currentValue().setOffsetLimit(token.end_ - begin_);
  return true;
}
decodeNumber() [2/2]
bool Json::OurReader::decodeNumber (Token & token, Value & decoded) [private]
Definition at line 1762 of file jsoncpp.cpp.
References decodeDouble(), Json::OurReader::Token::end_, Json::Value::maxInt, Json::Value::maxLargestUInt, Json::Value::minLargestInt, and Json::OurReader::Token::start_.
                                                         {
  // Attempts to parse the number as an integer. If the number is
  // larger than the maximum supported value of an integer then
  // we decode the number as a double.
  Location current = token.start_;
  bool isNegative = *current == '-';
  if (isNegative)
    ++current;
  // TODO: Help the compiler do the div and mod at compile time or get rid of them.
  Value::LargestUInt maxIntegerValue =
      isNegative ? Value::LargestUInt(-Value::minLargestInt)
                 : Value::maxLargestUInt;
  Value::LargestUInt threshold = maxIntegerValue / 10;
  Value::LargestUInt value = 0;
  while (current < token.end_) {
    Char c = *current++;
    if (c < '0' || c > '9')
      return decodeDouble(token, decoded);
    Value::UInt digit(static_cast<Value::UInt>(c - '0'));
    if (value >= threshold) {
      // We've hit or exceeded the max value divided by 10 (rounded down). If
      // a) we've only just touched the limit, b) this is the last digit, and
      // c) it's small enough to fit in that rounding delta, we're okay.
      // Otherwise treat this number as a double to avoid overflow.
      if (value > threshold || current != token.end_ ||
          digit > maxIntegerValue % 10) {
        return decodeDouble(token, decoded);
      }
    }
    value = value * 10 + digit;
  }
  if (isNegative)
    decoded = -Value::LargestInt(value);
  else if (value <= Value::LargestUInt(Value::maxInt))
    decoded = Value::LargestInt(value);
  else
    decoded = value;
  return true;
}
decodeString() [1/2]
bool Json::OurReader::decodeString (Token & token) [private]
Definition at line 1850 of file jsoncpp.cpp.
References begin_, currentValue(), Json::OurReader::Token::end_, JSONCPP_STRING, Json::Value::setOffsetLimit(), Json::Value::setOffsetStart(), Json::OurReader::Token::start_, and Json::Value::swapPayload().
Referenced by readObject(), and readValue().
                                         {
  JSONCPP_STRING decoded_string;
  if (!decodeString(token, decoded_string))
    return false;
  Value decoded(decoded_string);
  currentValue().swapPayload(decoded);
  currentValue().setOffsetStart(token.start_ - begin_);
  currentValue().setOffsetLimit(token.end_ - begin_);
  return true;
}
decodeString() [2/2]
bool Json::OurReader::decodeString (Token & token, JSONCPP_STRING & decoded) [private]
Definition at line 1861 of file jsoncpp.cpp.
References addError(), Json::codePointToUTF8(), decodeUnicodeCodePoint(), Json::OurReader::Token::end_, and Json::OurReader::Token::start_.
                                                                  {
  decoded.reserve(static_cast<size_t>(token.end_ - token.start_ - 2));
  Location current = token.start_ + 1; // skip '"'
  Location end = token.end_ - 1; // do not include '"'
  while (current != end) {
    Char c = *current++;
    if (c == '"')
      break;
    else if (c == '\\') {
      if (current == end)
        return addError("Empty escape sequence in string", token, current);
      Char escape = *current++;
      switch (escape) {
      case '"':
        decoded += '"';
        break;
      case '/':
        decoded += '/';
        break;
      case '\\':
        decoded += '\\';
        break;
      case 'b':
        decoded += '\b';
        break;
      case 'f':
        decoded += '\f';
        break;
      case 'n':
        decoded += '\n';
        break;
      case 'r':
        decoded += '\r';
        break;
      case 't':
        decoded += '\t';
        break;
      case 'u': {
        unsigned int unicode;
        if (!decodeUnicodeCodePoint(token, current, end, unicode))
          return false;
        decoded += codePointToUTF8(unicode);
      } break;
      default:
        return addError("Bad escape sequence in string", token, current);
      }
    } else {
      decoded += c;
    }
  }
  return true;
}
decodeUnicodeCodePoint()
bool Json::OurReader::decodeUnicodeCodePoint (Token & token, Location & current, Location end, unsigned int & unicode) [private]
Definition at line 1914 of file jsoncpp.cpp.
References addError(), and decodeUnicodeEscapeSequence().
Referenced by decodeString().
                                                           {
  if (!decodeUnicodeEscapeSequence(token, current, end, unicode))
    return false;
  if (unicode >= 0xD800 && unicode <= 0xDBFF) {
    // surrogate pairs
    if (end - current < 6)
      return addError(
          "additional six characters expected to parse unicode surrogate pair.",
          token,
          current);
    unsigned int surrogatePair;
    if (*(current++) == '\\' && *(current++) == 'u') {
      if (decodeUnicodeEscapeSequence(token, current, end, surrogatePair)) {
        unicode = 0x10000 + ((unicode & 0x3FF) << 10) + (surrogatePair & 0x3FF);
      } else
        return false;
    } else
      return addError("expecting another \\u token to begin the second half of "
                      "a unicode surrogate pair",
                      token,
                      current);
  }
  return true;
}
decodeUnicodeEscapeSequence()
bool Json::OurReader::decodeUnicodeEscapeSequence (Token & token, Location & current, Location end, unsigned int & unicode) [private]
Definition at line 1943 of file jsoncpp.cpp.
References addError().
Referenced by decodeUnicodeCodePoint().
                                                                    {
  if (end - current < 4)
    return addError(
        "Bad unicode escape sequence in string: four digits expected.",
        token,
        current);
  int unicode = 0;
  for (int index = 0; index < 4; ++index) {
    Char c = *current++;
    unicode *= 16;
    if (c >= '0' && c <= '9')
      unicode += c - '0';
    else if (c >= 'a' && c <= 'f')
      unicode += c - 'a' + 10;
    else if (c >= 'A' && c <= 'F')
      unicode += c - 'A' + 10;
    else
      return addError(
          "Bad unicode escape sequence in string: hexadecimal digit expected.",
          token,
          current);
  }
  ret_unicode = static_cast<unsigned int>(unicode);
  return true;
}
getFormattedErrorMessages()
JSONCPP_STRING Json::OurReader::getFormattedErrorMessages () const
Definition at line 2041 of file jsoncpp.cpp.
References errors_, Json::OurReader::ErrorInfo::extra_, getLocationLineAndColumn(), JSONCPP_STRING, Json::OurReader::ErrorInfo::message_, Json::OurReader::Token::start_, and Json::OurReader::ErrorInfo::token_.
Referenced by Json::OurCharReader::parse().
                                                          {
  JSONCPP_STRING formattedMessage;
  for (Errors::const_iterator itError = errors_.begin();
       itError != errors_.end();
       ++itError) {
    const ErrorInfo& error = *itError;
    formattedMessage +=
        "* " + getLocationLineAndColumn(error.token_.start_) + "\n";
    formattedMessage += " " + error.message_ + "\n";
    if (error.extra_)
      formattedMessage +=
          "See " + getLocationLineAndColumn(error.extra_) + " for detail.\n";
  }
  return formattedMessage;
}
getLocationLineAndColumn() [1/2]
void Json::OurReader::getLocationLineAndColumn (Location location, int & line, int & column) const [private]
Definition at line 2010 of file jsoncpp.cpp.
References begin_, and end_.
Referenced by getFormattedErrorMessages(), and getLocationLineAndColumn().
                                                         {
  Location current = begin_;
  Location lastLineStart = current;
  line = 0;
  while (current < location && current != end_) {
    Char c = *current++;
    if (c == '\r') {
      if (*current == '\n')
        ++current;
      lastLineStart = current;
      ++line;
    } else if (c == '\n') {
      lastLineStart = current;
      ++line;
    }
  }
  // column & line start at 1
  column = int(location - lastLineStart) + 1;
  ++line;
}
getLocationLineAndColumn() [2/2]
JSONCPP_STRING Json::OurReader::getLocationLineAndColumn (Location location) const [private]
Definition at line 2033 of file jsoncpp.cpp.
References getLocationLineAndColumn().
                                                                          {
  int line, column;
  getLocationLineAndColumn(location, line, column);
  char buffer[18 + 16 + 16 + 1];
  snprintf(buffer, sizeof(buffer), "Line %d, Column %d", line, column);
  return buffer;
}
getNextChar()
OurReader::Char Json::OurReader::getNextChar () [private]
Definition at line 2004 of file jsoncpp.cpp.
References current_, and end_.
Referenced by readComment(), readCppStyleComment(), readCStyleComment(), readString(), readStringSingleQuote(), and readToken().
                                     {
  if (current_ == end_)
    return 0;
  return *current_++;
}
getStructuredErrors()
std::vector< OurReader::StructuredError > Json::OurReader::getStructuredErrors () const
Definition at line 2057 of file jsoncpp.cpp.
References begin_, Json::OurReader::Token::end_, errors_, Json::OurReader::StructuredError::message, Json::OurReader::ErrorInfo::message_, Json::OurReader::StructuredError::offset_limit, Json::OurReader::StructuredError::offset_start, Json::OurReader::Token::start_, and Json::OurReader::ErrorInfo::token_.
                                                                         {
  std::vector<OurReader::StructuredError> allErrors;
  for (Errors::const_iterator itError = errors_.begin();
       itError != errors_.end();
       ++itError) {
    const ErrorInfo& error = *itError;
    OurReader::StructuredError structured;
    structured.offset_start = error.token_.start_ - begin_;
    structured.offset_limit = error.token_.end_ - begin_;
    structured.message = error.message_;
    allErrors.push_back(structured);
  }
  return allErrors;
}
good()
bool Json::OurReader::good () const
Definition at line 2107 of file jsoncpp.cpp.
References errors_.
                           {
  return !errors_.size();
}
match()
bool Json::OurReader::match (Location pattern, int patternLength) [private]
Definition at line 1530 of file jsoncpp.cpp.
References current_, and end_.
Referenced by readToken().
                                                         {
  if (end_ - current_ < patternLength)
    return false;
  int index = patternLength;
  while (index--)
    if (current_[index] != pattern[index])
      return false;
  current_ += patternLength;
  return true;
}
operator=()
void Json::OurReader::operator= (OurReader const &) [private]
parse()
bool Json::OurReader::parse (const char * beginDoc, const char * endDoc, Value & root, bool collectComments = true)
Definition at line 1261 of file jsoncpp.cpp.
References addError(), Json::OurFeatures::allowComments_, begin_, collectComments_, Json::commentAfter, commentsBefore_, current_, Json::OurReader::Token::end_, end_, errors_, Json::OurFeatures::failIfExtra_, features_, Json::Value::isArray(), Json::Value::isObject(), lastValue_, lastValueEnd_, nodes_, readValue(), Json::Value::setComment(), skipCommentTokens(), Json::OurReader::Token::start_, Json::OurFeatures::strictRoot_, tokenEndOfStream, tokenError, and Json::OurReader::Token::type_.
Referenced by Json::OurCharReader::parse().
                                         {
  if (!features_.allowComments_) {
    collectComments = false;
  }
  begin_ = beginDoc;
  end_ = endDoc;
  collectComments_ = collectComments;
  current_ = begin_;
  lastValueEnd_ = 0;
  lastValue_ = 0;
  commentsBefore_ = "";
  errors_.clear();
  while (!nodes_.empty())
    nodes_.pop();
  nodes_.push(&root);
  bool successful = readValue();
  Token token;
  skipCommentTokens(token);
  if (features_.failIfExtra_) {
    if ((features_.strictRoot_ || token.type_ != tokenError) && token.type_
      != tokenEndOfStream) {
      addError("Extra non-whitespace after JSON value.", token);
      return false;
    }
  }
  if (collectComments_ && !commentsBefore_.empty())
    root.setComment(commentsBefore_, commentAfter);
  if (features_.strictRoot_) {
    if (!root.isArray() && !root.isObject()) {
      // Set error location to start of doc, ideally should be first token found
      // in doc
      token.type_ = tokenError;
      token.start_ = beginDoc;
      token.end_ = endDoc;
      addError(
          "A valid JSON document must be either an array or an object value.",
          token);
      return false;
    }
  }
  return successful;
}
pushError() [1/2]
bool Json::OurReader::pushError (const Value & value, const JSONCPP_STRING & message)
Definition at line 2072 of file jsoncpp.cpp.
References begin_, Json::OurReader::Token::end_, end_, errors_, Json::OurReader::ErrorInfo::extra_, Json::Value::getOffsetLimit(), Json::Value::getOffsetStart(), Json::OurReader::ErrorInfo::message_, Json::OurReader::Token::start_, Json::OurReader::ErrorInfo::token_, tokenError, and Json::OurReader::Token::type_.
                                                                           {
  ptrdiff_t length = end_ - begin_;
  if(value.getOffsetStart() > length
    || value.getOffsetLimit() > length)
    return false;
  Token token;
  token.type_ = tokenError;
  token.start_ = begin_ + value.getOffsetStart();
  token.end_ = end_ + value.getOffsetLimit();
  ErrorInfo info;
  info.token_ = token;
  info.message_ = message;
  info.extra_ = 0;
  errors_.push_back(info);
  return true;
}
pushError() [2/2]
bool Json::OurReader::pushError (const Value & value, const JSONCPP_STRING & message, const Value & extra)
Definition at line 2089 of file jsoncpp.cpp.
References begin_, Json::OurReader::Token::end_, end_, errors_, Json::OurReader::ErrorInfo::extra_, Json::Value::getOffsetLimit(), Json::Value::getOffsetStart(), Json::OurReader::ErrorInfo::message_, Json::OurReader::Token::start_, Json::OurReader::ErrorInfo::token_, tokenError, and Json::OurReader::Token::type_.
                                                                                               {
  ptrdiff_t length = end_ - begin_;
  if(value.getOffsetStart() > length
    || value.getOffsetLimit() > length
    || extra.getOffsetLimit() > length)
    return false;
  Token token;
  token.type_ = tokenError;
  token.start_ = begin_ + value.getOffsetStart();
  token.end_ = begin_ + value.getOffsetLimit();
  ErrorInfo info;
  info.token_ = token;
  info.message_ = message;
  info.extra_ = begin_ + extra.getOffsetStart();
  errors_.push_back(info);
  return true;
}
readArray()
bool Json::OurReader::readArray (Token & token) [private]
Definition at line 1714 of file jsoncpp.cpp.
References addErrorAndRecover(), Json::arrayValue, begin_, current_, currentValue(), end_, nodes_, readToken(), readValue(), recoverFromError(), Json::Value::setOffsetStart(), skipSpaces(), Json::OurReader::Token::start_, Json::Value::swapPayload(), tokenArrayEnd, tokenArraySeparator, tokenComment, and Json::OurReader::Token::type_.
Referenced by readValue().
                                           {
  Value init(arrayValue);
  currentValue().swapPayload(init);
  currentValue().setOffsetStart(tokenStart.start_ -
      begin_);
  skipSpaces();
  if (current_ != end_ && *current_ == ']') // empty array
  {
    Token endArray;
    readToken(endArray);
    return true;
  }
  int index = 0;
  for (;;) {
    Value& value = currentValue()[index++];
    nodes_.push(&value);
    bool ok = readValue();
    nodes_.pop();
    if (!ok) // error already set
      return recoverFromError(tokenArrayEnd);
    Token token;
    // Accept Comment after last item in the array.
    ok = readToken(token);
    while (token.type_ == tokenComment && ok) {
      ok = readToken(token);
    }
    bool badTokenType =
        (token.type_ != tokenArraySeparator && token.type_ !=
      tokenArrayEnd);
    if (!ok || badTokenType) {
      return addErrorAndRecover(
          "Missing ',' or ']' in array declaration", token, tokenArrayEnd);
    }
    if (token.type_ == tokenArrayEnd)
      break;
  }
  return true;
}
readComment()
bool Json::OurReader::readComment () [private]
Definition at line 1541 of file jsoncpp.cpp.
References addComment(), collectComments_, Json::commentAfterOnSameLine, Json::commentBefore, Json::containsNewLine(), current_, getNextChar(), lastValueEnd_, readCppStyleComment(), and readCStyleComment().
Referenced by readToken().
                            {
  Location commentBegin = current_ - 1;
  Char c = getNextChar();
  bool successful = false;
  if (c == '*')
    successful = readCStyleComment();
  else if (c == '/')
    successful = readCppStyleComment();
  if (!successful)
    return false;
  if (collectComments_) {
    CommentPlacement placement = commentBefore;
    if (lastValueEnd_ && !containsNewLine(
      lastValueEnd_, commentBegin)) {
      if (c != '*' || !containsNewLine(commentBegin, current_))
        placement = commentAfterOnSameLine;
    }
    addComment(commentBegin, current_, placement);
  }
  return true;
}
readCppStyleComment()
bool Json::OurReader::readCppStyleComment () [private]
Definition at line 1585 of file jsoncpp.cpp.
References current_, end_, and getNextChar().
Referenced by readComment().
                                    {
  while (current_ != end_) {
    Char c = getNextChar();
    if (c == '\n')
      break;
    if (c == '\r') {
      // Consume DOS EOL. It will be normalized in addComment.
      if (current_ != end_ && *current_ == '\n')
        getNextChar();
      // Break on Moc OS 9 EOL.
      break;
    }
  }
  return true;
}
readCStyleComment()
bool Json::OurReader::readCStyleComment () [private]
Definition at line 1576 of file jsoncpp.cpp.
References current_, end_, and getNextChar().
Referenced by readComment().
                                  {
  while ((current_ + 1) < end_) {
    Char c = getNextChar();
    if (c == '*' && *current_ == '/')
      break;
  }
  return getNextChar() == '/';
}
readNumber()
bool Json::OurReader::readNumber (bool checkInf) [private]
Definition at line 1601 of file jsoncpp.cpp.
References current_, and end_.
Referenced by readToken().
                                        {
  const char *p = current_;
  if (checkInf && p != end_ && *p == 'I') {
    current_ = ++p;
    return false;
  }
  char c = '0'; // stopgap for already consumed character
  // integral part
  while (c >= '0' && c <= '9')
    c = (current_ = p) < end_ ? *p++ : '\0';
  // fractional part
  if (c == '.') {
    c = (current_ = p) < end_ ? *p++ : '\0';
    while (c >= '0' && c <= '9')
      c = (current_ = p) < end_ ? *p++ : '\0';
  }
  // exponential part
  if (c == 'e' || c == 'E') {
    c = (current_ = p) < end_ ? *p++ : '\0';
    if (c == '+' || c == '-')
      c = (current_ = p) < end_ ? *p++ : '\0';
    while (c >= '0' && c <= '9')
      c = (current_ = p) < end_ ? *p++ : '\0';
  }
  return true;
}
readObject()
bool Json::OurReader::readObject (Token & token) [private]
Definition at line 1652 of file jsoncpp.cpp.
References addErrorAndRecover(), Json::OurFeatures::allowNumericKeys_, Json::Value::asString(), begin_, currentValue(), decodeNumber(), decodeString(), features_, JSONCPP_STRING, nodes_, Json::objectValue, readToken(), readValue(), recoverFromError(), Json::OurFeatures::rejectDupKeys_, Json::Value::setOffsetStart(), Json::OurReader::Token::start_, Json::Value::swapPayload(), Json::throwRuntimeError(), tokenArraySeparator, tokenComment, tokenMemberSeparator, tokenNumber, tokenObjectEnd, tokenString, and Json::OurReader::Token::type_.
Referenced by readValue().
                                            {
  Token tokenName;
  JSONCPP_STRING name;
  Value init(objectValue);
  currentValue().swapPayload(init);
  currentValue().setOffsetStart(tokenStart.start_ -
      begin_);
  while (readToken(tokenName)) {
    bool initialTokenOk = true;
    while (tokenName.type_ == tokenComment && initialTokenOk)
      initialTokenOk = readToken(tokenName);
    if (!initialTokenOk)
      break;
    if (tokenName.type_ == tokenObjectEnd && name.empty()) // empty object
      return true;
    name = "";
    if (tokenName.type_ == tokenString) {
      if (!decodeString(tokenName, name))
        return recoverFromError(tokenObjectEnd);
    } else if (tokenName.type_ == tokenNumber && features_.
      allowNumericKeys_) {
      Value numberName;
      if (!decodeNumber(tokenName, numberName))
        return recoverFromError(tokenObjectEnd);
      name = numberName.asString();
    } else {
      break;
    }
    Token colon;
    if (!readToken(colon) || colon.type_ != tokenMemberSeparator) {
      return addErrorAndRecover(
          "Missing ':' after object member name", colon, tokenObjectEnd);
    }
    if (name.length() >= (1U<<30)) throwRuntimeError("keylength >= 2^30");
    if (features_.rejectDupKeys_ && currentValue().isMember(name)) {
      JSONCPP_STRING msg = "Duplicate key: '" + name + "'";
      return addErrorAndRecover(
          msg, tokenName, tokenObjectEnd);
    }
    Value& value = currentValue()[name];
    nodes_.push(&value);
    bool ok = readValue();
    nodes_.pop();
    if (!ok) // error already set
      return recoverFromError(tokenObjectEnd);
    Token comma;
    if (!readToken(comma) ||
        (comma.type_ != tokenObjectEnd && comma.type_ !=
      tokenArraySeparator &&
         comma.type_ != tokenComment)) {
      return addErrorAndRecover(
          "Missing ',' or '}' in object declaration", comma, tokenObjectEnd);
    }
    bool finalizeTokenOk = true;
    while (comma.type_ == tokenComment && finalizeTokenOk)
      finalizeTokenOk = readToken(comma);
    if (comma.type_ == tokenObjectEnd)
      return true;
  }
  return addErrorAndRecover(
      "Missing '}' or object member name", tokenName, tokenObjectEnd);
}
readString()
bool Json::OurReader::readString () [private]
Definition at line 1627 of file jsoncpp.cpp.
References current_, end_, and getNextChar().
Referenced by readToken().
                           {
  Char c = 0;
  while (current_ != end_) {
    c = getNextChar();
    if (c == '\\')
      getNextChar();
    else if (c == '"')
      break;
  }
  return c == '"';
}
readStringSingleQuote()
bool Json::OurReader::readStringSingleQuote () [private]
Definition at line 1640 of file jsoncpp.cpp.
References current_, end_, and getNextChar().
Referenced by readToken().
                                      {
  Char c = 0;
  while (current_ != end_) {
    c = getNextChar();
    if (c == '\\')
      getNextChar();
    else if (c == '\'')
      break;
  }
  return c == '\'';
}
readToken()
bool Json::OurReader::readToken (Token & token) [private]
Definition at line 1420 of file jsoncpp.cpp.
References Json::OurFeatures::allowSingleQuotes_, Json::OurFeatures::allowSpecialFloats_, current_, Json::OurReader::Token::end_, features_, getNextChar(), match(), readComment(), readNumber(), readString(), readStringSingleQuote(), skipSpaces(), Json::OurReader::Token::start_, tokenArrayBegin, tokenArrayEnd, tokenArraySeparator, tokenComment, tokenEndOfStream, tokenError, tokenFalse, tokenMemberSeparator, tokenNaN, tokenNegInf, tokenNull, tokenNumber, tokenObjectBegin, tokenObjectEnd, tokenPosInf, tokenString, tokenTrue, and Json::OurReader::Token::type_.
Referenced by readArray(), readObject(), recoverFromError(), and skipCommentTokens().
                                      {
  skipSpaces();
  token.start_ = current_;
  Char c = getNextChar();
  bool ok = true;
  switch (c) {
  case '{':
    token.type_ = tokenObjectBegin;
    break;
  case '}':
    token.type_ = tokenObjectEnd;
    break;
  case '[':
    token.type_ = tokenArrayBegin;
    break;
  case ']':
    token.type_ = tokenArrayEnd;
    break;
  case '"':
    token.type_ = tokenString;
    ok = readString();
    break;
  case '\'':
    if (features_.allowSingleQuotes_) {
    token.type_ = tokenString;
    ok = readStringSingleQuote();
    break;
    } // else continue
  case '/':
    token.type_ = tokenComment;
    ok = readComment();
    break;
  case '0':
  case '1':
  case '2':
  case '3':
  case '4':
  case '5':
  case '6':
  case '7':
  case '8':
  case '9':
    token.type_ = tokenNumber;
    readNumber(false);
    break;
  case '-':
    if (readNumber(true)) {
      token.type_ = tokenNumber;
    } else {
      token.type_ = tokenNegInf;
      ok = features_.allowSpecialFloats_ && match("nfinity", 7);
    }
    break;
  case 't':
    token.type_ = tokenTrue;
    ok = match("rue", 3);
    break;
  case 'f':
    token.type_ = tokenFalse;
    ok = match("alse", 4);
    break;
  case 'n':
    token.type_ = tokenNull;
    ok = match("ull", 3);
    break;
  case 'N':
    if (features_.allowSpecialFloats_) {
      token.type_ = tokenNaN;
      ok = match("aN", 2);
    } else {
      ok = false;
    }
    break;
  case 'I':
    if (features_.allowSpecialFloats_) {
      token.type_ = tokenPosInf;
      ok = match("nfinity", 7);
    } else {
      ok = false;
    }
    break;
  case ',':
    token.type_ = tokenArraySeparator;
    break;
  case ':':
    token.type_ = tokenMemberSeparator;
    break;
  case 0:
    token.type_ = tokenEndOfStream;
    break;
  default:
    ok = false;
    break;
  }
  if (!ok)
    token.type_ = tokenError;
  token.end_ = current_;
  return true;
}
readValue()
bool Json::OurReader::readValue () [private]
Definition at line 1308 of file jsoncpp.cpp.
References addError(), Json::OurFeatures::allowDroppedNullPlaceholders_, begin_, collectComments_, Json::commentBefore, commentsBefore_, current_, currentValue(), decodeNumber(), decodeString(), Json::OurReader::Token::end_, features_, lastValue_, lastValueEnd_, nodes_, readArray(), readObject(), Json::Value::setComment(), Json::Value::setOffsetLimit(), Json::Value::setOffsetStart(), skipCommentTokens(), Json::OurFeatures::stackLimit_, Json::OurReader::Token::start_, Json::Value::swapPayload(), Json::throwRuntimeError(), tokenArrayBegin, tokenArrayEnd, tokenArraySeparator, tokenFalse, tokenNaN, tokenNegInf, tokenNull, tokenNumber, tokenObjectBegin, tokenObjectEnd, tokenPosInf, tokenString, tokenTrue, and Json::OurReader::Token::type_.
Referenced by parse(), readArray(), and readObject().
                          {
  // To preserve the old behaviour we cast size_t to int.
  if (static_cast<int>(nodes_.size()) > features_.stackLimit_)
      throwRuntimeError("Exceeded stackLimit in readValue().");
  Token token;
  skipCommentTokens(token);
  bool successful = true;
  if (collectComments_ && !commentsBefore_.empty()) {
    currentValue().setComment(commentsBefore_,
      commentBefore);
    commentsBefore_ = "";
  }
  switch (token.type_) {
  case tokenObjectBegin:
    successful = readObject(token);
    currentValue().setOffsetLimit(current_ -
      begin_);
    break;
  case tokenArrayBegin:
    successful = readArray(token);
    currentValue().setOffsetLimit(current_ -
      begin_);
    break;
  case tokenNumber:
    successful = decodeNumber(token);
    break;
  case tokenString:
    successful = decodeString(token);
    break;
  case tokenTrue:
    {
    Value v(true);
    currentValue().swapPayload(v);
    currentValue().setOffsetStart(token.start_ -
      begin_);
    currentValue().setOffsetLimit(token.end_ - begin_);
    }
    break;
  case tokenFalse:
    {
    Value v(false);
    currentValue().swapPayload(v);
    currentValue().setOffsetStart(token.start_ -
      begin_);
    currentValue().setOffsetLimit(token.end_ - begin_);
    }
    break;
  case tokenNull:
    {
    Value v;
    currentValue().swapPayload(v);
    currentValue().setOffsetStart(token.start_ -
      begin_);
    currentValue().setOffsetLimit(token.end_ - begin_);
    }
    break;
  case tokenNaN:
    {
    Value v(std::numeric_limits<double>::quiet_NaN());
    currentValue().swapPayload(v);
    currentValue().setOffsetStart(token.start_ -
      begin_);
    currentValue().setOffsetLimit(token.end_ - begin_);
    }
    break;
  case tokenPosInf:
    {
    Value v(std::numeric_limits<double>::infinity());
    currentValue().swapPayload(v);
    currentValue().setOffsetStart(token.start_ -
      begin_);
    currentValue().setOffsetLimit(token.end_ - begin_);
    }
    break;
  case tokenNegInf:
    {
    Value v(-std::numeric_limits<double>::infinity());
    currentValue().swapPayload(v);
    currentValue().setOffsetStart(token.start_ -
      begin_);
    currentValue().setOffsetLimit(token.end_ - begin_);
    }
    break;
  case tokenArraySeparator:
  case tokenObjectEnd:
  case tokenArrayEnd:
    if (features_.allowDroppedNullPlaceholders_) {
      // "Un-read" the current token and mark the current value as a null
      // token.
      current_--;
      Value v;
      currentValue().swapPayload(v);
      currentValue().setOffsetStart(current_ -
      begin_ - 1);
      currentValue().setOffsetLimit(current_ -
      begin_);
      break;
    } // else, fall through ...
  default:
    currentValue().setOffsetStart(token.start_ -
      begin_);
    currentValue().setOffsetLimit(token.end_ - begin_);
    return addError("Syntax error: value, object or array expected.", token);
  }
  if (collectComments_) {
    lastValueEnd_ = current_;
    lastValue_ = &currentValue();
  }
  return successful;
}
recoverFromError()
bool Json::OurReader::recoverFromError (TokenType skipUntilToken) [private]
Definition at line 1982 of file jsoncpp.cpp.
References errors_, readToken(), tokenEndOfStream, and Json::OurReader::Token::type_.
Referenced by addErrorAndRecover(), readArray(), and readObject().
                                                         {
  size_t errorCount = errors_.size();
  Token skip;
  for (;;) {
    if (!readToken(skip))
      errors_.resize(errorCount); // discard errors caused by recovery
    if (skip.type_ == skipUntilToken || skip.type_ == tokenEndOfStream)
      break;
  }
  errors_.resize(errorCount);
  return false;
}
skipCommentTokens()
void Json::OurReader::skipCommentTokens (Token & token) [private]
Definition at line 1410 of file jsoncpp.cpp.
References Json::OurFeatures::allowComments_, features_, readToken(), tokenComment, and Json::OurReader::Token::type_.
Referenced by parse(), and readValue().
                                              {
  if (features_.allowComments_) {
    do {
      readToken(token);
    } while (token.type_ == tokenComment);
  } else {
    readToken(token);
  }
}
skipSpaces()
void Json::OurReader::skipSpaces () [private]
Definition at line 1520 of file jsoncpp.cpp.
References current_, and end_.
Referenced by readArray(), and readToken().
                           {
  while (current_ != end_) {
    Char c = *current_;
    if (c == ' ' || c == '\t' || c == '\r' || c == '\n')
      ++current_;
    else
      break;
  }
}
skipUntilSpace()
void Json::OurReader::skipUntilSpace () [private]
Member Data Documentation
begin_
Location Json::OurReader::begin_ [private]
Definition at line 1242 of file jsoncpp.cpp.
Referenced by decodeDouble(), decodeNumber(), decodeString(), getLocationLineAndColumn(), getStructuredErrors(), parse(), pushError(), readArray(), readObject(), and readValue().
collectComments_
bool Json::OurReader::collectComments_ [private]
Definition at line 1250 of file jsoncpp.cpp.
Referenced by addComment(), parse(), readComment(), and readValue().
commentsBefore_
JSONCPP_STRING Json::OurReader::commentsBefore_ [private]
Definition at line 1247 of file jsoncpp.cpp.
Referenced by addComment(), parse(), and readValue().
current_
Location Json::OurReader::current_ [private]
Definition at line 1244 of file jsoncpp.cpp.
Referenced by getNextChar(), match(), parse(), readArray(), readComment(), readCppStyleComment(), readCStyleComment(), readNumber(), readString(), readStringSingleQuote(), readToken(), readValue(), and skipSpaces().
document_
JSONCPP_STRING Json::OurReader::document_ [private]
Definition at line 1241 of file jsoncpp.cpp.
end_
Location Json::OurReader::end_ [private]
Definition at line 1243 of file jsoncpp.cpp.
Referenced by getLocationLineAndColumn(), getNextChar(), match(), parse(), pushError(), readArray(), readCppStyleComment(), readCStyleComment(), readNumber(), readString(), readStringSingleQuote(), and skipSpaces().
errors_
Errors Json::OurReader::errors_ [private]
Definition at line 1240 of file jsoncpp.cpp.
Referenced by addError(), getFormattedErrorMessages(), getStructuredErrors(), good(), parse(), pushError(), and recoverFromError().
features_
OurFeatures const Json::OurReader::features_ [private]
Definition at line 1249 of file jsoncpp.cpp.
Referenced by parse(), readObject(), readToken(), readValue(), and skipCommentTokens().
lastValue_
Value* Json::OurReader::lastValue_ [private]
Definition at line 1246 of file jsoncpp.cpp.
Referenced by addComment(), parse(), and readValue().
lastValueEnd_
Location Json::OurReader::lastValueEnd_ [private]
Definition at line 1245 of file jsoncpp.cpp.
Referenced by parse(), readComment(), and readValue().
nodes_
Nodes Json::OurReader::nodes_ [private]
Definition at line 1239 of file jsoncpp.cpp.
Referenced by currentValue(), parse(), readArray(), readObject(), and readValue().
The documentation for this class was generated from the following file:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/jsoncpp.cpp