Json::ValueIteratorBase Class Reference
base class for Value iterators.
#include <json.h>
Public Types
typedef std::bidirectional_iterator_tag iterator_category
typedef unsigned int size_t
typedef int difference_type
typedef ValueIteratorBase SelfType
Public Member Functions
bool operator== (const SelfType &other) const
bool operator!= (const SelfType &other) const
difference_type operator- (const SelfType &other) const
Value key () const
UInt index () const
Return the index of the referenced Value, or -1 if it is not an arrayValue.
JSONCPP_STRING name () const
char const * memberName () const
char const * memberName (char const **end) const
ValueIteratorBase ()
ValueIteratorBase (const Value::ObjectValues::iterator &current)
Protected Member Functions
Value & deref () const
void increment ()
void decrement ()
difference_type computeDistance (const SelfType &other) const
bool isEqual (const SelfType &other) const
void copy (const SelfType &other)
Private Attributes
Value::ObjectValues::iterator current_
bool isNull_
Detailed Description
base class for Value iterators.
Definition at line 1133 of file json.h.
Member Typedef Documentation
difference_type
typedef int Json::ValueIteratorBase::difference_type
Definition at line 1137 of file json.h.
iterator_category
typedef std::bidirectional_iterator_tag Json::ValueIteratorBase::iterator_category
Definition at line 1135 of file json.h.
SelfType
typedef ValueIteratorBase Json::ValueIteratorBase::SelfType
Definition at line 1138 of file json.h.
size_t
typedef unsigned int Json::ValueIteratorBase::size_t
Definition at line 1136 of file json.h.
Constructor & Destructor Documentation
ValueIteratorBase() [1/2]
Json::ValueIteratorBase::ValueIteratorBase ()
Definition at line 2284 of file jsoncpp.cpp.
    : current_(), isNull_(true) {
}
ValueIteratorBase() [2/2]
Json::ValueIteratorBase::ValueIteratorBase (const Value::ObjectValues::iterator & current) [explicit]
Definition at line 2288 of file jsoncpp.cpp.
    : current_(current), isNull_(false) {}
Member Function Documentation
computeDistance()
ValueIteratorBase::difference_type Json::ValueIteratorBase::computeDistance (const SelfType & other) const [protected]
Definition at line 2305 of file jsoncpp.cpp.
References current_, and isNull_.
Referenced by operator-().
                                                              {
#ifdef JSON_USE_CPPTL_SMALLMAP
  return other.current_ - current_;
#else
  // Iterator for null value are initialized using the default
  // constructor, which initialize current_ to the default
  // std::map::iterator. As begin() and end() are two instance
  // of the default std::map::iterator, they can not be compared.
  // To allow this, we handle this comparison specifically.
  if (isNull_ && other.isNull_) {
    return 0;
  }
  // Usage of std::distance is not portable (does not compile with Sun Studio 12
  // RogueWave STL,
  // which is the one used by default).
  // Using a portable hand-made version for non random iterator instead:
  // return difference_type(std::distance(current_, other.current_));
  difference_type myDistance = 0;
  for (Value::ObjectValues::iterator it = current_; it != other.current_;
       ++it) {
    ++myDistance;
  }
  return myDistance;
#endif
}
copy()
void Json::ValueIteratorBase::copy (const SelfType & other) [protected]
Definition at line 2339 of file jsoncpp.cpp.
References current_, and isNull_.
Referenced by Json::ValueConstIterator::operator=(), and Json::ValueIterator::operator=().
                                                  {
  current_ = other.current_;
  isNull_ = other.isNull_;
}
decrement()
void Json::ValueIteratorBase::decrement () [protected]
Definition at line 2300 of file jsoncpp.cpp.
References current_.
                                  {
  --current_;
}
deref()
Value & Json::ValueIteratorBase::deref () const [protected]
Definition at line 2292 of file jsoncpp.cpp.
References current_.
                                      {
  return current_->second;
}
increment()
void Json::ValueIteratorBase::increment () [protected]
Definition at line 2296 of file jsoncpp.cpp.
References current_.
                                  {
  ++current_;
}
index()
UInt Json::ValueIteratorBase::index () const
Return the index of the referenced Value, or -1 if it is not an arrayValue.
Definition at line 2354 of file jsoncpp.cpp.
References Json::Value::CZString::data(), and Json::Value::CZString::index().
                                    {
  const Value::CZString czstring = (*current_).first;
  if (!czstring.data())
    return czstring.index();
  return Value::UInt(-1);
}
isEqual()
bool Json::ValueIteratorBase::isEqual (const SelfType & other) const [protected]
Definition at line 2332 of file jsoncpp.cpp.
References current_, and isNull_.
                                                           {
  if (isNull_) {
    return other.isNull_;
  }
  return current_ == other.current_;
}
key()
Value Json::ValueIteratorBase::key () const
Return either the index or the member name of the referenced value as a Value.
Definition at line 2344 of file jsoncpp.cpp.
References Json::Value::CZString::data(), Json::Value::CZString::index(), Json::Value::CZString::isStaticString(), and Json::Value::CZString::length().
                                   {
  const Value::CZString czstring = (*current_).first;
  if (czstring.data()) {
    if (czstring.isStaticString())
      return Value(StaticString(czstring.data()));
    return Value(czstring.data(), czstring.data() + czstring.length());
  }
  return Value(czstring.index());
}
memberName() [1/2]
char const * Json::ValueIteratorBase::memberName () const
Return the member name of the referenced Value. `` if it is not an objectValue.
Deprecated
Deprecated This cannot be used for UTF-8 strings, since there can be embedded nulls.
Definition at line 2369 of file jsoncpp.cpp.
Referenced by name().
                                                {
  const char* cname = (*current_).first.data();
  return cname ? cname : "";
}
memberName() [2/2]
char const * Json::ValueIteratorBase::memberName (char const ** end) const
Return the member name of the referenced Value, or NULL if it is not an objectValue.
Note
Better version than memberName(). Allows embedded nulls.
Definition at line 2374 of file jsoncpp.cpp.
                                                                {
  const char* cname = (*current_).first.data();
  if (!cname) {
    *end = NULL;
    return NULL;
  }
  *end = cname + (*current_).first.length();
  return cname;
}
name()
JSONCPP_STRING Json::ValueIteratorBase::name () const
Return the member name of the referenced Value, or `` if it is not an objectValue.
Note
Avoid c_str() on result, as embedded zeroes are possible.
Definition at line 2361 of file jsoncpp.cpp.
References JSONCPP_STRING, and memberName().
                                             {
  char const* keey;
  char const* end;
  keey = memberName(&end);
  if (!keey) return JSONCPP_STRING();
  return JSONCPP_STRING(keey, end);
}
operator!=()
bool Json::ValueIteratorBase::operator!= (const SelfType & other) const [inline]
Definition at line 1142 of file json.h.
{ return !isEqual(other); }
operator-()
difference_type Json::ValueIteratorBase::operator- (const SelfType & other) const [inline]
Definition at line 1144 of file json.h.
References computeDistance(), JSONCPP_DEPRECATED, and JSONCPP_STRING.
                                                         {
    return other.computeDistance(*this);
  }
operator==()
bool Json::ValueIteratorBase::operator== (const SelfType & other) const [inline]
Definition at line 1140 of file json.h.
{ return isEqual(other); }
Member Data Documentation
current_
Value::ObjectValues::iterator Json::ValueIteratorBase::current_ [private]
Definition at line 1184 of file json.h.
Referenced by computeDistance(), copy(), decrement(), deref(), increment(), and isEqual().
isNull_
bool Json::ValueIteratorBase::isNull_ [private]
Definition at line 1186 of file json.h.
Referenced by computeDistance(), copy(), and isEqual().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/json.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/jsoncpp.cpp