Texture Class Reference
#include <Texture.h>
Public Member Functions
Texture ()
~Texture ()
bool loadFromFile (std::string path, SDL_Renderer *renderer)
Loads image at specified path.
bool loadFromRenderedText (std::string textureText, SDL_Color textColor, SDL_Renderer *renderer, TTF_Font *gFont, int wrapLength)
Creates image from font string.
void free ()
Deallocates texture.
void render (int x, int y, SDL_Renderer *renderer, SDL_Rect *clip=NULL, double angle=0.0, SDL_Point *center=NULL, SDL_RendererFlip flip=SDL_FLIP_NONE)
Renders texture at given point.
void setColor (int r, int g, int b)
sets the sprites RBG values
SDL_Texture * getSDLTexture ()
returns the SDL texture
int getWidth ()
Gets image width.
int getHeight ()
Gets image height.
Private Attributes
SDL_Texture * mTexture
The actual hardware texture.
int mWidth
Image dimensions.
int mHeight
Detailed Description
Implementation is based on the LTexture class from http://lazyfoo.net/tutorials/SDL/12_color_modulation/index.php it is a wrapper surrounding the SDL_Texture class
Definition at line 13 of file Texture.h.
Constructor & Destructor Documentation
Texture()
Texture::Texture ()
Definition at line 5 of file Texture.cpp.
References mHeight, mTexture, and mWidth.
{
    //Initialize
    mTexture = NULL;
    mWidth = 0;
    mHeight = 0;
}
 Texture()
Texture::~Texture ()
Definition at line 14 of file Texture.cpp.
References free().
{
    //Deallocate
    free();
}
Member Function Documentation
free()
void Texture::free ()
Deallocates texture.
Frees up the memory space the texture is occupying
Definition at line 114 of file Texture.cpp.
References mTexture.
Referenced by Sprite::free(), TextBox::freeComment(), loadFromFile(), loadFromRenderedText(), and ~Texture().
{
    //Free texture if it exists
    if (mTexture != NULL)
    {
        SDL_DestroyTexture(mTexture);
        mTexture = NULL;
    }
}
getHeight()
int Texture::getHeight ()
Gets image height.
get the Textures height
Definition at line 164 of file Texture.cpp.
References mTexture.
Referenced by Sprite::loadMedia(), and TextBox::loadText().
{
    int w, h;
    SDL_QueryTexture(mTexture, NULL, NULL, &w, &h);
    return h;
}
getSDLTexture()
SDL_Texture * Texture::getSDLTexture ()
returns the SDL texture
Return the SDL_Texture pointer
Definition at line 67 of file Texture.cpp.
References mTexture.
{
    return mTexture;
}
getWidth()
int Texture::getWidth ()
Gets image width.
get the Textures width
Definition at line 154 of file Texture.cpp.
References mTexture.
Referenced by Sprite::loadMedia(), and TextBox::loadText().
{
    int w, h;
    SDL_QueryTexture(mTexture, NULL, NULL, &w, &h);
    return w;
}
loadFromFile()
bool Texture::loadFromFile (std::string path, SDL_Renderer * renderer)
Loads image at specified path.
Loads in a PNG images as a texture to the game
Definition at line 23 of file Texture.cpp.
References free(), mHeight, mTexture, and mWidth.
Referenced by Sprite::loadMedia().
{
    //Get rid of preexisting texture
    free();
    //The final texture
    SDL_Texture* newTexture = NULL;
    //Load image at specified path
    SDL_Surface* loadedSurface = IMG_Load(path.c_str());
    if (loadedSurface == NULL)
    {
        printf("Unable to load image %s! SDL_image Error: %s\n", path.c_str(), IMG_GetError());
    }
    else
    {
        //Color key image
        SDL_SetColorKey(loadedSurface, SDL_TRUE, SDL_MapRGB(loadedSurface->format, 0, 0xFF, 0xFF));
        //Create texture from surface pixels
        newTexture = SDL_CreateTextureFromSurface(renderer, loadedSurface);
        if (newTexture == NULL)
        {
            printf("Unable to create texture from %s! SDL Error: %s\n", path.c_str(), SDL_GetError());
        }
        else
        {
            //Get image dimensions
            mWidth = loadedSurface->w;
            mHeight = loadedSurface->h;
        }
        //Get rid of old loaded surface
        SDL_FreeSurface(loadedSurface);
    }
    //Return success
    mTexture = newTexture;
    return mTexture != NULL;
}
loadFromRenderedText()
bool Texture::loadFromRenderedText (std::string textureText, SDL_Color textColor, SDL_Renderer * renderer, TTF_Font * gFont, int wrapLength)
Creates image from font string.
loads in any parsed in text as a texture, we want the text to wrap depending on width
Definition at line 75 of file Texture.cpp.
References free(), mHeight, mTexture, and mWidth.
Referenced by TextBox::loadText().
{
    //Get rid of preexisting texture
    free();
    //Render text surface
    SDL_Surface* textSurface = TTF_RenderText_Blended_Wrapped(gFont, textureText.c_str(), textColor,
      wrapLength);
    if (textSurface == NULL)
    {
        printf("Unable to render text surface! SDL_ttf Error: %s\n", TTF_GetError());
    }
    else
    {
        
        //Create texture from surface pixels
        mTexture = SDL_CreateTextureFromSurface(renderer, textSurface);
        if (mTexture == NULL)
        {
            printf("Unable to create texture from rendered text! SDL Error: %s\n", SDL_GetError());
        }
        else
        {
            //Get image dimensions
            mWidth = textSurface->w;
            mHeight = textSurface->h;
        }
        //Get rid of old surface
        SDL_FreeSurface(textSurface);
    }
    //Return success
    return mTexture != NULL;
}
render()
void Texture::render (int x, int y, SDL_Renderer * renderer, SDL_Rect * clip = NULL, double angle = 0.0, SDL_Point * center = NULL, SDL_RendererFlip flip = SDL_FLIP_NONE)
Renders texture at given point.
Renders the image to the screen
Definition at line 135 of file Texture.cpp.
References mHeight, mTexture, and mWidth.
Referenced by Sprite::render(), and TextBox::renderComment().
{
    //Set rendering space and render to screen
    SDL_Rect renderQuad = { x, y, mWidth, mHeight };
    //Set clip rendering dimensions
    if (clip != NULL)
    {
        renderQuad.w = clip->w;
        renderQuad.h = clip->h;
    }
    //Render to screen
    SDL_RenderCopyEx(renderer, mTexture, clip, &renderQuad, angle, center, flip);
}
setColor()
void Texture::setColor (int r, int g, int b)
sets the sprites RBG values
Modulates the colour of our Texture
Definition at line 127 of file Texture.cpp.
References mTexture.
Referenced by Sprite::setColor().
{
    SDL_SetTextureColorMod(mTexture, r, g, b);
}
Member Data Documentation
mHeight
int Texture::mHeight [private]
Definition at line 48 of file Texture.h.
Referenced by loadFromFile(), loadFromRenderedText(), render(), and Texture().
mTexture
SDL_Texture* Texture::mTexture [private]
The actual hardware texture.
Definition at line 44 of file Texture.h.
Referenced by free(), getHeight(), getSDLTexture(), getWidth(), loadFromFile(), loadFromRenderedText(), render(), setColor(), and Texture().
mWidth
int Texture::mWidth [private]
Image dimensions.
Definition at line 47 of file Texture.h.
Referenced by loadFromFile(), loadFromRenderedText(), render(), and Texture().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Texture.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/Texture.cpp