Json::StyledStreamWriter Class Reference
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
#include <json.h>
Public Member Functions
StyledStreamWriter (JSONCPP_STRING indentation=`\)
~StyledStreamWriter ()
void write (JSONCPP_OSTREAM &out, const Value &root)
Serialize a Value in JSON format.
Private Types
typedef std::vector< JSONCPP_STRING > ChildValues
Private Member Functions
void writeValue (const Value &value)
void writeArrayValue (const Value &value)
bool isMultineArray (const Value &value)
void pushValue (const JSONCPP_STRING &value)
void writeIndent ()
void writeWithIndent (const JSONCPP_STRING &value)
void indent ()
void unindent ()
void writeCommentBeforeValue (const Value &root)
void writeCommentAfterValueOnSameLine (const Value &root)
bool hasCommentForValue (const Value &value)
Static Private Member Functions
static JSONCPP_STRING normalizeEOL (const JSONCPP_STRING &text)
Private Attributes
ChildValues childValues_
JSONCPP_OSTREAM * document_
JSONCPP_STRING indentString_
unsigned int rightMargin_
JSONCPP_STRING indentation_
bool addChildValues_: 1
bool indented_: 1
Detailed Description
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
The rules for line break and indent are as follow:
Object value:
if empty then print {} without indent and line break
if not empty the print '{', line break & indent, print one value per line and then unindent and line break and print '}'.
Array value:
if empty then print [] without indent and line break
if the array contains no object value, empty array or some other value types, and all the values fit on one lines, then print the array on a single line.
otherwise, it the values do not fit on one line, or the array contains object or non empty array, then print one value per line.
If the Value have comments then they are outputed according to their CommentPlacement.
Parameters
indentation Each level will be indented by this amount extra.
See also
Reader, Value, Value::setComment()
Deprecated
Deprecated Use StreamWriterBuilder.
Definition at line 2022 of file json.h.
Member Typedef Documentation
ChildValues
typedef std::vector<JSONCPP_STRING> Json::StyledStreamWriter::ChildValues [private]
Definition at line 2050 of file json.h.
Constructor & Destructor Documentation
StyledStreamWriter()
Json::StyledStreamWriter::StyledStreamWriter (JSONCPP_STRING indentation = `\t`)
Definition at line 4692 of file jsoncpp.cpp.
    : document_(NULL), rightMargin_(74), indentation_(indentation),
      addChildValues_() {}
 StyledStreamWriter()
Json::StyledStreamWriter::~StyledStreamWriter () [inline]
Definition at line 2025 of file json.h.
References JSONCPP_OSTREAM, JSONCPP_STRING, and Json::normalizeEOL().
{}
Member Function Documentation
hasCommentForValue()
bool Json::StyledStreamWriter::hasCommentForValue (const Value & value) [private]
Definition at line 4898 of file jsoncpp.cpp.
References Json::commentAfter, Json::commentAfterOnSameLine, Json::commentBefore, and Json::Value::hasComment().
Referenced by isMultineArray().
                                                              {
  return value.hasComment(commentBefore) ||
         value.hasComment(commentAfterOnSameLine) ||
         value.hasComment(commentAfter);
}
indent()
void Json::StyledStreamWriter::indent () [private]
Definition at line 4862 of file jsoncpp.cpp.
References indentation_, and indentString_.
Referenced by writeArrayValue(), and writeValue().
{ indentString_ += indentation_; }
isMultineArray()
bool Json::StyledStreamWriter::isMultineArray (const Value & value) [private]
Definition at line 4814 of file jsoncpp.cpp.
References addChildValues_, childValues_, hasCommentForValue(), Json::Value::isArray(), Json::Value::isObject(), rightMargin_, Json::Value::size(), and writeValue().
Referenced by writeArrayValue().
                                                          {
  ArrayIndex const size = value.size();
  bool isMultiLine = size * 3 >= rightMargin_;
  childValues_.clear();
  for (ArrayIndex index = 0; index < size && !isMultiLine; ++index) {
    const Value& childValue = value[index];
    isMultiLine = ((childValue.isArray() || childValue.isObject()) &&
                        childValue.size() > 0);
  }
  if (!isMultiLine) // check if line length > max line length
  {
    childValues_.reserve(size);
    addChildValues_ = true;
    ArrayIndex lineLength = 4 + (size - 1) * 2; // '[ ' + ', '*n + ' ]'
    for (ArrayIndex index = 0; index < size; ++index) {
      if (hasCommentForValue(value[index])) {
        isMultiLine = true;
      }
      writeValue(value[index]);
      lineLength += static_cast<ArrayIndex>(childValues_[index].length());
    }
    addChildValues_ = false;
    isMultiLine = isMultiLine || lineLength >= rightMargin_;
  }
  return isMultiLine;
}
normalizeEOL()
static JSONCPP_STRING Json::StyledStreamWriter::normalizeEOL (const JSONCPP_STRING & text) [static], [private]
pushValue()
void Json::StyledStreamWriter::pushValue (const JSONCPP_STRING & value) [private]
Definition at line 4841 of file jsoncpp.cpp.
References addChildValues_, childValues_, and document_.
Referenced by writeArrayValue(), and writeValue().
                                                              {
  if (addChildValues_)
    childValues_.push_back(value);
  else
    *document_ << value;
}
unindent()
void Json::StyledStreamWriter::unindent () [private]
Definition at line 4864 of file jsoncpp.cpp.
References indentation_, and indentString_.
Referenced by writeArrayValue(), and writeValue().
                                  {
  assert(indentString_.size() >= indentation_.size());
  indentString_.resize(indentString_.size() -
      indentation_.size());
}
write()
void Json::StyledStreamWriter::write (JSONCPP_OSTREAM & out, const Value & root)
Serialize a Value in JSON format.
Parameters
out Stream to write to. (Can be ostringstream, e.g.)
root Value to serialize.
Note
There is no point in deriving from Writer, since write() should not return a value.
Definition at line 4696 of file jsoncpp.cpp.
References addChildValues_, document_, indented_, indentString_, writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), and writeValue().
                                                                      {
  document_ = &out;
  addChildValues_ = false;
  indentString_ = "";
  indented_ = true;
  writeCommentBeforeValue(root);
  if (!indented_) writeIndent();
  indented_ = true;
  writeValue(root);
  writeCommentAfterValueOnSameLine(root);
  *document_ << "\n";
  document_ = NULL; // Forget the stream, for safety.
}
writeArrayValue()
void Json::StyledStreamWriter::writeArrayValue (const Value & value) [private]
Definition at line 4769 of file jsoncpp.cpp.
References childValues_, document_, indent(), indented_, isMultineArray(), pushValue(), Json::Value::size(), unindent(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), writeValue(), and writeWithIndent().
Referenced by writeValue().
                                                           {
  unsigned size = value.size();
  if (size == 0)
    pushValue("[]");
  else {
    bool isArrayMultiLine = isMultineArray(value);
    if (isArrayMultiLine) {
      writeWithIndent("[");
      indent();
      bool hasChildValue = !childValues_.empty();
      unsigned index = 0;
      for (;;) {
        const Value& childValue = value[index];
        writeCommentBeforeValue(childValue);
        if (hasChildValue)
          writeWithIndent(childValues_[index]);
        else {
          if (!indented_) writeIndent();
          indented_ = true;
          writeValue(childValue);
          indented_ = false;
        }
        if (++index == size) {
          writeCommentAfterValueOnSameLine(childValue);
          break;
        }
        *document_ << ",";
        writeCommentAfterValueOnSameLine(childValue);
      }
      unindent();
      writeWithIndent("]");
    } else // output on a single line
    {
      assert(childValues_.size() == size);
      *document_ << "[ ";
      for (unsigned index = 0; index < size; ++index) {
        if (index > 0)
          *document_ << ", ";
        *document_ << childValues_[index];
      }
      *document_ << " ]";
    }
  }
}
writeCommentAfterValueOnSameLine()
void Json::StyledStreamWriter::writeCommentAfterValueOnSameLine (const Value & root) [private]
Definition at line 4887 of file jsoncpp.cpp.
References Json::commentAfter, Json::commentAfterOnSameLine, document_, Json::Value::getComment(), Json::Value::hasComment(), indented_, and writeIndent().
Referenced by write(), writeArrayValue(), and writeValue().
                                                                           {
  if (root.hasComment(commentAfterOnSameLine))
    *document_ << ' ' << root.getComment(commentAfterOnSameLine);
  if (root.hasComment(commentAfter)) {
    writeIndent();
    *document_ << root.getComment(commentAfter);
  }
  indented_ = false;
}
writeCommentBeforeValue()
void Json::StyledStreamWriter::writeCommentBeforeValue (const Value & root) [private]
Definition at line 4869 of file jsoncpp.cpp.
References Json::commentBefore, document_, Json::Value::getComment(), Json::Value::hasComment(), indented_, indentString_, JSONCPP_STRING, and writeIndent().
Referenced by write(), writeArrayValue(), and writeValue().
                                                                  {
  if (!root.hasComment(commentBefore))
    return;
  if (!indented_) writeIndent();
  const JSONCPP_STRING& comment = root.getComment(commentBefore);
  JSONCPP_STRING::const_iterator iter = comment.begin();
  while (iter != comment.end()) {
    *document_ << *iter;
    if (*iter == '\n' &&
       (iter != comment.end() && *(iter + 1) == '/'))
      // writeIndent(); // would include newline
      *document_ << indentString_;
    ++iter;
  }
  indented_ = false;
}
writeIndent()
void Json::StyledStreamWriter::writeIndent () [private]
Definition at line 4848 of file jsoncpp.cpp.
References document_, and indentString_.
Referenced by write(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeWithIndent().
                                     {
  // blep intended this to look at the so-far-written string
  // to determine whether we are already indented, but
  // with a stream we cannot do that. So we rely on some saved state.
  // The caller checks indented_.
  *document_ << '\n' << indentString_;
}
writeValue()
void Json::StyledStreamWriter::writeValue (const Value & value) [private]
Definition at line 4710 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::asBool(), Json::Value::asDouble(), Json::Value::asLargestInt(), Json::Value::asLargestUInt(), Json::booleanValue, document_, Json::Value::getMemberNames(), Json::Value::getString(), indent(), Json::intValue, JSONCPP_STRING, Json::nullValue, Json::objectValue, pushValue(), Json::realValue, Json::stringValue, Json::Value::type(), Json::uintValue, unindent(), Json::valueToQuotedString(), Json::valueToQuotedStringN(), Json::valueToString(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeWithIndent().
Referenced by isMultineArray(), write(), and writeArrayValue().
                                                      {
  switch (value.type()) {
  case nullValue:
    pushValue("null");
    break;
  case intValue:
    pushValue(valueToString(value.asLargestInt()));
    break;
  case uintValue:
    pushValue(valueToString(value.asLargestUInt()));
    break;
  case realValue:
    pushValue(valueToString(value.asDouble()));
    break;
  case stringValue:
  {
    // Is NULL possible for value.string_? No.
    char const* str;
    char const* end;
    bool ok = value.getString(&str, &end);
    if (ok) pushValue(valueToQuotedStringN(str, static_cast<unsigned>(end-str)
      ));
    else pushValue("");
    break;
  }
  case booleanValue:
    pushValue(valueToString(value.asBool()));
    break;
  case arrayValue:
    writeArrayValue(value);
    break;
  case objectValue: {
    Value::Members members(value.getMemberNames());
    if (members.empty())
      pushValue("{}");
    else {
      writeWithIndent("{");
      indent();
      Value::Members::iterator it = members.begin();
      for (;;) {
        const JSONCPP_STRING& name = *it;
        const Value& childValue = value[name];
        writeCommentBeforeValue(childValue);
        writeWithIndent(valueToQuotedString(name.c_str()));
        *document_ << " : ";
        writeValue(childValue);
        if (++it == members.end()) {
          writeCommentAfterValueOnSameLine(childValue);
          break;
        }
        *document_ << ",";
        writeCommentAfterValueOnSameLine(childValue);
      }
      unindent();
      writeWithIndent("}");
    }
  } break;
  }
}
writeWithIndent()
void Json::StyledStreamWriter::writeWithIndent (const JSONCPP_STRING & value) [private]
Definition at line 4856 of file jsoncpp.cpp.
References document_, indented_, and writeIndent().
Referenced by writeArrayValue(), and writeValue().
                                                                    {
  if (!indented_) writeIndent();
  *document_ << value;
  indented_ = false;
}
Member Data Documentation
addChildValues_
bool Json::StyledStreamWriter::addChildValues_ [private]
Definition at line 2057 of file json.h.
Referenced by isMultineArray(), pushValue(), and write().
childValues_
ChildValues Json::StyledStreamWriter::childValues_ [private]
Definition at line 2052 of file json.h.
Referenced by isMultineArray(), pushValue(), and writeArrayValue().
document_
JSONCPP_OSTREAM* Json::StyledStreamWriter::document_ [private]
Definition at line 2053 of file json.h.
Referenced by pushValue(), write(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), writeValue(), and writeWithIndent().
indentation_
JSONCPP_STRING Json::StyledStreamWriter::indentation_ [private]
Definition at line 2056 of file json.h.
Referenced by indent(), and unindent().
indented_
bool Json::StyledStreamWriter::indented_ [private]
Definition at line 2058 of file json.h.
Referenced by write(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeWithIndent().
indentString_
JSONCPP_STRING Json::StyledStreamWriter::indentString_ [private]
Definition at line 2054 of file json.h.
Referenced by indent(), unindent(), write(), writeCommentBeforeValue(), and writeIndent().
rightMargin_
unsigned int Json::StyledStreamWriter::rightMargin_ [private]
Definition at line 2055 of file json.h.
Referenced by isMultineArray().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/json.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/jsoncpp.cpp