Json::Reader Class Reference
Unserialize a JSON document into a Value.
#include <json.h>
Classes
class ErrorInfo
struct StructuredError
An error tagged with where in the JSON text it was encountered.
class Token
Public Types
typedef char Char
typedef const Char * Location
Public Member Functions
Reader ()
Constructs a Reader allowing all features for parsing.
Reader (const Features &features)
Constructs a Reader allowing the specified feature set for parsing.
bool parse (const std::string &document, Value &root, bool collectComments=true)
Read a Value from a JSON document.
bool parse (const char *beginDoc, const char *endDoc, Value &root, bool collectComments=true)
Read a Value from a JSON document.
bool parse (JSONCPP_ISTREAM &is, Value &root, bool collectComments=true)
Parse from input stream.
JSONCPP_STRING getFormatedErrorMessages () const
Returns a user friendly string that list errors in the parsed document.
JSONCPP_STRING getFormattedErrorMessages () const
Returns a user friendly string that list errors in the parsed document.
std::vector< StructuredError > getStructuredErrors () const
Returns a vector of structured erros encounted while parsing.
bool pushError (const Value &value, const JSONCPP_STRING &message)
Add a semantic error message.
bool pushError (const Value &value, const JSONCPP_STRING &message, const Value &extra)
Add a semantic error message with extra context.
bool good () const
Return whether there are any errors.
Private Types
enum TokenType {
tokenEndOfStream = 0,
tokenObjectBegin,
tokenObjectEnd,
tokenArrayBegin,
tokenArrayEnd,
tokenString,
tokenNumber,
tokenTrue,
tokenFalse,
tokenNull,
tokenArraySeparator,
tokenMemberSeparator,
tokenComment,
tokenError
 }
typedef std::deque< ErrorInfo > Errors
typedef std::stack< Value * > Nodes
Private Member Functions
bool readToken (Token &token)
void skipSpaces ()
bool match (Location pattern, int patternLength)
bool readComment ()
bool readCStyleComment ()
bool readCppStyleComment ()
bool readString ()
void readNumber ()
bool readValue ()
bool readObject (Token &token)
bool readArray (Token &token)
bool decodeNumber (Token &token)
bool decodeNumber (Token &token, Value &decoded)
bool decodeString (Token &token)
bool decodeString (Token &token, JSONCPP_STRING &decoded)
bool decodeDouble (Token &token)
bool decodeDouble (Token &token, Value &decoded)
bool decodeUnicodeCodePoint (Token &token, Location &current, Location end, unsigned int &unicode)
bool decodeUnicodeEscapeSequence (Token &token, Location &current, Location end, unsigned int &unicode)
bool addError (const JSONCPP_STRING &message, Token &token, Location extra=0)
bool recoverFromError (TokenType skipUntilToken)
bool addErrorAndRecover (const JSONCPP_STRING &message, Token &token, TokenType skipUntilToken)
void skipUntilSpace ()
Value & currentValue ()
Char getNextChar ()
void getLocationLineAndColumn (Location location, int &line, int &column) const
JSONCPP_STRING getLocationLineAndColumn (Location location) const
void addComment (Location begin, Location end, CommentPlacement placement)
void skipCommentTokens (Token &token)
Private Attributes
Nodes nodes_
Errors errors_
JSONCPP_STRING document_
Location begin_
Location end_
Location current_
Location lastValueEnd_
Value * lastValue_
JSONCPP_STRING commentsBefore_
Features features_
bool collectComments_
Detailed Description
Unserialize a JSON document into a Value.
Deprecated
Deprecated Use CharReader and CharReaderBuilder.
Definition at line 1361 of file json.h.
Member Typedef Documentation
Char
typedef char Json::Reader::Char
Definition at line 1363 of file json.h.
Errors
typedef std::deque<ErrorInfo> Json::Reader::Errors [private]
Definition at line 1518 of file json.h.
Location
typedef const Char* Json::Reader::Location
Definition at line 1364 of file json.h.
Nodes
typedef std::stack<Value*> Json::Reader::Nodes [private]
Definition at line 1559 of file json.h.
Member Enumeration Documentation
TokenType
enum Json::Reader::TokenType [private]
Enumerator
tokenEndOfStream
tokenObjectBegin
tokenObjectEnd
tokenArrayBegin
tokenArrayEnd
tokenString
tokenNumber
tokenTrue
tokenFalse
tokenNull
tokenArraySeparator
tokenMemberSeparator
tokenComment
tokenError
Definition at line 1487 of file json.h.
                 {
    tokenEndOfStream = 0,
    tokenObjectBegin,
    tokenObjectEnd,
    tokenArrayBegin,
    tokenArrayEnd,
    tokenString,
    tokenNumber,
    tokenTrue,
    tokenFalse,
    tokenNull,
    tokenArraySeparator,
    tokenMemberSeparator,
    tokenComment,
    tokenError
  };
Constructor & Destructor Documentation
Reader() [1/2]
Json::Reader::Reader ()
Constructs a Reader allowing all features for parsing.
Definition at line 310 of file jsoncpp.cpp.
    : errors_(), document_(), begin_(), end_(),
      current_(), lastValueEnd_(),
      lastValue_(), commentsBefore_(), features_(
      Features::all()),
      collectComments_() {}
Reader() [2/2]
Json::Reader::Reader (const Features & features)
Constructs a Reader allowing the specified feature set for parsing.
Definition at line 315 of file jsoncpp.cpp.
    : errors_(), document_(), begin_(), end_(),
      current_(), lastValueEnd_(),
      lastValue_(), commentsBefore_(), features_(features),
      collectComments_() {
}
Member Function Documentation
addComment()
void Json::Reader::addComment (Location begin, Location end, CommentPlacement placement) [private]
Definition at line 609 of file jsoncpp.cpp.
References collectComments_, Json::commentAfterOnSameLine, commentsBefore_, JSONCPP_STRING, lastValue_, Json::normalizeEOL(), and Json::Value::setComment().
Referenced by readComment().
                                                                           {
  assert(collectComments_);
  const JSONCPP_STRING& normalized = normalizeEOL(begin, end);
  if (placement == commentAfterOnSameLine) {
    assert(lastValue_ != 0);
    lastValue_->setComment(normalized, placement);
  } else {
    commentsBefore_ += normalized;
  }
}
addError()
bool Json::Reader::addError (const JSONCPP_STRING & message, Token & token, Location extra = 0) [private]
Definition at line 970 of file jsoncpp.cpp.
References errors_, Json::Reader::ErrorInfo::extra_, Json::Reader::ErrorInfo::message_, and Json::Reader::ErrorInfo::token_.
Referenced by addErrorAndRecover(), decodeDouble(), decodeString(), decodeUnicodeCodePoint(), decodeUnicodeEscapeSequence(), parse(), and readValue().
                                                                            {
  ErrorInfo info;
  info.token_ = token;
  info.message_ = message;
  info.extra_ = extra;
  errors_.push_back(info);
  return false;
}
addErrorAndRecover()
bool Json::Reader::addErrorAndRecover (const JSONCPP_STRING & message, Token & token, TokenType skipUntilToken) [private]
Definition at line 992 of file jsoncpp.cpp.
References addError(), and recoverFromError().
Referenced by readArray(), and readObject().
                                                          {
  addError(message, token);
  return recoverFromError(skipUntilToken);
}
currentValue()
Value & Json::Reader::currentValue () [private]
Definition at line 999 of file jsoncpp.cpp.
References nodes_.
Referenced by decodeDouble(), decodeNumber(), decodeString(), readArray(), readObject(), and readValue().
{ return *(nodes_.top()); }
decodeDouble() [1/2]
bool Json::Reader::decodeDouble (Token & token) [private]
Definition at line 825 of file jsoncpp.cpp.
References begin_, currentValue(), Json::Reader::Token::end_, Json::Value::setOffsetLimit(), Json::Value::setOffsetStart(), Json::Reader::Token::start_, and Json::Value::swapPayload().
Referenced by decodeNumber().
                                      {
  Value decoded;
  if (!decodeDouble(token, decoded))
    return false;
  currentValue().swapPayload(decoded);
  currentValue().setOffsetStart(token.start_ - begin_);
  currentValue().setOffsetLimit(token.end_ - begin_);
  return true;
}
decodeDouble() [2/2]
bool Json::Reader::decodeDouble (Token & token, Value & decoded) [private]
Definition at line 835 of file jsoncpp.cpp.
References addError(), Json::Reader::Token::end_, JSONCPP_ISTRINGSTREAM, JSONCPP_STRING, and Json::Reader::Token::start_.
                                                      {
  double value = 0;
  JSONCPP_STRING buffer(token.start_, token.end_);
  JSONCPP_ISTRINGSTREAM is(buffer);
  if (!(is >> value))
    return addError("'" + JSONCPP_STRING(token.start_, token.end_) +
                        "' is not a number.",
                    token);
  decoded = value;
  return true;
}
decodeNumber() [1/2]
bool Json::Reader::decodeNumber (Token & token) [private]
Definition at line 773 of file jsoncpp.cpp.
References begin_, currentValue(), Json::Reader::Token::end_, Json::Value::setOffsetLimit(), Json::Value::setOffsetStart(), Json::Reader::Token::start_, and Json::Value::swapPayload().
Referenced by readObject(), and readValue().
                                      {
  Value decoded;
  if (!decodeNumber(token, decoded))
    return false;
  currentValue().swapPayload(decoded);
  currentValue().setOffsetStart(token.start_ - begin_);
  currentValue().setOffsetLimit(token.end_ - begin_);
  return true;
}
decodeNumber() [2/2]
bool Json::Reader::decodeNumber (Token & token, Value & decoded) [private]
Definition at line 783 of file jsoncpp.cpp.
References decodeDouble(), Json::Reader::Token::end_, Json::Value::maxInt, Json::Value::maxLargestInt, Json::Value::maxLargestUInt, Json::Value::minLargestInt, and Json::Reader::Token::start_.
                                                      {
  // Attempts to parse the number as an integer. If the number is
  // larger than the maximum supported value of an integer then
  // we decode the number as a double.
  Location current = token.start_;
  bool isNegative = *current == '-';
  if (isNegative)
    ++current;
  // TODO: Help the compiler do the div and mod at compile time or get rid of them.
  Value::LargestUInt maxIntegerValue =
      isNegative ? Value::LargestUInt(Value::maxLargestInt) + 1
                 : Value::maxLargestUInt;
  Value::LargestUInt threshold = maxIntegerValue / 10;
  Value::LargestUInt value = 0;
  while (current < token.end_) {
    Char c = *current++;
    if (c < '0' || c > '9')
      return decodeDouble(token, decoded);
    Value::UInt digit(static_cast<Value::UInt>(c - '0'));
    if (value >= threshold) {
      // We've hit or exceeded the max value divided by 10 (rounded down). If
      // a) we've only just touched the limit, b) this is the last digit, and
      // c) it's small enough to fit in that rounding delta, we're okay.
      // Otherwise treat this number as a double to avoid overflow.
      if (value > threshold || current != token.end_ ||
          digit > maxIntegerValue % 10) {
        return decodeDouble(token, decoded);
      }
    }
    value = value * 10 + digit;
  }
  if (isNegative && value == maxIntegerValue)
    decoded = Value::minLargestInt;
  else if (isNegative)
    decoded = -Value::LargestInt(value);
  else if (value <= Value::LargestUInt(Value::maxInt))
    decoded = Value::LargestInt(value);
  else
    decoded = value;
  return true;
}
decodeString() [1/2]
bool Json::Reader::decodeString (Token & token) [private]
Definition at line 847 of file jsoncpp.cpp.
References begin_, currentValue(), Json::Reader::Token::end_, JSONCPP_STRING, Json::Value::setOffsetLimit(), Json::Value::setOffsetStart(), Json::Reader::Token::start_, and Json::Value::swapPayload().
Referenced by readObject(), and readValue().
                                      {
  JSONCPP_STRING decoded_string;
  if (!decodeString(token, decoded_string))
    return false;
  Value decoded(decoded_string);
  currentValue().swapPayload(decoded);
  currentValue().setOffsetStart(token.start_ - begin_);
  currentValue().setOffsetLimit(token.end_ - begin_);
  return true;
}
decodeString() [2/2]
bool Json::Reader::decodeString (Token & token, JSONCPP_STRING & decoded) [private]
Definition at line 858 of file jsoncpp.cpp.
References addError(), Json::codePointToUTF8(), decodeUnicodeCodePoint(), Json::Reader::Token::end_, and Json::Reader::Token::start_.
                                                               {
  decoded.reserve(static_cast<size_t>(token.end_ - token.start_ - 2));
  Location current = token.start_ + 1; // skip '"'
  Location end = token.end_ - 1; // do not include '"'
  while (current != end) {
    Char c = *current++;
    if (c == '"')
      break;
    else if (c == '\\') {
      if (current == end)
        return addError("Empty escape sequence in string", token, current);
      Char escape = *current++;
      switch (escape) {
      case '"':
        decoded += '"';
        break;
      case '/':
        decoded += '/';
        break;
      case '\\':
        decoded += '\\';
        break;
      case 'b':
        decoded += '\b';
        break;
      case 'f':
        decoded += '\f';
        break;
      case 'n':
        decoded += '\n';
        break;
      case 'r':
        decoded += '\r';
        break;
      case 't':
        decoded += '\t';
        break;
      case 'u': {
        unsigned int unicode;
        if (!decodeUnicodeCodePoint(token, current, end, unicode))
          return false;
        decoded += codePointToUTF8(unicode);
      } break;
      default:
        return addError("Bad escape sequence in string", token, current);
      }
    } else {
      decoded += c;
    }
  }
  return true;
}
decodeUnicodeCodePoint()
bool Json::Reader::decodeUnicodeCodePoint (Token & token, Location & current, Location end, unsigned int & unicode) [private]
Definition at line 911 of file jsoncpp.cpp.
References addError(), and decodeUnicodeEscapeSequence().
Referenced by decodeString().
                                                           {
  if (!decodeUnicodeEscapeSequence(token, current, end, unicode))
    return false;
  if (unicode >= 0xD800 && unicode <= 0xDBFF) {
    // surrogate pairs
    if (end - current < 6)
      return addError(
          "additional six characters expected to parse unicode surrogate pair.",
          token,
          current);
    unsigned int surrogatePair;
    if (*(current++) == '\\' && *(current++) == 'u') {
      if (decodeUnicodeEscapeSequence(token, current, end, surrogatePair)) {
        unicode = 0x10000 + ((unicode & 0x3FF) << 10) + (surrogatePair & 0x3FF);
      } else
        return false;
    } else
      return addError("expecting another \\u token to begin the second half of "
                      "a unicode surrogate pair",
                      token,
                      current);
  }
  return true;
}
decodeUnicodeEscapeSequence()
bool Json::Reader::decodeUnicodeEscapeSequence (Token & token, Location & current, Location end, unsigned int & unicode) [private]
Definition at line 940 of file jsoncpp.cpp.
References addError().
Referenced by decodeUnicodeCodePoint().
                                                                    {
  if (end - current < 4)
    return addError(
        "Bad unicode escape sequence in string: four digits expected.",
        token,
        current);
  int unicode = 0;
  for (int index = 0; index < 4; ++index) {
    Char c = *current++;
    unicode *= 16;
    if (c >= '0' && c <= '9')
      unicode += c - '0';
    else if (c >= 'a' && c <= 'f')
      unicode += c - 'a' + 10;
    else if (c >= 'A' && c <= 'F')
      unicode += c - 'A' + 10;
    else
      return addError(
          "Bad unicode escape sequence in string: hexadecimal digit expected.",
          token,
          current);
  }
  ret_unicode = static_cast<unsigned int>(unicode);
  return true;
}
getFormatedErrorMessages()
JSONCPP_STRING Json::Reader::getFormatedErrorMessages () const
Returns a user friendly string that list errors in the parsed document.
Returns
Formatted error message with the list of errors with their location in the parsed document. An empty string is returned if no error occurred during parsing.
Deprecated
Deprecated Use getFormattedErrorMessages() instead (typo fix).
Definition at line 1039 of file jsoncpp.cpp.
References getFormattedErrorMessages().
                                                      {
  return getFormattedErrorMessages();
}
getFormattedErrorMessages()
JSONCPP_STRING Json::Reader::getFormattedErrorMessages () const
Returns a user friendly string that list errors in the parsed document.
Returns
Formatted error message with the list of errors with their location in the parsed document. An empty string is returned if no error occurred during parsing.
Definition at line 1043 of file jsoncpp.cpp.
References errors_, Json::Reader::ErrorInfo::extra_, getLocationLineAndColumn(), JSONCPP_STRING, Json::Reader::ErrorInfo::message_, Json::Reader::Token::start_, and Json::Reader::ErrorInfo::token_.
Referenced by getFormatedErrorMessages().
                                                       {
  JSONCPP_STRING formattedMessage;
  for (Errors::const_iterator itError = errors_.begin();
       itError != errors_.end();
       ++itError) {
    const ErrorInfo& error = *itError;
    formattedMessage +=
        "* " + getLocationLineAndColumn(error.token_.start_) + "\n";
    formattedMessage += " " + error.message_ + "\n";
    if (error.extra_)
      formattedMessage +=
          "See " + getLocationLineAndColumn(error.extra_) + " for detail.\n";
  }
  return formattedMessage;
}
getLocationLineAndColumn() [1/2]
void Json::Reader::getLocationLineAndColumn (Location location, int & line, int & column) const [private]
Definition at line 1007 of file jsoncpp.cpp.
References begin_, and end_.
Referenced by getFormattedErrorMessages(), and getLocationLineAndColumn().
                                                         {
  Location current = begin_;
  Location lastLineStart = current;
  line = 0;
  while (current < location && current != end_) {
    Char c = *current++;
    if (c == '\r') {
      if (*current == '\n')
        ++current;
      lastLineStart = current;
      ++line;
    } else if (c == '\n') {
      lastLineStart = current;
      ++line;
    }
  }
  // column & line start at 1
  column = int(location - lastLineStart) + 1;
  ++line;
}
getLocationLineAndColumn() [2/2]
JSONCPP_STRING Json::Reader::getLocationLineAndColumn (Location location) const [private]
Definition at line 1030 of file jsoncpp.cpp.
References getLocationLineAndColumn().
                                                                       {
  int line, column;
  getLocationLineAndColumn(location, line, column);
  char buffer[18 + 16 + 16 + 1];
  snprintf(buffer, sizeof(buffer), "Line %d, Column %d", line, column);
  return buffer;
}
getNextChar()
Reader::Char Json::Reader::getNextChar () [private]
Definition at line 1001 of file jsoncpp.cpp.
References current_, and end_.
Referenced by readComment(), readCppStyleComment(), readCStyleComment(), readString(), and readToken().
                               {
  if (current_ == end_)
    return 0;
  return *current_++;
}
getStructuredErrors()
std::vector< Reader::StructuredError > Json::Reader::getStructuredErrors () const
Returns a vector of structured erros encounted while parsing.
Returns
A (possibly empty) vector of StructuredError objects. Currently only one error can be returned, but the caller should tolerate multiple errors. This can occur if the parser recovers from a non-fatal parse error and then encounters additional errors.
Definition at line 1059 of file jsoncpp.cpp.
References begin_, Json::Reader::Token::end_, errors_, Json::Reader::StructuredError::message, Json::Reader::ErrorInfo::message_, Json::Reader::StructuredError::offset_limit, Json::Reader::StructuredError::offset_start, Json::Reader::Token::start_, and Json::Reader::ErrorInfo::token_.
                                                                   {
  std::vector<Reader::StructuredError> allErrors;
  for (Errors::const_iterator itError = errors_.begin();
       itError != errors_.end();
       ++itError) {
    const ErrorInfo& error = *itError;
    Reader::StructuredError structured;
    structured.offset_start = error.token_.start_ - begin_;
    structured.offset_limit = error.token_.end_ - begin_;
    structured.message = error.message_;
    allErrors.push_back(structured);
  }
  return allErrors;
}
good()
bool Json::Reader::good () const
Return whether there are any errors.
Returns
true if there are no errors to report false if errors have occurred.
Definition at line 1109 of file jsoncpp.cpp.
References errors_.
                        {
  return !errors_.size();
}
match()
bool Json::Reader::match (Location pattern, int patternLength) [private]
Definition at line 555 of file jsoncpp.cpp.
References current_, and end_.
Referenced by readToken().
                                                      {
  if (end_ - current_ < patternLength)
    return false;
  int index = patternLength;
  while (index--)
    if (current_[index] != pattern[index])
      return false;
  current_ += patternLength;
  return true;
}
parse() [1/3]
bool Json::Reader::parse (const std::string & document, Value & root, bool collectComments = true)
Read a Value from a JSON document.
Parameters
document UTF-8 encoded string containing the document to read.
root [out] Contains the root value of the document if it was successfully parsed.
collectComments true to collect comment and allow writing them back during serialization, false to discard comments. This parameter is ignored if Features::allowComments_ is false.
Returns
true if the document was successfully parsed, false if an error occurred.
Definition at line 321 of file jsoncpp.cpp.
References document_, JSONCPP_STRING, and std::swap().
                                                                          {
  JSONCPP_STRING documentCopy(document.data(), document.data() + document.capacity());
  std::swap(documentCopy, document_);
  const char* begin = document_.c_str();
  const char* end = begin + document_.length();
  return parse(begin, end, root, collectComments);
}
parse() [2/3]
bool Json::Reader::parse (const char * beginDoc, const char * endDoc, Value & root, bool collectComments = true)
Read a Value from a JSON document.
Parameters
beginDoc Pointer on the beginning of the UTF-8 encoded string of the document to read.
endDoc Pointer on the end of the UTF-8 encoded string of the document to read. Must be >= beginDoc.
root [out] Contains the root value of the document if it was successfully parsed.
collectComments true to collect comment and allow writing them back during serialization, false to discard comments. This parameter is ignored if Features::allowComments_ is false.
Returns
true if the document was successfully parsed, false if an error occurred.
Definition at line 342 of file jsoncpp.cpp.
References addError(), Json::Features::allowComments_, begin_, collectComments_, Json::commentAfter, commentsBefore_, current_, Json::Reader::Token::end_, end_, errors_, features_, Json::Value::isArray(), Json::Value::isObject(), lastValue_, lastValueEnd_, nodes_, readValue(), Json::Value::setComment(), skipCommentTokens(), Json::Reader::Token::start_, Json::Features::strictRoot_, tokenError, and Json::Reader::Token::type_.
                                         {
  if (!features_.allowComments_) {
    collectComments = false;
  }
  begin_ = beginDoc;
  end_ = endDoc;
  collectComments_ = collectComments;
  current_ = begin_;
  lastValueEnd_ = 0;
  lastValue_ = 0;
  commentsBefore_ = "";
  errors_.clear();
  while (!nodes_.empty())
    nodes_.pop();
  nodes_.push(&root);
  bool successful = readValue();
  Token token;
  skipCommentTokens(token);
  if (collectComments_ && !commentsBefore_.empty())
    root.setComment(commentsBefore_, commentAfter);
  if (features_.strictRoot_) {
    if (!root.isArray() && !root.isObject()) {
      // Set error location to start of doc, ideally should be first token found
      // in doc
      token.type_ = tokenError;
      token.start_ = beginDoc;
      token.end_ = endDoc;
      addError(
          "A valid JSON document must be either an array or an object value.",
          token);
      return false;
    }
  }
  return successful;
}
parse() [3/3]
bool Json::Reader::parse (JSONCPP_ISTREAM & is, Value & root, bool collectComments = true)
Parse from input stream.
See also
Json::operator>>(std::istream&, Json::Value&).
pushError() [1/2]
bool Json::Reader::pushError (const Value & value, const JSONCPP_STRING & message)
Add a semantic error message.
Parameters
value JSON Value location associated with the error
message The error message.
Returns
true if the error was successfully added, false if the Value offset exceeds the document size.
Definition at line 1074 of file jsoncpp.cpp.
References begin_, Json::Reader::Token::end_, end_, errors_, Json::Reader::ErrorInfo::extra_, Json::Value::getOffsetLimit(), Json::Value::getOffsetStart(), Json::Reader::ErrorInfo::message_, Json::Reader::Token::start_, Json::Reader::ErrorInfo::token_, tokenError, and Json::Reader::Token::type_.
                                                                        {
  ptrdiff_t const length = end_ - begin_;
  if(value.getOffsetStart() > length
    || value.getOffsetLimit() > length)
    return false;
  Token token;
  token.type_ = tokenError;
  token.start_ = begin_ + value.getOffsetStart();
  token.end_ = end_ + value.getOffsetLimit();
  ErrorInfo info;
  info.token_ = token;
  info.message_ = message;
  info.extra_ = 0;
  errors_.push_back(info);
  return true;
}
pushError() [2/2]
bool Json::Reader::pushError (const Value & value, const JSONCPP_STRING & message, const Value & extra)
Add a semantic error message with extra context.
Parameters
value JSON Value location associated with the error
message The error message.
extra Additional JSON Value location to contextualize the error
Returns
true if the error was successfully added, false if either Value offset exceeds the document size.
Definition at line 1091 of file jsoncpp.cpp.
References begin_, Json::Reader::Token::end_, end_, errors_, Json::Reader::ErrorInfo::extra_, Json::Value::getOffsetLimit(), Json::Value::getOffsetStart(), Json::Reader::ErrorInfo::message_, Json::Reader::Token::start_, Json::Reader::ErrorInfo::token_, tokenError, and Json::Reader::Token::type_.
                                                                                            {
  ptrdiff_t const length = end_ - begin_;
  if(value.getOffsetStart() > length
    || value.getOffsetLimit() > length
    || extra.getOffsetLimit() > length)
    return false;
  Token token;
  token.type_ = tokenError;
  token.start_ = begin_ + value.getOffsetStart();
  token.end_ = begin_ + value.getOffsetLimit();
  ErrorInfo info;
  info.token_ = token;
  info.message_ = message;
  info.extra_ = begin_ + extra.getOffsetStart();
  errors_.push_back(info);
  return true;
}
readArray()
bool Json::Reader::readArray (Token & token) [private]
Definition at line 735 of file jsoncpp.cpp.
References addErrorAndRecover(), Json::arrayValue, begin_, current_, currentValue(), end_, nodes_, readToken(), readValue(), recoverFromError(), Json::Value::setOffsetStart(), skipSpaces(), Json::Reader::Token::start_, Json::Value::swapPayload(), tokenArrayEnd, tokenArraySeparator, tokenComment, and Json::Reader::Token::type_.
Referenced by readValue().
                                        {
  Value init(arrayValue);
  currentValue().swapPayload(init);
  currentValue().setOffsetStart(tokenStart.start_ -
      begin_);
  skipSpaces();
  if (current_ != end_ && *current_ == ']') // empty array
  {
    Token endArray;
    readToken(endArray);
    return true;
  }
  int index = 0;
  for (;;) {
    Value& value = currentValue()[index++];
    nodes_.push(&value);
    bool ok = readValue();
    nodes_.pop();
    if (!ok) // error already set
      return recoverFromError(tokenArrayEnd);
    Token token;
    // Accept Comment after last item in the array.
    ok = readToken(token);
    while (token.type_ == tokenComment && ok) {
      ok = readToken(token);
    }
    bool badTokenType =
        (token.type_ != tokenArraySeparator && token.type_ !=
      tokenArrayEnd);
    if (!ok || badTokenType) {
      return addErrorAndRecover(
          "Missing ',' or ']' in array declaration", token, tokenArrayEnd);
    }
    if (token.type_ == tokenArrayEnd)
      break;
  }
  return true;
}
readComment()
bool Json::Reader::readComment () [private]
Definition at line 566 of file jsoncpp.cpp.
References addComment(), collectComments_, Json::commentAfterOnSameLine, Json::commentBefore, Json::containsNewLine(), current_, getNextChar(), lastValueEnd_, readCppStyleComment(), and readCStyleComment().
Referenced by readToken().
                         {
  Location commentBegin = current_ - 1;
  Char c = getNextChar();
  bool successful = false;
  if (c == '*')
    successful = readCStyleComment();
  else if (c == '/')
    successful = readCppStyleComment();
  if (!successful)
    return false;
  if (collectComments_) {
    CommentPlacement placement = commentBefore;
    if (lastValueEnd_ && !containsNewLine(
      lastValueEnd_, commentBegin)) {
      if (c != '*' || !containsNewLine(commentBegin, current_))
        placement = commentAfterOnSameLine;
    }
    addComment(commentBegin, current_, placement);
  }
  return true;
}
readCppStyleComment()
bool Json::Reader::readCppStyleComment () [private]
Definition at line 629 of file jsoncpp.cpp.
References current_, end_, and getNextChar().
Referenced by readComment().
                                 {
  while (current_ != end_) {
    Char c = getNextChar();
    if (c == '\n')
      break;
    if (c == '\r') {
      // Consume DOS EOL. It will be normalized in addComment.
      if (current_ != end_ && *current_ == '\n')
        getNextChar();
      // Break on Moc OS 9 EOL.
      break;
    }
  }
  return true;
}
readCStyleComment()
bool Json::Reader::readCStyleComment () [private]
Definition at line 620 of file jsoncpp.cpp.
References current_, end_, and getNextChar().
Referenced by readComment().
                               {
  while ((current_ + 1) < end_) {
    Char c = getNextChar();
    if (c == '*' && *current_ == '/')
      break;
  }
  return getNextChar() == '/';
}
readNumber()
void Json::Reader::readNumber () [private]
Definition at line 645 of file jsoncpp.cpp.
References current_, and end_.
Referenced by readToken().
                        {
  const char *p = current_;
  char c = '0'; // stopgap for already consumed character
  // integral part
  while (c >= '0' && c <= '9')
    c = (current_ = p) < end_ ? *p++ : '\0';
  // fractional part
  if (c == '.') {
    c = (current_ = p) < end_ ? *p++ : '\0';
    while (c >= '0' && c <= '9')
      c = (current_ = p) < end_ ? *p++ : '\0';
  }
  // exponential part
  if (c == 'e' || c == 'E') {
    c = (current_ = p) < end_ ? *p++ : '\0';
    if (c == '+' || c == '-')
      c = (current_ = p) < end_ ? *p++ : '\0';
    while (c >= '0' && c <= '9')
      c = (current_ = p) < end_ ? *p++ : '\0';
  }
}
readObject()
bool Json::Reader::readObject (Token & token) [private]
Definition at line 679 of file jsoncpp.cpp.
References addErrorAndRecover(), Json::Features::allowNumericKeys_, Json::Value::asCString(), begin_, currentValue(), decodeNumber(), decodeString(), features_, JSONCPP_STRING, nodes_, Json::objectValue, readToken(), readValue(), recoverFromError(), Json::Value::setOffsetStart(), Json::Reader::Token::start_, Json::Value::swapPayload(), tokenArraySeparator, tokenComment, tokenMemberSeparator, tokenNumber, tokenObjectEnd, tokenString, and Json::Reader::Token::type_.
Referenced by readValue().
                                         {
  Token tokenName;
  JSONCPP_STRING name;
  Value init(objectValue);
  currentValue().swapPayload(init);
  currentValue().setOffsetStart(tokenStart.start_ -
      begin_);
  while (readToken(tokenName)) {
    bool initialTokenOk = true;
    while (tokenName.type_ == tokenComment && initialTokenOk)
      initialTokenOk = readToken(tokenName);
    if (!initialTokenOk)
      break;
    if (tokenName.type_ == tokenObjectEnd && name.empty()) // empty object
      return true;
    name = "";
    if (tokenName.type_ == tokenString) {
      if (!decodeString(tokenName, name))
        return recoverFromError(tokenObjectEnd);
    } else if (tokenName.type_ == tokenNumber && features_.
      allowNumericKeys_) {
      Value numberName;
      if (!decodeNumber(tokenName, numberName))
        return recoverFromError(tokenObjectEnd);
      name = JSONCPP_STRING(numberName.asCString());
    } else {
      break;
    }
    Token colon;
    if (!readToken(colon) || colon.type_ != tokenMemberSeparator) {
      return addErrorAndRecover(
          "Missing ':' after object member name", colon, tokenObjectEnd);
    }
    Value& value = currentValue()[name];
    nodes_.push(&value);
    bool ok = readValue();
    nodes_.pop();
    if (!ok) // error already set
      return recoverFromError(tokenObjectEnd);
    Token comma;
    if (!readToken(comma) ||
        (comma.type_ != tokenObjectEnd && comma.type_ !=
      tokenArraySeparator &&
         comma.type_ != tokenComment)) {
      return addErrorAndRecover(
          "Missing ',' or '}' in object declaration", comma, tokenObjectEnd);
    }
    bool finalizeTokenOk = true;
    while (comma.type_ == tokenComment && finalizeTokenOk)
      finalizeTokenOk = readToken(comma);
    if (comma.type_ == tokenObjectEnd)
      return true;
  }
  return addErrorAndRecover(
      "Missing '}' or object member name", tokenName, tokenObjectEnd);
}
readString()
bool Json::Reader::readString () [private]
Definition at line 667 of file jsoncpp.cpp.
References current_, end_, and getNextChar().
Referenced by readToken().
                        {
  Char c = '\0';
  while (current_ != end_) {
    c = getNextChar();
    if (c == '\\')
      getNextChar();
    else if (c == '"')
      break;
  }
  return c == '"';
}
readToken()
bool Json::Reader::readToken (Token & token) [private]
Definition at line 474 of file jsoncpp.cpp.
References current_, Json::Reader::Token::end_, getNextChar(), match(), readComment(), readNumber(), readString(), skipSpaces(), Json::Reader::Token::start_, tokenArrayBegin, tokenArrayEnd, tokenArraySeparator, tokenComment, tokenEndOfStream, tokenError, tokenFalse, tokenMemberSeparator, tokenNull, tokenNumber, tokenObjectBegin, tokenObjectEnd, tokenString, tokenTrue, and Json::Reader::Token::type_.
Referenced by readArray(), readObject(), recoverFromError(), and skipCommentTokens().
                                   {
  skipSpaces();
  token.start_ = current_;
  Char c = getNextChar();
  bool ok = true;
  switch (c) {
  case '{':
    token.type_ = tokenObjectBegin;
    break;
  case '}':
    token.type_ = tokenObjectEnd;
    break;
  case '[':
    token.type_ = tokenArrayBegin;
    break;
  case ']':
    token.type_ = tokenArrayEnd;
    break;
  case '"':
    token.type_ = tokenString;
    ok = readString();
    break;
  case '/':
    token.type_ = tokenComment;
    ok = readComment();
    break;
  case '0':
  case '1':
  case '2':
  case '3':
  case '4':
  case '5':
  case '6':
  case '7':
  case '8':
  case '9':
  case '-':
    token.type_ = tokenNumber;
    readNumber();
    break;
  case 't':
    token.type_ = tokenTrue;
    ok = match("rue", 3);
    break;
  case 'f':
    token.type_ = tokenFalse;
    ok = match("alse", 4);
    break;
  case 'n':
    token.type_ = tokenNull;
    ok = match("ull", 3);
    break;
  case ',':
    token.type_ = tokenArraySeparator;
    break;
  case ':':
    token.type_ = tokenMemberSeparator;
    break;
  case 0:
    token.type_ = tokenEndOfStream;
    break;
  default:
    ok = false;
    break;
  }
  if (!ok)
    token.type_ = tokenError;
  token.end_ = current_;
  return true;
}
readValue()
bool Json::Reader::readValue () [private]
Definition at line 383 of file jsoncpp.cpp.
References addError(), Json::Features::allowDroppedNullPlaceholders_, begin_, collectComments_, Json::commentBefore, commentsBefore_, current_, currentValue(), decodeNumber(), decodeString(), Json::Reader::Token::end_, features_, lastValue_, lastValueEnd_, nodes_, readArray(), readObject(), Json::Value::setComment(), Json::Value::setOffsetLimit(), Json::Value::setOffsetStart(), skipCommentTokens(), stackLimit_g, Json::Reader::Token::start_, Json::Value::swapPayload(), Json::throwRuntimeError(), tokenArrayBegin, tokenArrayEnd, tokenArraySeparator, tokenFalse, tokenNull, tokenNumber, tokenObjectBegin, tokenObjectEnd, tokenString, tokenTrue, and Json::Reader::Token::type_.
Referenced by parse(), readArray(), and readObject().
                       {
  // readValue() may call itself only if it calls readObject() or ReadArray().
  // These methods execute nodes_.push() just before and nodes_.pop)() just after calling readValue().
  // parse() executes one nodes_.push(), so > instead of >=.
  if (nodes_.size() > stackLimit_g) throwRuntimeError("Exceeded
       stackLimit in readValue().");
  Token token;
  skipCommentTokens(token);
  bool successful = true;
  if (collectComments_ && !commentsBefore_.empty()) {
    currentValue().setComment(commentsBefore_,
      commentBefore);
    commentsBefore_ = "";
  }
  switch (token.type_) {
  case tokenObjectBegin:
    successful = readObject(token);
    currentValue().setOffsetLimit(current_ -
      begin_);
    break;
  case tokenArrayBegin:
    successful = readArray(token);
    currentValue().setOffsetLimit(current_ -
      begin_);
    break;
  case tokenNumber:
    successful = decodeNumber(token);
    break;
  case tokenString:
    successful = decodeString(token);
    break;
  case tokenTrue:
    {
    Value v(true);
    currentValue().swapPayload(v);
    currentValue().setOffsetStart(token.start_ -
      begin_);
    currentValue().setOffsetLimit(token.end_ - begin_);
    }
    break;
  case tokenFalse:
    {
    Value v(false);
    currentValue().swapPayload(v);
    currentValue().setOffsetStart(token.start_ -
      begin_);
    currentValue().setOffsetLimit(token.end_ - begin_);
    }
    break;
  case tokenNull:
    {
    Value v;
    currentValue().swapPayload(v);
    currentValue().setOffsetStart(token.start_ -
      begin_);
    currentValue().setOffsetLimit(token.end_ - begin_);
    }
    break;
  case tokenArraySeparator:
  case tokenObjectEnd:
  case tokenArrayEnd:
    if (features_.allowDroppedNullPlaceholders_) {
      // "Un-read" the current token and mark the current value as a null
      // token.
      current_--;
      Value v;
      currentValue().swapPayload(v);
      currentValue().setOffsetStart(current_ -
      begin_ - 1);
      currentValue().setOffsetLimit(current_ -
      begin_);
      break;
    } // Else, fall through...
  default:
    currentValue().setOffsetStart(token.start_ -
      begin_);
    currentValue().setOffsetLimit(token.end_ - begin_);
    return addError("Syntax error: value, object or array expected.", token);
  }
  if (collectComments_) {
    lastValueEnd_ = current_;
    lastValue_ = &currentValue();
  }
  return successful;
}
recoverFromError()
bool Json::Reader::recoverFromError (TokenType skipUntilToken) [private]
Definition at line 979 of file jsoncpp.cpp.
References errors_, readToken(), tokenEndOfStream, and Json::Reader::Token::type_.
Referenced by addErrorAndRecover(), readArray(), and readObject().
                                                      {
  size_t const errorCount = errors_.size();
  Token skip;
  for (;;) {
    if (!readToken(skip))
      errors_.resize(errorCount); // discard errors caused by recovery
    if (skip.type_ == skipUntilToken || skip.type_ == tokenEndOfStream)
      break;
  }
  errors_.resize(errorCount);
  return false;
}
skipCommentTokens()
void Json::Reader::skipCommentTokens (Token & token) [private]
Definition at line 464 of file jsoncpp.cpp.
References Json::Features::allowComments_, features_, readToken(), tokenComment, and Json::Reader::Token::type_.
Referenced by parse(), and readValue().
                                           {
  if (features_.allowComments_) {
    do {
      readToken(token);
    } while (token.type_ == tokenComment);
  } else {
    readToken(token);
  }
}
skipSpaces()
void Json::Reader::skipSpaces () [private]
Definition at line 545 of file jsoncpp.cpp.
References current_, and end_.
Referenced by readArray(), and readToken().
                        {
  while (current_ != end_) {
    Char c = *current_;
    if (c == ' ' || c == '\t' || c == '\r' || c == '\n')
      ++current_;
    else
      break;
  }
}
skipUntilSpace()
void Json::Reader::skipUntilSpace () [private]
Member Data Documentation
begin_
Location Json::Reader::begin_ [private]
Definition at line 1563 of file json.h.
Referenced by decodeDouble(), decodeNumber(), decodeString(), getLocationLineAndColumn(), getStructuredErrors(), parse(), pushError(), readArray(), readObject(), and readValue().
collectComments_
bool Json::Reader::collectComments_ [private]
Definition at line 1570 of file json.h.
Referenced by addComment(), parse(), readComment(), and readValue().
commentsBefore_
JSONCPP_STRING Json::Reader::commentsBefore_ [private]
Definition at line 1568 of file json.h.
Referenced by addComment(), parse(), and readValue().
current_
Location Json::Reader::current_ [private]
Definition at line 1565 of file json.h.
Referenced by getNextChar(), match(), parse(), readArray(), readComment(), readCppStyleComment(), readCStyleComment(), readNumber(), readString(), readToken(), readValue(), and skipSpaces().
document_
JSONCPP_STRING Json::Reader::document_ [private]
Definition at line 1562 of file json.h.
Referenced by parse().
end_
Location Json::Reader::end_ [private]
Definition at line 1564 of file json.h.
Referenced by getLocationLineAndColumn(), getNextChar(), match(), parse(), pushError(), readArray(), readCppStyleComment(), readCStyleComment(), readNumber(), readString(), and skipSpaces().
errors_
Errors Json::Reader::errors_ [private]
Definition at line 1561 of file json.h.
Referenced by addError(), getFormattedErrorMessages(), getStructuredErrors(), good(), parse(), pushError(), and recoverFromError().
features_
Features Json::Reader::features_ [private]
Definition at line 1569 of file json.h.
Referenced by parse(), readObject(), readValue(), and skipCommentTokens().
lastValue_
Value* Json::Reader::lastValue_ [private]
Definition at line 1567 of file json.h.
Referenced by addComment(), parse(), and readValue().
lastValueEnd_
Location Json::Reader::lastValueEnd_ [private]
Definition at line 1566 of file json.h.
Referenced by parse(), readComment(), and readValue().
nodes_
Nodes Json::Reader::nodes_ [private]
Definition at line 1560 of file json.h.
Referenced by currentValue(), parse(), readArray(), readObject(), and readValue().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/json.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/jsoncpp.cpp