Json::ValueConstIterator Class Reference
const iterator for object and array value.
#include <json.h>
Public Types
typedef const Value value_type
typedef const Value & reference
typedef const Value * pointer
typedef ValueConstIterator SelfType
Public Member Functions
ValueConstIterator ()
ValueConstIterator (ValueIterator const &other)
SelfType & operator= (const ValueIteratorBase &other)
SelfType operator++ (int)
SelfType operator-- (int)
SelfType & operator-- ()
SelfType & operator++ ()
reference operator* () const
pointer operator-> () const
Private Member Functions
ValueConstIterator (const Value::ObjectValues::iterator &current)
Friends
class Value
Additional Inherited Members
Detailed Description
const iterator for object and array value.
Definition at line 1198 of file json.h.
Member Typedef Documentation
pointer
typedef const Value* Json::ValueConstIterator::pointer
Definition at line 1206 of file json.h.
reference
typedef const Value& Json::ValueConstIterator::reference
Definition at line 1205 of file json.h.
SelfType
typedef ValueConstIterator Json::ValueConstIterator::SelfType
Definition at line 1207 of file json.h.
value_type
typedef const Value Json::ValueConstIterator::value_type
Definition at line 1202 of file json.h.
Constructor & Destructor Documentation
ValueConstIterator() [1/3]
Json::ValueConstIterator::ValueConstIterator ()
Definition at line 2392 of file jsoncpp.cpp.
{}
ValueConstIterator() [2/3]
Json::ValueConstIterator::ValueConstIterator (ValueIterator const & other)
Definition at line 2398 of file jsoncpp.cpp.
References operator=().
    : ValueIteratorBase(other) {}
ValueConstIterator() [3/3]
Json::ValueConstIterator::ValueConstIterator (const Value::ObjectValues::iterator & current) [explicit], [private]
Definition at line 2394 of file jsoncpp.cpp.
    : ValueIteratorBase(current) {}
Member Function Documentation
operator*()
reference Json::ValueConstIterator::operator* () const [inline]
Definition at line 1241 of file json.h.
{ return deref(); }
operator++() [1/2]
SelfType Json::ValueConstIterator::operator++ (int) [inline]
Definition at line 1219 of file json.h.
                           {
    SelfType temp(*this);
    ++*this;
    return temp;
  }
operator++() [2/2]
SelfType& Json::ValueConstIterator::operator++ () [inline]
Definition at line 1236 of file json.h.
                         {
    increment();
    return *this;
  }
operator--() [1/2]
SelfType Json::ValueConstIterator::operator-- (int) [inline]
Definition at line 1225 of file json.h.
                           {
    SelfType temp(*this);
    --*this;
    return temp;
  }
operator--() [2/2]
SelfType& Json::ValueConstIterator::operator-- () [inline]
Definition at line 1231 of file json.h.
                         {
    decrement();
    return *this;
  }
operator->()
pointer Json::ValueConstIterator::operator-> () const [inline]
Definition at line 1243 of file json.h.
{ return &deref(); }
operator=()
ValueConstIterator & Json::ValueConstIterator::operator= (const ValueIteratorBase & other)
Definition at line 2402 of file jsoncpp.cpp.
References Json::ValueIteratorBase::copy().
Referenced by ValueConstIterator().
                                          {
  copy(other);
  return *this;
}
Friends And Related Function Documentation
Value
friend class Value [friend]
Definition at line 1199 of file json.h.
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/json.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/jsoncpp.cpp