TextBox Class Reference
#include <TextBox.h>
Public Member Functions
TextBox ()
TextBox (std::string fileName, SDL_Renderer *renderer, int x, int y)
void renderComment (SDL_Renderer *renderer)
bool loadText (SDL_Renderer *renderer, std::string text, TTF_Font *font)
void createStrings (std::string text, TTF_Font *font)
Texture getFontTexture ()
int getLinesToRender ()
void freeComment ()
std::string returnLine (int i)
void emptyTextToRender ()
Private Attributes
int fontWidth
int fontHeight
std::vector< std::string > textToRender
Texture fontTexture
Detailed Description
Inherit's from the base sprite class, handles text rendering to the screen, and freeing up that text
Definition at line 11 of file TextBox.h.
Constructor & Destructor Documentation
TextBox() [1/2]
TextBox::TextBox ()
Definition at line 3 of file TextBox.cpp.
{}
TextBox() [2/2]
TextBox::TextBox (std::string fileName, SDL_Renderer * renderer, int x, int y)
Definition at line 5 of file TextBox.cpp.
: Sprite(fileName, renderer, x, y){}
Member Function Documentation
createStrings()
void TextBox::createStrings (std::string text, TTF_Font * font)
Breaks up text into 3 line chunks to be rendered
Bug
Bug There is currently an issue where the texture will return 0, temp fix has been implemented where the texture width is hardcoded
Definition at line 50 of file TextBox.cpp.
References Sprite::getWidth(), and textToRender.
Referenced by NPC::prepareComment().
{
    if (font == NULL)
    {
        printf("Failed to load font! SDL_ttf Error: %s\n", TTF_GetError());
    }
    else
    {
        try
        {
            // Find the dimensions of a single character rendered in the parsed in font
            int tW, tH;
            TTF_SizeText(font, "a", &tW, &tH);
            // retrieve the width of our texture
            int supposedWidth = getWidth();
            
            int maxCharsPerLine = 180 / tW;
            if (maxCharsPerLine == 0)
                throw std::overflow_error("texture Width is 0!");
            
            // Divide the length of text by the max number of chars that can be had per line
            int numSubStrings = text.length() / maxCharsPerLine;
            std::vector<std::string> ret;
            std::stringstream threeChunks;
            int counter = 0;
            for (int i = 0; i < numSubStrings; i++)
            {
                // Create a substring using the maxCharPerLine value
                std::string textChunk = text.substr(i * maxCharsPerLine, maxCharsPerLine);
                // feed the chunk into our string stream
                threeChunks << textChunk;
                counter++;
                // if we have 3 lines stored, push back the chunk
                if (counter == 3 || counter == numSubStrings)
                {
                    counter = 0;
                    textToRender.push_back(threeChunks.str());
                    threeChunks.str("");
                }
            }
            // add the remainder text as a chunk
            if (text.length() % maxCharsPerLine != 0)
            {
                threeChunks << text.substr(maxCharsPerLine * numSubStrings);
                textToRender.push_back(threeChunks.str());
                threeChunks.str("");
            }
        }
        catch (std::overflow_error e)
        {
            std::cout << e.what() << std::endl;;
        }
    }
}
emptyTextToRender()
void TextBox::emptyTextToRender ()
Definition at line 131 of file TextBox.cpp.
References textToRender.
Referenced by NPC::prepareComment().
{
    textToRender.clear();
}
freeComment()
void TextBox::freeComment ()
Definition at line 113 of file TextBox.cpp.
References fontTexture, and Texture::free().
Referenced by NPC::freeBox().
{
    fontTexture.free();
}
getFontTexture()
Texture TextBox::getFontTexture ()
Definition at line 12 of file TextBox.cpp.
References fontTexture.
{
    return fontTexture;
}
getLinesToRender()
int TextBox::getLinesToRender ()
Definition at line 118 of file TextBox.cpp.
References textToRender.
Referenced by NPC::getLinesToRender().
{
    return textToRender.size();
}
loadText()
bool TextBox::loadText (SDL_Renderer * renderer, std::string text, TTF_Font * font)
Load parsed in text as a texture
Definition at line 20 of file TextBox.cpp.
References fontHeight, fontTexture, fontWidth, Texture::getHeight(), Sprite::getWidth(), Texture::getWidth(), and Texture::loadFromRenderedText().
Referenced by NPC::LoadComment().
{
    //Loading success flag
    bool success = true;
    //Open the font
    if (font == NULL)
    {
        printf("Failed to load font! SDL_ttf Error: %s\n", TTF_GetError());
        success = false;
    }
    else
    {
        //Render text
        SDL_Color textColor = { 0, 0, 0 };
        if (!fontTexture.loadFromRenderedText(text, textColor, renderer,
      font, getWidth()))
        {
            printf("Failed to render text texture!\n");
            success = false;
        }
        fontWidth = fontTexture.getWidth();
        fontHeight = fontTexture.getHeight();
    }
    return success;
}
renderComment()
void TextBox::renderComment (SDL_Renderer * renderer)
Definition at line 7 of file TextBox.cpp.
References fontTexture, Sprite::getX(), Sprite::getY(), and Texture::render().
Referenced by NPC::renderComment().
{
    fontTexture.render(getX(), getY(), renderer);
}
returnLine()
std::string TextBox::returnLine (int i)
Definition at line 123 of file TextBox.cpp.
References textToRender.
Referenced by NPC::LoadComment().
{
    if (textToRender.size() > 0)
        return textToRender[i];
    else
        return "";
}
Member Data Documentation
fontHeight
int TextBox::fontHeight [private]
Definition at line 30 of file TextBox.h.
Referenced by loadText().
fontTexture
Texture TextBox::fontTexture [private]
Definition at line 33 of file TextBox.h.
Referenced by freeComment(), getFontTexture(), loadText(), and renderComment().
fontWidth
int TextBox::fontWidth [private]
Definition at line 30 of file TextBox.h.
Referenced by loadText().
textToRender
std::vector<std::string> TextBox::textToRender [private]
Definition at line 32 of file TextBox.h.
Referenced by createStrings(), emptyTextToRender(), getLinesToRender(), and returnLine().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/TextBox.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/TextBox.cpp