JSONReader Class Reference
#include <JSONReader.h>
Public Member Functions
JSONReader (std::string fName)
std::string getFileName ()
void setFileName (std::string fName)
std::ifstream ReadJsonFile ()
reads a JSON file into the program
Private Attributes
std::string fileName
Detailed Description
Reads in a JSON file
Definition at line 9 of file JSONReader.h.
Constructor & Destructor Documentation
JSONReader()
JSONReader::JSONReader (std::string fName)
Definition at line 3 of file JSONReader.cpp.
References setFileName().
{
    setFileName(fName);
}
Member Function Documentation
getFileName()
std::string JSONReader::getFileName ()
Definition at line 8 of file JSONReader.cpp.
References fileName.
{
    return fileName;
}
ReadJsonFile()
std::ifstream JSONReader::ReadJsonFile ()
reads a JSON file into the program
Definition at line 18 of file JSONReader.cpp.
References fileName.
Referenced by main().
{
    return std::ifstream(fileName, std::ifstream::binary);
}
setFileName()
void JSONReader::setFileName (std::string fName)
Definition at line 13 of file JSONReader.cpp.
References fileName.
Referenced by JSONReader().
{
    fileName = fName;
}
Member Data Documentation
fileName
std::string JSONReader::fileName [private]
Definition at line 21 of file JSONReader.h.
Referenced by getFileName(), ReadJsonFile(), and setFileName().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/JSONReader.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/JSONReader.cpp