PythonHandler Class Reference
#include <PythonHandler.h>
Public Member Functions
PythonHandler (std::string module, std::string function)
std::string getModuleName ()
void setModuleName (std::string module)
std::string getFunctionName ()
void setFunctionName (std::string function)
void callPythonModule ()
Call the python script to gather comments.
Private Attributes
std::string moduleName
std::string functionName
Detailed Description
Wrapper to handle the C/Python api functionality, in charge of calling the external python scripts
Definition at line 7 of file PythonHandler.h.
Constructor & Destructor Documentation
PythonHandler()
PythonHandler::PythonHandler (std::string module, std::string function)
Definition at line 3 of file PythonHandler.cpp.
References setFunctionName(), and setModuleName().
{
    setModuleName(module);
    setFunctionName(function);
}
Member Function Documentation
callPythonModule()
void PythonHandler::callPythonModule ()
Call the python script to gather comments.
Definition at line 29 of file PythonHandler.cpp.
References functionName, and moduleName.
Referenced by main().
{
    try
    {
        //Begin python
        Py_Initialize();
        //Call the python module
        PyObject* module = PyImport_ImportModule(moduleName.c_str());
        if (module == 0)
        {
            PyErr_Print();
            printf("Couldn't find python module");
        }
        //Create a dictionary of the function's inside the module
        PyObject* comDict = PyModule_GetDict(module);
        //State the specified function name from the dictionary
        PyObject* func = PyDict_GetItemString(comDict, functionName.c_str());
        //State the argument's you want NOTE: currently only work's with functions with 0 arguments
        PyObject* args = PyTuple_New(0);
        //Call the object
        PyObject* result = PyObject_CallObject(func, args);
        if (result == NULL)
        {
            printf("Calling function failed");
        }
        //Print any errors
        PyErr_Print();
        //Clean up the pointer's
        Py_DECREF(module);
        Py_DECREF(comDict);
        Py_DECREF(func);
        Py_DECREF(args);
        Py_DECREF(result);
        //End the python process
        Py_Finalize();
    }
    catch (...) {
        PyObject *ptype, *pvalue, *ptraceback;
        PyErr_Fetch(&ptype, &pvalue, &ptraceback);
        char* pStrErrorMessage = _PyUnicode_AsString(pvalue);
        Py_DECREF(ptype);
        Py_DECREF(pvalue);
        Py_DECREF(ptraceback);
    }
}
getFunctionName()
std::string PythonHandler::getFunctionName ()
Definition at line 19 of file PythonHandler.cpp.
References functionName.
{
    return functionName;
}
getModuleName()
std::string PythonHandler::getModuleName ()
Definition at line 9 of file PythonHandler.cpp.
References moduleName.
{
    return moduleName;
}
setFunctionName()
void PythonHandler::setFunctionName (std::string function)
Definition at line 24 of file PythonHandler.cpp.
References functionName.
Referenced by PythonHandler().
{
    functionName = funcName;
}
setModuleName()
void PythonHandler::setModuleName (std::string module)
Definition at line 14 of file PythonHandler.cpp.
References moduleName.
Referenced by PythonHandler().
{
    moduleName = modName;
}
Member Data Documentation
functionName
std::string PythonHandler::functionName [private]
Definition at line 22 of file PythonHandler.h.
Referenced by callPythonModule(), getFunctionName(), and setFunctionName().
moduleName
std::string PythonHandler::moduleName [private]
Definition at line 21 of file PythonHandler.h.
Referenced by callPythonModule(), getModuleName(), and setModuleName().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/PythonHandler.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/PythonHandler.cpp