NPC Class Reference
#include <NPC.h>
Public Member Functions
NPC (std::string tBoxSprite, std::string NPCSprite, std::string text, SDL_Renderer *renderer, int x, int y)
void prepareComment (std::string txt, TTF_Font *font)
Breaks up parsed in text into a chunked comment.
void LoadComment (SDL_Renderer *renderer, int i, TTF_Font *font)
Loads the NPCs comment into the textbox.
void renderComment (SDL_Renderer *renderer)
Renders the NPCs comment.
void LoadBox (SDL_Renderer *renderer)
Loads the NPCs TextBox.
void renderBox (SDL_Renderer *renderer)
Renders the NPCs TextBox.
void freeBox ()
Frees up the memory space the textbox is occupying.
int getLinesToRender ()
returns the number of line being rendered to the screen
void applyEmotionLevel (float polarity)
void evaluateEmotionLevel ()
Evaluates the emotional level of the NPC.
void move ()
Handles the NPCs movement.
void setID (int i)
int getID ()
int getGroupID ()
void setGroupID (int id)
int getCurrentLine ()
void setCurrentLine (int id)
bool getSpeaking ()
void setSpeaking (bool val)
float getEmotionLevel ()
bool getIdle ()
void setIdle (bool nIdle)
bool getMoving ()
void setMoving (bool move)
bool getReading ()
void setReading (bool read)
int getBoredom ()
void setBoredom (int lvl)
std::string getCurrentUser ()
void setCurrentUser (std::string user)
std::vector< std::shared_ptr< Node > > getPath ()
void setPath (std::vector< std::shared_ptr< Node >> newPath)
std::string getText ()
void setText (std::string t)
std::pair< int, int > getEndGoal ()
void setEndGoal (std::pair< int, int > newGoal)
Private Attributes
int id
int groupID
int currentLine
int boredLvl
std::string currentUser = ``
std::string text
TextBox speech
std::vector< std::shared_ptr< Node > > path
std::pair< int, int > endGoal
bool speaking = false
bool reading = false
bool idle = false
bool moving = false
float emotionLevels = 0.0f
Friends
bool operator== (const NPC &c1, const NPC &c2)
Detailed Description
NPC class inherits from sprite class, uses the textbox class in conjunction with it's base rendering methods for the NPC sprite. holds all the actions a NPC can perform within the application.
Definition at line 9 of file NPC.h.
Constructor & Destructor Documentation
NPC()
NPC::NPC (std::string tBoxSprite, std::string NPCSprite, std::string text, SDL_Renderer * renderer, int x, int y)
Definition at line 3 of file NPC.cpp.
References boredLvl, and speech.
                                                                                                        :
      Sprite(NPCSprite, renderer, x, y)
{
    boredLvl = 0;
    speech = TextBox(tBoxSprite, renderer, x, y);
}
Member Function Documentation
applyEmotionLevel()
void NPC::applyEmotionLevel (float polarity)
Definition at line 200 of file NPC.cpp.
References emotionLevels.
{
    emotionLevels += val;
}
evaluateEmotionLevel()
void NPC::evaluateEmotionLevel ()
Evaluates the emotional level of the NPC.
Evaluates the NPCs emotion level and converts it into RGB values
Definition at line 157 of file NPC.cpp.
References getEmotionLevel(), and Sprite::setColor().
{
    int emo = getEmotionLevel();
    // if the emotion level is less than 0 it is negative
    if (emo < 0)
    {
        emo = abs(emo) * 10;
        // ensure that the highest possible value is 255
        if (emo > 255)
            emo = 255;
        // set the NPCs color to be more red to show negativity
        setColor(255, 255-emo, 255-emo);
    }
    else if(emo > 0)
    {
        emo = emo * 10;
        if (emo > 255)
            emo = 255;
        // set the NPCs color to be more green to show positivity
        setColor(255-emo, 255, 255-emo);
    }
}
freeBox()
void NPC::freeBox ()
Frees up the memory space the textbox is occupying.
Frees the space that both the comment and its textbox occupy in memory
Definition at line 128 of file NPC.cpp.
References Sprite::free(), TextBox::freeComment(), and speech.
{
    speech.free();
    speech.freeComment();
}
getBoredom()
int NPC::getBoredom ()
Definition at line 47 of file NPC.cpp.
References boredLvl.
{
    return boredLvl;
}
getCurrentLine()
int NPC::getCurrentLine ()
Definition at line 185 of file NPC.cpp.
References currentLine.
{
    return currentLine;
}
getCurrentUser()
std::string NPC::getCurrentUser ()
Definition at line 52 of file NPC.cpp.
References currentUser.
{
    return currentUser;
}
getEmotionLevel()
float NPC::getEmotionLevel ()
Definition at line 149 of file NPC.cpp.
References emotionLevels.
Referenced by evaluateEmotionLevel().
{
    return emotionLevels;
}
getEndGoal()
std::pair< int, int > NPC::getEndGoal ()
Definition at line 225 of file NPC.cpp.
References endGoal.
{
    return endGoal;
}
getGroupID()
int NPC::getGroupID ()
Definition at line 42 of file NPC.cpp.
References groupID.
{
    return groupID;
}
getID()
int NPC::getID ()
Definition at line 32 of file NPC.cpp.
References id.
{
    return id;
}
getIdle()
bool NPC::getIdle ()
Definition at line 215 of file NPC.cpp.
References idle.
{
    return idle;
}
getLinesToRender()
int NPC::getLinesToRender ()
returns the number of line being rendered to the screen
Definition at line 139 of file NPC.cpp.
References TextBox::getLinesToRender(), and speech.
{
    return speech.getLinesToRender();
}
getMoving()
bool NPC::getMoving ()
Definition at line 254 of file NPC.cpp.
References moving.
{
    return moving;
}
getPath()
std::vector< std::shared_ptr< Node > > NPC::getPath ()
Definition at line 235 of file NPC.cpp.
References path.
{
    return path;
}
getReading()
bool NPC::getReading ()
Definition at line 244 of file NPC.cpp.
References reading.
{
    return reading;
}
getSpeaking()
bool NPC::getSpeaking ()
Definition at line 144 of file NPC.cpp.
References speaking.
{
    return speaking;
}
getText()
std::string NPC::getText ()
Definition at line 210 of file NPC.cpp.
References text.
{
    return text;
}
LoadBox()
void NPC::LoadBox (SDL_Renderer * renderer)
Loads the NPCs TextBox.
Load the Textbox into memory
Definition at line 109 of file NPC.cpp.
References Sprite::getX(), Sprite::getY(), Sprite::loadMedia(), Sprite::setX(), Sprite::setY(), and speech.
{
    speech.setX(getX() - 40);
    speech.setY(getY() - 120);
    speech.loadMedia(renderer);
}
LoadComment()
void NPC::LoadComment (SDL_Renderer * renderer, int i, TTF_Font * font)
Loads the NPCs comment into the textbox.
Load in a comment as a texture
Definition at line 21 of file NPC.cpp.
References TextBox::loadText(), TextBox::returnLine(), and speech.
{
    std::string txt = speech.returnLine(i);
    speech.loadText(renderer, txt, font);
}
move()
void NPC::move ()
Handles the NPCs movement.
The NPCs movement method
Definition at line 65 of file NPC.cpp.
References Sprite::getX(), Sprite::getY(), path, Sprite::setX(), and Sprite::setY().
Referenced by setMoving().
{
    // if there is a path that the NPC can follow
    if (path.size() > 0)
    {
        // Deduct the NPCs X & Y from the path nodes X & Y
        float movementX = path[0]->getX() - getX();
        float movementY = path[0]->getY() - getY();
        // Find the length between the NPC and the node
        float toWayPointLength = sqrt(movementX*movementX + movementY*movementY);
        
        // If the node has not been reached, then divide the movement values by the length
        if (toWayPointLength > 0)
        {
            movementX = movementX / toWayPointLength;
            movementY = movementY / toWayPointLength;
        }
        float nX = getX();
        float nY = getY();
        // apply the movements value multiplied by a speed of 2
        setX(nX += movementX * 2);
        setY(nY += movementY * 2);
        // If the NPC is close to the node, set him to occupy that node space
        if (path[0]->getX() - getX() < 3 && path[0]->getY() -
      getY() < 3 && path[0]->getX() - getX() > -3 && path[0]->getY() -
      getY() > -3)
        {
            setX(path[0]->getX());
            setY(path[0]->getY());
            path.erase(path.begin());
        }
    }
}
prepareComment()
void NPC::prepareComment (std::string txt, TTF_Font * font)
Breaks up parsed in text into a chunked comment.
Break up the parsed in text into chunks to be scrolled
Definition at line 12 of file NPC.cpp.
References TextBox::createStrings(), TextBox::emptyTextToRender(), and speech.
{
    speech.emptyTextToRender();
    speech.createStrings(txt, font);
}
renderBox()
void NPC::renderBox (SDL_Renderer * renderer)
Renders the NPCs TextBox.
Render the textbox to the screen
Definition at line 120 of file NPC.cpp.
References Sprite::render(), and speech.
{
    speech.render(renderer);
}
renderComment()
void NPC::renderComment (SDL_Renderer * renderer)
Renders the NPCs comment.
Definition at line 134 of file NPC.cpp.
References TextBox::renderComment(), and speech.
{
    speech.renderComment(renderer);
}
setBoredom()
void NPC::setBoredom (int lvl)
Definition at line 101 of file NPC.cpp.
References boredLvl.
{
    boredLvl = lvl;
}
setCurrentLine()
void NPC::setCurrentLine (int id)
Definition at line 190 of file NPC.cpp.
References currentLine.
{
    currentLine = line;
}
setCurrentUser()
void NPC::setCurrentUser (std::string user)
Definition at line 57 of file NPC.cpp.
References currentUser.
{
    currentUser = user;
}
setEndGoal()
void NPC::setEndGoal (std::pair< int, int > newGoal)
Definition at line 230 of file NPC.cpp.
References endGoal.
{
    endGoal = newGoal;
}
setGroupID()
void NPC::setGroupID (int id)
Definition at line 37 of file NPC.cpp.
References groupID, and id.
{
    groupID = id;
}
setID()
void NPC::setID (int i)
Definition at line 27 of file NPC.cpp.
{
    id = i;
}
setIdle()
void NPC::setIdle (bool nIdle)
Definition at line 220 of file NPC.cpp.
References idle.
{
    idle = nIdle;
}
setMoving()
void NPC::setMoving (bool move)
Definition at line 258 of file NPC.cpp.
References move(), and moving.
{
    moving = move;
}
setPath()
void NPC::setPath (std::vector< std::shared_ptr< Node >> newPath)
Definition at line 240 of file NPC.cpp.
References path.
{
    path = newPath;
}
setReading()
void NPC::setReading (bool read)
Definition at line 249 of file NPC.cpp.
References reading.
{
    reading = read;
}
setSpeaking()
void NPC::setSpeaking (bool val)
Definition at line 195 of file NPC.cpp.
References speaking.
{
    speaking = val;
}
setText()
void NPC::setText (std::string t)
Definition at line 205 of file NPC.cpp.
References text.
{
    text = str;
}
Friends And Related Function Documentation
operator==
bool operator== (const NPC & c1, const NPC & c2) [friend]
Definition at line 263 of file NPC.cpp.
{
    return (c1.id == c2.id);
}
Member Data Documentation
boredLvl
int NPC::boredLvl [private]
Definition at line 86 of file NPC.h.
Referenced by getBoredom(), NPC(), and setBoredom().
currentLine
int NPC::currentLine [private]
Definition at line 85 of file NPC.h.
Referenced by getCurrentLine(), and setCurrentLine().
currentUser
std::string NPC::currentUser = `` [private]
Definition at line 88 of file NPC.h.
Referenced by getCurrentUser(), and setCurrentUser().
emotionLevels
float NPC::emotionLevels = 0.0f [private]
Definition at line 100 of file NPC.h.
Referenced by applyEmotionLevel(), and getEmotionLevel().
endGoal
std::pair<int, int> NPC::endGoal [private]
Definition at line 93 of file NPC.h.
Referenced by getEndGoal(), and setEndGoal().
groupID
int NPC::groupID [private]
Definition at line 84 of file NPC.h.
Referenced by getGroupID(), and setGroupID().
id
int NPC::id [private]
Definition at line 83 of file NPC.h.
Referenced by getID(), operator==(), and setGroupID().
idle
bool NPC::idle = false [private]
Definition at line 97 of file NPC.h.
Referenced by getIdle(), and setIdle().
moving
bool NPC::moving = false [private]
Definition at line 98 of file NPC.h.
Referenced by getMoving(), and setMoving().
path
std::vector<std::shared_ptr<Node> > NPC::path [private]
Definition at line 92 of file NPC.h.
Referenced by getPath(), move(), and setPath().
reading
bool NPC::reading = false [private]
Definition at line 96 of file NPC.h.
Referenced by getReading(), and setReading().
speaking
bool NPC::speaking = false [private]
Definition at line 95 of file NPC.h.
Referenced by getSpeaking(), and setSpeaking().
speech
TextBox NPC::speech [private]
Definition at line 90 of file NPC.h.
Referenced by freeBox(), getLinesToRender(), LoadBox(), LoadComment(), NPC(), prepareComment(), renderBox(), and renderComment().
text
std::string NPC::text [private]
Definition at line 89 of file NPC.h.
Referenced by getText(), and setText().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/NPC.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/NPC.cpp