Json::StyledWriter Class Reference
Writes a Value in JSON format in a human friendly way.
#include <json.h>
Public Member Functions
StyledWriter ()
~StyledWriter () JSONCPP_OVERRIDE
JSONCPP_STRING write (const Value &root) JSONCPP_OVERRIDE
Serialize a Value in JSON format.
Private Types
typedef std::vector< JSONCPP_STRING > ChildValues
Private Member Functions
void writeValue (const Value &value)
void writeArrayValue (const Value &value)
bool isMultineArray (const Value &value)
void pushValue (const JSONCPP_STRING &value)
void writeIndent ()
void writeWithIndent (const JSONCPP_STRING &value)
void indent ()
void unindent ()
void writeCommentBeforeValue (const Value &root)
void writeCommentAfterValueOnSameLine (const Value &root)
bool hasCommentForValue (const Value &value)
Static Private Member Functions
static JSONCPP_STRING normalizeEOL (const JSONCPP_STRING &text)
Private Attributes
ChildValues childValues_
JSONCPP_STRING document_
JSONCPP_STRING indentString_
unsigned int rightMargin_
unsigned int indentSize_
bool addChildValues_
Detailed Description
Writes a Value in JSON format in a human friendly way.
The rules for line break and indent are as follow:
Object value:
if empty then print {} without indent and line break
if not empty the print '{', line break & indent, print one value per line and then unindent and line break and print '}'.
Array value:
if empty then print [] without indent and line break
if the array contains no object value, empty array or some other value types, and all the values fit on one lines, then print the array on a single line.
otherwise, it the values do not fit on one line, or the array contains object or non empty array, then print one value per line.
If the Value have comments then they are outputed according to their CommentPlacement.
See also
Reader, Value, Value::setComment()
Deprecated
Deprecated Use StreamWriterBuilder.
Definition at line 1960 of file json.h.
Member Typedef Documentation
ChildValues
typedef std::vector<JSONCPP_STRING> Json::StyledWriter::ChildValues [private]
Definition at line 1986 of file json.h.
Constructor & Destructor Documentation
StyledWriter()
Json::StyledWriter::StyledWriter ()
Definition at line 4479 of file jsoncpp.cpp.
    : rightMargin_(74), indentSize_(3), addChildValues_() {}
 StyledWriter()
Json::StyledWriter::~StyledWriter () [inline]
Definition at line 1963 of file json.h.
References JSONCPP_OVERRIDE, JSONCPP_STRING, and Json::normalizeEOL().
{}
Member Function Documentation
hasCommentForValue()
bool Json::StyledWriter::hasCommentForValue (const Value & value) [private]
Definition at line 4683 of file jsoncpp.cpp.
References Json::commentAfter, Json::commentAfterOnSameLine, Json::commentBefore, and Json::Value::hasComment().
Referenced by isMultineArray().
                                                        {
  return value.hasComment(commentBefore) ||
         value.hasComment(commentAfterOnSameLine) ||
         value.hasComment(commentAfter);
}
indent()
void Json::StyledWriter::indent () [private]
Definition at line 4645 of file jsoncpp.cpp.
References indentSize_, indentString_, and JSONCPP_STRING.
Referenced by writeArrayValue(), and writeValue().
{ indentString_ += JSONCPP_STRING(indentSize_, ' '); }
isMultineArray()
bool Json::StyledWriter::isMultineArray (const Value & value) [private]
Definition at line 4595 of file jsoncpp.cpp.
References addChildValues_, childValues_, hasCommentForValue(), Json::Value::isArray(), Json::Value::isObject(), rightMargin_, Json::Value::size(), and writeValue().
Referenced by writeArrayValue().
                                                    {
  ArrayIndex const size = value.size();
  bool isMultiLine = size * 3 >= rightMargin_;
  childValues_.clear();
  for (ArrayIndex index = 0; index < size && !isMultiLine; ++index) {
    const Value& childValue = value[index];
    isMultiLine = ((childValue.isArray() || childValue.isObject()) &&
                        childValue.size() > 0);
  }
  if (!isMultiLine) // check if line length > max line length
  {
    childValues_.reserve(size);
    addChildValues_ = true;
    ArrayIndex lineLength = 4 + (size - 1) * 2; // '[ ' + ', '*n + ' ]'
    for (ArrayIndex index = 0; index < size; ++index) {
      if (hasCommentForValue(value[index])) {
        isMultiLine = true;
      }
      writeValue(value[index]);
      lineLength += static_cast<ArrayIndex>(childValues_[index].length());
    }
    addChildValues_ = false;
    isMultiLine = isMultiLine || lineLength >= rightMargin_;
  }
  return isMultiLine;
}
normalizeEOL()
static JSONCPP_STRING Json::StyledWriter::normalizeEOL (const JSONCPP_STRING & text) [static], [private]
pushValue()
void Json::StyledWriter::pushValue (const JSONCPP_STRING & value) [private]
Definition at line 4622 of file jsoncpp.cpp.
References addChildValues_, childValues_, and document_.
Referenced by writeArrayValue(), and writeValue().
                                                        {
  if (addChildValues_)
    childValues_.push_back(value);
  else
    document_ += value;
}
unindent()
void Json::StyledWriter::unindent () [private]
Definition at line 4647 of file jsoncpp.cpp.
References indentSize_, and indentString_.
Referenced by writeArrayValue(), and writeValue().
                            {
  assert(indentString_.size() >= indentSize_);
  indentString_.resize(indentString_.size() -
      indentSize_);
}
write()
JSONCPP_STRING Json::StyledWriter::write (const Value & root) [virtual]
Serialize a Value in JSON format.
Parameters
root Value to serialize.
Returns
String containing the JSON document that represents the root value.
Implements Json::Writer.
Definition at line 4482 of file jsoncpp.cpp.
References addChildValues_, document_, indentString_, writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeValue().
Referenced by Json::Value::toStyledString().
                                                    {
  document_ = "";
  addChildValues_ = false;
  indentString_ = "";
  writeCommentBeforeValue(root);
  writeValue(root);
  writeCommentAfterValueOnSameLine(root);
  document_ += "\n";
  return document_;
}
writeArrayValue()
void Json::StyledWriter::writeArrayValue (const Value & value) [private]
Definition at line 4552 of file jsoncpp.cpp.
References childValues_, document_, indent(), isMultineArray(), pushValue(), Json::Value::size(), unindent(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), writeValue(), and writeWithIndent().
Referenced by writeValue().
                                                     {
  unsigned size = value.size();
  if (size == 0)
    pushValue("[]");
  else {
    bool isArrayMultiLine = isMultineArray(value);
    if (isArrayMultiLine) {
      writeWithIndent("[");
      indent();
      bool hasChildValue = !childValues_.empty();
      unsigned index = 0;
      for (;;) {
        const Value& childValue = value[index];
        writeCommentBeforeValue(childValue);
        if (hasChildValue)
          writeWithIndent(childValues_[index]);
        else {
          writeIndent();
          writeValue(childValue);
        }
        if (++index == size) {
          writeCommentAfterValueOnSameLine(childValue);
          break;
        }
        document_ += ',';
        writeCommentAfterValueOnSameLine(childValue);
      }
      unindent();
      writeWithIndent("]");
    } else // output on a single line
    {
      assert(childValues_.size() == size);
      document_ += "[ ";
      for (unsigned index = 0; index < size; ++index) {
        if (index > 0)
          document_ += ", ";
        document_ += childValues_[index];
      }
      document_ += " ]";
    }
  }
}
writeCommentAfterValueOnSameLine()
void Json::StyledWriter::writeCommentAfterValueOnSameLine (const Value & root) [private]
Definition at line 4672 of file jsoncpp.cpp.
References Json::commentAfter, Json::commentAfterOnSameLine, document_, Json::Value::getComment(), and Json::Value::hasComment().
Referenced by write(), writeArrayValue(), and writeValue().
                                                                     {
  if (root.hasComment(commentAfterOnSameLine))
    document_ += " " + root.getComment(commentAfterOnSameLine);
  if (root.hasComment(commentAfter)) {
    document_ += "\n";
    document_ += root.getComment(commentAfter);
    document_ += "\n";
  }
}
writeCommentBeforeValue()
void Json::StyledWriter::writeCommentBeforeValue (const Value & root) [private]
Definition at line 4652 of file jsoncpp.cpp.
References Json::commentBefore, document_, Json::Value::getComment(), Json::Value::hasComment(), JSONCPP_STRING, and writeIndent().
Referenced by write(), writeArrayValue(), and writeValue().
                                                            {
  if (!root.hasComment(commentBefore))
    return;
  document_ += "\n";
  writeIndent();
  const JSONCPP_STRING& comment = root.getComment(commentBefore);
  JSONCPP_STRING::const_iterator iter = comment.begin();
  while (iter != comment.end()) {
    document_ += *iter;
    if (*iter == '\n' &&
       (iter != comment.end() && *(iter + 1) == '/'))
      writeIndent();
    ++iter;
  }
  // Comments are stripped of trailing newlines, so add one here
  document_ += "\n";
}
writeIndent()
void Json::StyledWriter::writeIndent () [private]
Definition at line 4629 of file jsoncpp.cpp.
References document_, and indentString_.
Referenced by writeArrayValue(), writeCommentBeforeValue(), and writeWithIndent().
                               {
  if (!document_.empty()) {
    char last = document_[document_.length() - 1];
    if (last == ' ') // already indented
      return;
    if (last != '\n') // Comments may add new-line
      document_ += '\n';
  }
  document_ += indentString_;
}
writeValue()
void Json::StyledWriter::writeValue (const Value & value) [private]
Definition at line 4493 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::asBool(), Json::Value::asDouble(), Json::Value::asLargestInt(), Json::Value::asLargestUInt(), Json::booleanValue, document_, Json::Value::getMemberNames(), Json::Value::getString(), indent(), Json::intValue, JSONCPP_STRING, Json::nullValue, Json::objectValue, pushValue(), Json::realValue, Json::stringValue, Json::Value::type(), Json::uintValue, unindent(), Json::valueToQuotedString(), Json::valueToQuotedStringN(), Json::valueToString(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeWithIndent().
Referenced by isMultineArray(), write(), and writeArrayValue().
                                                {
  switch (value.type()) {
  case nullValue:
    pushValue("null");
    break;
  case intValue:
    pushValue(valueToString(value.asLargestInt()));
    break;
  case uintValue:
    pushValue(valueToString(value.asLargestUInt()));
    break;
  case realValue:
    pushValue(valueToString(value.asDouble()));
    break;
  case stringValue:
  {
    // Is NULL possible for value.string_? No.
    char const* str;
    char const* end;
    bool ok = value.getString(&str, &end);
    if (ok) pushValue(valueToQuotedStringN(str, static_cast<unsigned>(end-str)
      ));
    else pushValue("");
    break;
  }
  case booleanValue:
    pushValue(valueToString(value.asBool()));
    break;
  case arrayValue:
    writeArrayValue(value);
    break;
  case objectValue: {
    Value::Members members(value.getMemberNames());
    if (members.empty())
      pushValue("{}");
    else {
      writeWithIndent("{");
      indent();
      Value::Members::iterator it = members.begin();
      for (;;) {
        const JSONCPP_STRING& name = *it;
        const Value& childValue = value[name];
        writeCommentBeforeValue(childValue);
        writeWithIndent(valueToQuotedString(name.c_str()));
        document_ += " : ";
        writeValue(childValue);
        if (++it == members.end()) {
          writeCommentAfterValueOnSameLine(childValue);
          break;
        }
        document_ += ',';
        writeCommentAfterValueOnSameLine(childValue);
      }
      unindent();
      writeWithIndent("}");
    }
  } break;
  }
}
writeWithIndent()
void Json::StyledWriter::writeWithIndent (const JSONCPP_STRING & value) [private]
Definition at line 4640 of file jsoncpp.cpp.
References document_, and writeIndent().
Referenced by writeArrayValue(), and writeValue().
                                                              {
  writeIndent();
  document_ += value;
}
Member Data Documentation
addChildValues_
bool Json::StyledWriter::addChildValues_ [private]
Definition at line 1993 of file json.h.
Referenced by isMultineArray(), pushValue(), and write().
childValues_
ChildValues Json::StyledWriter::childValues_ [private]
Definition at line 1988 of file json.h.
Referenced by isMultineArray(), pushValue(), and writeArrayValue().
document_
JSONCPP_STRING Json::StyledWriter::document_ [private]
Definition at line 1989 of file json.h.
Referenced by pushValue(), write(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), writeValue(), and writeWithIndent().
indentSize_
unsigned int Json::StyledWriter::indentSize_ [private]
Definition at line 1992 of file json.h.
Referenced by indent(), and unindent().
indentString_
JSONCPP_STRING Json::StyledWriter::indentString_ [private]
Definition at line 1990 of file json.h.
Referenced by indent(), unindent(), write(), and writeIndent().
rightMargin_
unsigned int Json::StyledWriter::rightMargin_ [private]
Definition at line 1991 of file json.h.
Referenced by isMultineArray().
The documentation for this class was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/json.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/jsoncpp.cpp