Json Namespace Reference
JSON (JavaScript Object Notation).
Classes
struct BuiltStyledStreamWriter
class CharReader
class CharReaderBuilder
Build a CharReader implementation.
struct CommentStyle
Scoped enums are not available until C++11.
class Exception
class FastWriter
Outputs a Value in JSON format without formatting (not human friendly).
class Features
Configuration passed to reader and writer. This configuration object can be used to force the Reader or Writer to behave in a standard conforming way.
class LogicError
class OurCharReader
class OurFeatures
class OurReader
class Path
Experimental and untested: represents a `path` to access a node.
class PathArgument
Experimental and untested: represents an element of the `path` to access a node.
class Reader
Unserialize a JSON document into a Value.
class RuntimeError
class StaticString
Lightweight wrapper to tag static string.
class StreamWriter
class StreamWriterBuilder
Build a StreamWriter implementation.
class StyledStreamWriter
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
class StyledWriter
Writes a Value in JSON format in a human friendly way.
class Value
Represents a JSON value.
class ValueConstIterator
const iterator for object and array value.
class ValueIterator
Iterator for object and array value.
class ValueIteratorBase
base class for Value iterators.
class Writer
Abstract class for writers.
Typedefs
typedef int Int
typedef unsigned int UInt
typedef int64_t Int64
typedef uint64_t UInt64
typedef Int64 LargestInt
typedef UInt64 LargestUInt
typedef unsigned int ArrayIndex
typedef char UIntToStringBuffer[uintToStringBufferSize]
typedef std::auto_ptr< CharReader > CharReaderPtr
typedef std::auto_ptr< StreamWriter > StreamWriterPtr
Enumerations
enum ValueType {
nullValue = 0,
intValue,
uintValue,
realValue,
stringValue,
booleanValue,
arrayValue,
objectValue
 }
Type of the value held by a Value object.
enum CommentPlacement { commentBefore = 0,
commentAfterOnSameLine,
commentAfter,
numberOfCommentPlacement
 }
enum { uintToStringBufferSize = 3 * sizeof(LargestUInt) + 1
 }
Functions
JSONCPP_NORETURN void throwRuntimeError (JSONCPP_STRING const &msg)
used internally
JSONCPP_NORETURN void throwLogicError (JSONCPP_STRING const &msg)
used internally
bool JSON_API parseFromStream (CharReader::Factory const &, JSONCPP_ISTREAM &, Value *root, std::string *errs)
JSON_API JSONCPP_ISTREAM & operator>> (JSONCPP_ISTREAM &, Value &)
Read from 'sin' into 'root'.
JSONCPP_STRING JSON_API writeString (StreamWriter::Factory const &factory, Value const &root)
Write into stringstream, then return string, for convenience. A StreamWriter will be created from the factory, used, and then deleted.
JSONCPP_STRING JSON_API valueToString (Int value)
JSONCPP_STRING JSON_API valueToString (UInt value)
JSONCPP_STRING JSON_API valueToString (LargestInt value)
JSONCPP_STRING JSON_API valueToString (LargestUInt value)
JSONCPP_STRING JSON_API valueToString (double value)
JSONCPP_STRING JSON_API valueToString (bool value)
JSONCPP_STRING JSON_API valueToQuotedString (const char *value)
JSON_API JSONCPP_OSTREAM & operator<< (JSONCPP_OSTREAM &, const Value &root)
Output using the StyledStreamWriter.
static char getDecimalPoint ()
static JSONCPP_STRING codePointToUTF8 (unsigned int cp)
Converts a unicode code-point to UTF-8.
static bool isControlCharacter (char ch)
Returns true if ch is a control character (in range [1,31]).
static void uintToString (LargestUInt value, char *&current)
static void fixNumericLocale (char *begin, char *end)
static void fixNumericLocaleInput (char *begin, char *end)
static bool containsNewLine (Reader::Location begin, Reader::Location end)
static JSONCPP_STRING normalizeEOL (Reader::Location begin, Reader::Location end)
static void getValidReaderKeys (std::set< JSONCPP_STRING > *valid_keys)
bool parseFromStream (CharReader::Factory const &fact, JSONCPP_ISTREAM &sin, Value *root, JSONCPP_STRING *errs)
template<typename T , typename U >
static bool InRange (double d, T min, U max)
static char * duplicateStringValue (const char *value, size_t length)
static char * duplicateAndPrefixStringValue (const char *value, unsigned int length)
static void decodePrefixedString (bool isPrefixed, char const *prefixed, unsigned *length, char const **value)
static void releasePrefixedStringValue (char *value)
static void releaseStringValue (char *value, unsigned)
static bool IsIntegral (double d)
static bool containsControlCharacter (const char *str)
static bool containsControlCharacter0 (const char *str, unsigned len)
static char const * strnpbrk (char const *s, char const *accept, size_t n)
static JSONCPP_STRING valueToQuotedStringN (const char *value, unsigned length)
static void getValidWriterKeys (std::set< JSONCPP_STRING > *valid_keys)
Variables
static const double maxUInt64AsDouble = 18446744073709551615.0
Detailed Description
JSON (JavaScript Object Notation).
Typedef Documentation
ArrayIndex
typedef unsigned int Json::ArrayIndex
Definition at line 339 of file json.h.
CharReaderPtr
typedef std::auto_ptr<CharReader> Json::CharReaderPtr
Definition at line 276 of file jsoncpp.cpp.
Int
typedef int Json::Int
Definition at line 268 of file json.h.
Int64
typedef int64_t Json::Int64
Definition at line 280 of file json.h.
LargestInt
typedef Int64 Json::LargestInt
Definition at line 283 of file json.h.
LargestUInt
typedef UInt64 Json::LargestUInt
Definition at line 284 of file json.h.
StreamWriterPtr
typedef std::auto_ptr<StreamWriter> Json::StreamWriterPtr
Definition at line 4158 of file jsoncpp.cpp.
UInt
typedef unsigned int Json::UInt
Definition at line 269 of file json.h.
UInt64
typedef uint64_t Json::UInt64
Definition at line 281 of file json.h.
UIntToStringBuffer
typedef char Json::UIntToStringBuffer[uintToStringBufferSize]
Definition at line 159 of file jsoncpp.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
uintToStringBufferSize Constant that specify the size of the buffer that must be passed to uintToString.
Definition at line 152 of file jsoncpp.cpp.
     {
  uintToStringBufferSize = 3 * sizeof(LargestUInt) + 1
};
CommentPlacement
enum Json::CommentPlacement
Enumerator
commentBefore a comment placed on the line before a value
commentAfterOnSameLine a comment just after a value on the same line
commentAfter a comment on the line after a value (only make sense for
numberOfCommentPlacement root value)
Definition at line 546 of file json.h.
                      {
  commentBefore = 0,
  commentAfterOnSameLine,
  commentAfter,
  numberOfCommentPlacement
};
ValueType
enum Json::ValueType
Type of the value held by a Value object.
Enumerator
nullValue 'null' value
intValue signed integer value
uintValue unsigned integer value
realValue double value
stringValue UTF-8 string value.
booleanValue bool value
arrayValue array value (ordered list)
objectValue object value (collection of name/value pairs).
Definition at line 535 of file json.h.
               {
  nullValue = 0,
  intValue,
  uintValue,
  realValue,
  stringValue,
  booleanValue,
  arrayValue,
  objectValue
};
Function Documentation
codePointToUTF8()
static JSONCPP_STRING Json::codePointToUTF8 (unsigned int cp) [inline], [static]
Converts a unicode code-point to UTF-8.
Definition at line 121 of file jsoncpp.cpp.
References JSONCPP_STRING.
Referenced by Json::OurReader::decodeString(), and Json::Reader::decodeString().
                                                              {
  JSONCPP_STRING result;
  // based on description from http://en.wikipedia.org/wiki/UTF-8
  if (cp <= 0x7f) {
    result.resize(1);
    result[0] = static_cast<char>(cp);
  } else if (cp <= 0x7FF) {
    result.resize(2);
    result[1] = static_cast<char>(0x80 | (0x3f & cp));
    result[0] = static_cast<char>(0xC0 | (0x1f & (cp >> 6)));
  } else if (cp <= 0xFFFF) {
    result.resize(3);
    result[2] = static_cast<char>(0x80 | (0x3f & cp));
    result[1] = static_cast<char>(0x80 | (0x3f & (cp >> 6)));
    result[0] = static_cast<char>(0xE0 | (0xf & (cp >> 12)));
  } else if (cp <= 0x10FFFF) {
    result.resize(4);
    result[3] = static_cast<char>(0x80 | (0x3f & cp));
    result[2] = static_cast<char>(0x80 | (0x3f & (cp >> 6)));
    result[1] = static_cast<char>(0x80 | (0x3f & (cp >> 12)));
    result[0] = static_cast<char>(0xF0 | (0x7 & (cp >> 18)));
  }
  return result;
}
containsControlCharacter()
static bool Json::containsControlCharacter (const char * str) [static]
Definition at line 4161 of file jsoncpp.cpp.
References isControlCharacter().
Referenced by valueToQuotedString().
                                                      {
  while (*str) {
    if (isControlCharacter(*(str++)))
      return true;
  }
  return false;
}
containsControlCharacter0()
static bool Json::containsControlCharacter0 (const char * str, unsigned len) [static]
Definition at line 4169 of file jsoncpp.cpp.
References isControlCharacter().
Referenced by valueToQuotedStringN().
                                                                     {
  char const* end = str + len;
  while (end != str) {
    if (isControlCharacter(*str) || 0==*str)
      return true;
    ++str;
  }
  return false;
}
containsNewLine()
static bool Json::containsNewLine (Reader::Location begin, Reader::Location end) [static]
Definition at line 300 of file jsoncpp.cpp.
Referenced by Json::OurReader::readComment(), and Json::Reader::readComment().
                                                                      {
  for (; begin < end; ++begin)
    if (*begin == '\n' || *begin == '\r')
      return true;
  return false;
}
decodePrefixedString()
static void Json::decodePrefixedString (bool isPrefixed, char const * prefixed, unsigned * length, char const ** value) [inline], [static]
Definition at line 2586 of file jsoncpp.cpp.
References releasePrefixedStringValue(), and releaseStringValue().
Referenced by Json::Value::asCString(), Json::Value::asString(), Json::Value::getString(), Json::Value::operator<(), Json::Value::operator==(), and Json::Value::Value().
{
  if (!isPrefixed) {
    *length = static_cast<unsigned>(strlen(prefixed));
    *value = prefixed;
  } else {
    *length = *reinterpret_cast<unsigned const*>(prefixed);
    *value = prefixed + sizeof(unsigned);
  }
}
duplicateAndPrefixStringValue()
static char* Json::duplicateAndPrefixStringValue (const char * value, unsigned int length) [inline], [static]
Definition at line 2565 of file jsoncpp.cpp.
References JSON_ASSERT_MESSAGE, and throwRuntimeError().
Referenced by Json::Value::Value().
{
  // Avoid an integer overflow in the call to malloc below by limiting length
  // to a sane value.
  JSON_ASSERT_MESSAGE(length <= static_cast<unsigned>(Value::maxInt) - sizeof(unsigned)
      - 1U,
                      "in Json::Value::duplicateAndPrefixStringValue(): "
                      "length too big for prefixing");
  unsigned actualLength = length + static_cast<unsigned>(sizeof(unsigned)) + 1U;
  char* newString = static_cast<char*>(malloc(actualLength));
  if (newString == 0) {
    throwRuntimeError(
        "in Json::Value::duplicateAndPrefixStringValue(): "
        "Failed to allocate string value buffer");
  }
  *reinterpret_cast<unsigned*>(newString) = length;
  memcpy(newString + sizeof(unsigned), value, length);
  newString[actualLength - 1U] = 0; // to avoid buffer over-run accidents by users later
  return newString;
}
duplicateStringValue()
static char* Json::duplicateStringValue (const char * value, size_t length) [inline], [static]
Duplicates the specified string value.
Parameters
value Pointer to the string to duplicate. Must be zero-terminated if length is `unknown`.
length Length of the value. if equals to unknown, then it will be computed using strlen(value).
Returns
Pointer on the duplicate instance of string.
Definition at line 2544 of file jsoncpp.cpp.
References throwRuntimeError().
Referenced by Json::Value::CZString::CZString(), and Json::Value::CommentInfo::setComment().
{
  // Avoid an integer overflow in the call to malloc below by limiting length
  // to a sane value.
  if (length >= static_cast<size_t>(Value::maxInt))
    length = Value::maxInt - 1;
  char* newString = static_cast<char*>(malloc(length + 1));
  if (newString == NULL) {
    throwRuntimeError(
        "in Json::Value::duplicateStringValue(): "
        "Failed to allocate string value buffer");
  }
  memcpy(newString, value, length);
  newString[length] = 0;
  return newString;
}
fixNumericLocale()
static void Json::fixNumericLocale (char * begin, char * end) [inline], [static]
Change ',' to '.' everywhere in buffer.
We had a sophisticated way, but it did not work in WinCE.
See also
https://github.com/open-source-parsers/jsoncpp/pull/9
Definition at line 179 of file jsoncpp.cpp.
Referenced by valueToString().
                                                            {
  while (begin < end) {
    if (*begin == ',') {
      *begin = '.';
    }
    ++begin;
  }
}
fixNumericLocaleInput()
static void Json::fixNumericLocaleInput (char * begin, char * end) [inline], [static]
Definition at line 188 of file jsoncpp.cpp.
References getDecimalPoint().
Referenced by Json::OurReader::decodeDouble().
                                                                 {
  char decimalPoint = getDecimalPoint();
  if (decimalPoint != '\0' && decimalPoint != '.') {
    while (begin < end) {
      if (*begin == '.') {
        *begin = decimalPoint;
      }
      ++begin;
    }
  }
}
getDecimalPoint()
static char Json::getDecimalPoint () [static]
Definition at line 111 of file jsoncpp.cpp.
Referenced by fixNumericLocaleInput().
                              {
#ifdef JSONCPP_NO_LOCALE_SUPPORT
  return '\0';
#else
  struct lconv* lc = localeconv();
  return lc ? *(lc->decimal_point) : '\0';
#endif
}
getValidReaderKeys()
static void Json::getValidReaderKeys (std::set< JSONCPP_STRING > * valid_keys) [static]
Definition at line 2154 of file jsoncpp.cpp.
Referenced by Json::CharReaderBuilder::validate().
{
  valid_keys->clear();
  valid_keys->insert("collectComments");
  valid_keys->insert("allowComments");
  valid_keys->insert("strictRoot");
  valid_keys->insert("allowDroppedNullPlaceholders");
  valid_keys->insert("allowNumericKeys");
  valid_keys->insert("allowSingleQuotes");
  valid_keys->insert("stackLimit");
  valid_keys->insert("failIfExtra");
  valid_keys->insert("rejectDupKeys");
  valid_keys->insert("allowSpecialFloats");
}
getValidWriterKeys()
static void Json::getValidWriterKeys (std::set< JSONCPP_STRING > * valid_keys) [static]
Definition at line 5243 of file jsoncpp.cpp.
Referenced by Json::StreamWriterBuilder::validate().
{
  valid_keys->clear();
  valid_keys->insert("indentation");
  valid_keys->insert("commentStyle");
  valid_keys->insert("enableYAMLCompatibility");
  valid_keys->insert("dropNullPlaceholders");
  valid_keys->insert("useSpecialFloats");
  valid_keys->insert("precision");
}
InRange()
template<typename T , typename U >
static bool Json::InRange (double d, T min, U max) [inline], [static]
Definition at line 2516 of file jsoncpp.cpp.
Referenced by Json::Value::asInt(), Json::Value::asInt64(), Json::Value::asUInt(), Json::Value::asUInt64(), and Json::Value::isConvertibleTo().
                                                   {
  // The casts can lose precision, but we are looking only for
  // an approximate range. Might fail on edge cases though. ~cdunn
  //return d >= static_cast<double>(min) && d <= static_cast<double>(max);
  return d >= min && d <= max;
}
isControlCharacter()
static bool Json::isControlCharacter (char ch) [inline], [static]
Returns true if ch is a control character (in range [1,31]).
Definition at line 150 of file jsoncpp.cpp.
Referenced by containsControlCharacter(), containsControlCharacter0(), valueToQuotedString(), and valueToQuotedStringN().
{ return ch > 0 && ch <= 0x1F; }
IsIntegral()
static bool Json::IsIntegral (double d) [static]
Definition at line 3717 of file jsoncpp.cpp.
Referenced by Json::Value::isInt(), Json::Value::isInt64(), Json::Value::isUInt(), and Json::Value::isUInt64().
                                 {
  double integral_part;
  return modf(d, &integral_part) == 0.0;
}
normalizeEOL()
static JSONCPP_STRING Json::normalizeEOL (Reader::Location begin, Reader::Location end) [static]
Definition at line 589 of file jsoncpp.cpp.
References JSONCPP_STRING.
Referenced by Json::OurReader::addComment(), Json::Reader::addComment(), Json::StyledStreamWriter::~StyledStreamWriter(), and Json::StyledWriter::~StyledWriter().
                                                                             {
  JSONCPP_STRING normalized;
  normalized.reserve(static_cast<size_t>(end - begin));
  Reader::Location current = begin;
  while (current != end) {
    char c = *current++;
    if (c == '\r') {
      if (current != end && *current == '\n')
         // convert dos EOL
         ++current;
      // convert Mac EOL
      normalized += '\n';
    } else {
      normalized += c;
    }
  }
  return normalized;
}
operator<<()
JSONCPP_OSTREAM & Json::operator<< (JSONCPP_OSTREAM & sout, const Value & root)
Output using the StyledStreamWriter.
See also
Json::operator>>()
Definition at line 5294 of file jsoncpp.cpp.
References Json::StreamWriterBuilder::newStreamWriter().
                                                                      {
  StreamWriterBuilder builder;
  StreamWriterPtr const writer(builder.newStreamWriter());
  writer->write(root, &sout);
  return sout;
}
operator>>()
JSONCPP_ISTREAM & Json::operator>> (JSONCPP_ISTREAM & sin, Value & root)
Read from 'sin' into 'root'.
Always keep comments from the input JSON.
This can be used to read a file into a particular sub-object. For example:
Json::Value root;
cin >> root["dir"]["file"];
cout << root;
 Result:
{
"dir": {
    "file": {
    // The input stream JSON would be nested here.
    }
}
}
Exceptions
std::exception on parse error.
See also
Json::operator<<()
Definition at line 2238 of file jsoncpp.cpp.
References JSONCPP_STRING, parseFromStream(), and throwRuntimeError().
                                                               {
  CharReaderBuilder b;
  JSONCPP_STRING errs;
  bool ok = parseFromStream(b, sin, &root, &errs);
  if (!ok) {
    fprintf(stderr,
            "Error from reader: %s",
            errs.c_str());
    throwRuntimeError(errs);
  }
  return sin;
}
parseFromStream() [1/2]
bool JSON_API Json::parseFromStream (CharReader::Factory const & , JSONCPP_ISTREAM & , Value * root, std::string * errs)
Consume entire stream and use its begin/end. Someday we might have a real StreamReader, but for now this is convenient.
Referenced by operator>>().
parseFromStream() [2/2]
bool Json::parseFromStream (CharReader::Factory const & fact, JSONCPP_ISTREAM & sin, Value * root, JSONCPP_STRING * errs)
Definition at line 2224 of file jsoncpp.cpp.
References JSONCPP_OSTRINGSTREAM, JSONCPP_STRING, and Json::CharReader::Factory::newCharReader().
{
  JSONCPP_OSTRINGSTREAM ssin;
  ssin << sin.rdbuf();
  JSONCPP_STRING doc = ssin.str();
  char const* begin = doc.data();
  char const* end = begin + doc.size();
  // Note that we do not actually need a null-terminator.
  CharReaderPtr const reader(fact.newCharReader());
  return reader->parse(begin, end, root, errs);
}
releasePrefixedStringValue()
static void Json::releasePrefixedStringValue (char * value) [inline], [static]
Free the string duplicated by duplicateStringValue()/duplicateAndPrefixStringValue().
Definition at line 2616 of file jsoncpp.cpp.
Referenced by decodePrefixedString(), and Json::Value::~Value().
                                                           {
  free(value);
}
releaseStringValue()
static void Json::releaseStringValue (char * value, unsigned) [inline], [static]
Definition at line 2619 of file jsoncpp.cpp.
Referenced by decodePrefixedString(), Json::Value::CommentInfo::setComment(), Json::Value::CommentInfo::~CommentInfo(), and Json::Value::CZString::~CZString().
                                                             {
  free(value);
}
strnpbrk()
static char const* Json::strnpbrk (char const * s, char const * accept, size_t n) [static]
Definition at line 4320 of file jsoncpp.cpp.
Referenced by valueToQuotedStringN().
                                                                         {
  assert((s || !n) && accept);
  char const* const end = s + n;
  for (char const* cur = s; cur < end; ++cur) {
    int const c = *cur;
    for (char const* a = accept; *a; ++a) {
      if (*a == c) {
        return cur;
      }
    }
  }
  return NULL;
}
throwLogicError()
JSONCPP_NORETURN void Json::throwLogicError (JSONCPP_STRING const & msg)
used internally
Definition at line 2659 of file jsoncpp.cpp.
References Json::LogicError::LogicError().
{
  throw LogicError(msg);
}
throwRuntimeError()
JSONCPP_NORETURN void Json::throwRuntimeError (JSONCPP_STRING const & msg)
used internally
Definition at line 2655 of file jsoncpp.cpp.
Referenced by duplicateAndPrefixStringValue(), duplicateStringValue(), Json::StreamWriterBuilder::newStreamWriter(), operator>>(), Json::OurReader::readObject(), Json::OurReader::readValue(), Json::Reader::readValue(), and Json::ValueIterator::ValueIterator().
{
  throw RuntimeError(msg);
}
uintToString()
static void Json::uintToString (LargestUInt value, char *& current) [inline], [static]
Converts an unsigned integer to string.
Parameters
value Unsigned interger to convert to string
current Input/Output string buffer. Must have at least uintToStringBufferSize chars free.
Definition at line 166 of file jsoncpp.cpp.
Referenced by valueToString().
                                                                   {
  *--current = 0;
  do {
    *--current = static_cast<char>(value % 10U + static_cast<unsigned>('0'));
    value /= 10;
  } while (value != 0);
}
valueToQuotedString()
JSONCPP_STRING Json::valueToQuotedString (const char * value)
Definition at line 4257 of file jsoncpp.cpp.
References containsControlCharacter(), isControlCharacter(), JSONCPP_OSTRINGSTREAM, and JSONCPP_STRING.
Referenced by Json::StyledWriter::writeValue(), and Json::StyledStreamWriter::writeValue().
                                                      {
  if (value == NULL)
    return "";
  // Not sure how to handle unicode...
  if (strpbrk(value, "\"\\\b\f\n\r\t") == NULL &&
      !containsControlCharacter(value))
    return JSONCPP_STRING("\"") + value + "\"";
  // We have to walk value and escape any special characters.
  // Appending to JSONCPP_STRING is not efficient, but this should be rare.
  // (Note: forward slashes are *not* rare, but I am not escaping them.)
  JSONCPP_STRING::size_type maxsize =
      strlen(value) * 2 + 3; // allescaped+quotes+NULL
  JSONCPP_STRING result;
  result.reserve(maxsize); // to avoid lots of mallocs
  result += "\"";
  for (const char* c = value; *c != 0; ++c) {
    switch (*c) {
    case '\"':
      result += "\\\"";
      break;
    case '\\':
      result += "\\\\";
      break;
    case '\b':
      result += "\\b";
      break;
    case '\f':
      result += "\\f";
      break;
    case '\n':
      result += "\\n";
      break;
    case '\r':
      result += "\\r";
      break;
    case '\t':
      result += "\\t";
      break;
    // case '/':
    // Even though \/ is considered a legal escape in JSON, a bare
    // slash is also legal, so I see no reason to escape it.
    // (I hope I am not misunderstanding something.
    // blep notes: actually escaping \/ may be useful in javascript to avoid </
    // sequence.
    // Should add a flag to allow this compatibility mode and prevent this
    // sequence from occurring.
    default:
      if (isControlCharacter(*c)) {
        JSONCPP_OSTRINGSTREAM oss;
        oss << "\\u" << std::hex << std::uppercase << std::setfill('0')
            << std::setw(4) << static_cast<int>(*c);
        result += oss.str();
      } else {
        result += *c;
      }
      break;
    }
  }
  result += "\"";
  return result;
}
valueToQuotedStringN()
static JSONCPP_STRING Json::valueToQuotedStringN (const char * value, unsigned length) [static]
Definition at line 4334 of file jsoncpp.cpp.
References containsControlCharacter0(), isControlCharacter(), JSONCPP_OSTRINGSTREAM, JSONCPP_STRING, and strnpbrk().
Referenced by Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
                                                                               {
  if (value == NULL)
    return "";
  // Not sure how to handle unicode...
  if (strnpbrk(value, "\"\\\b\f\n\r\t", length) == NULL &&
      !containsControlCharacter0(value, length))
    return JSONCPP_STRING("\"") + value + "\"";
  // We have to walk value and escape any special characters.
  // Appending to JSONCPP_STRING is not efficient, but this should be rare.
  // (Note: forward slashes are *not* rare, but I am not escaping them.)
  JSONCPP_STRING::size_type maxsize =
      length * 2 + 3; // allescaped+quotes+NULL
  JSONCPP_STRING result;
  result.reserve(maxsize); // to avoid lots of mallocs
  result += "\"";
  char const* end = value + length;
  for (const char* c = value; c != end; ++c) {
    switch (*c) {
    case '\"':
      result += "\\\"";
      break;
    case '\\':
      result += "\\\\";
      break;
    case '\b':
      result += "\\b";
      break;
    case '\f':
      result += "\\f";
      break;
    case '\n':
      result += "\\n";
      break;
    case '\r':
      result += "\\r";
      break;
    case '\t':
      result += "\\t";
      break;
    // case '/':
    // Even though \/ is considered a legal escape in JSON, a bare
    // slash is also legal, so I see no reason to escape it.
    // (I hope I am not misunderstanding something.)
    // blep notes: actually escaping \/ may be useful in javascript to avoid </
    // sequence.
    // Should add a flag to allow this compatibility mode and prevent this
    // sequence from occurring.
    default:
      if ((isControlCharacter(*c)) || (*c == 0)) {
        JSONCPP_OSTRINGSTREAM oss;
        oss << "\\u" << std::hex << std::uppercase << std::setfill('0')
            << std::setw(4) << static_cast<int>(*c);
        result += oss.str();
      } else {
        result += *c;
      }
      break;
    }
  }
  result += "\"";
  return result;
}
valueToString() [1/6]
JSONCPP_STRING Json::valueToString (Int value)
Definition at line 4205 of file jsoncpp.cpp.
Referenced by Json::Value::asString(), valueToString(), Json::FastWriter::writeValue(), Json::StyledWriter::writeValue(), Json::StyledStreamWriter::writeValue(), and Json::BuiltStyledStreamWriter::writeValue().
                                        {
  return valueToString(LargestInt(value));
}
valueToString() [2/6]
JSONCPP_STRING Json::valueToString (UInt value)
Definition at line 4209 of file jsoncpp.cpp.
References fixNumericLocale(), isfinite, JSONCPP_STRING, and valueToString().
                                         {
  return valueToString(LargestUInt(value));
}
valueToString() [3/6]
JSONCPP_STRING Json::valueToString (LargestInt value)
Definition at line 4179 of file jsoncpp.cpp.
References uintToString().
                                               {
  UIntToStringBuffer buffer;
  char* current = buffer + sizeof(buffer);
  if (value == Value::minLargestInt) {
    uintToString(LargestUInt(Value::maxLargestInt) + 1, current);
    *--current = '-';
  } else if (value < 0) {
    uintToString(LargestUInt(-value), current);
    *--current = '-';
  } else {
    uintToString(LargestUInt(value), current);
  }
  assert(current >= buffer);
  return current;
}
valueToString() [4/6]
JSONCPP_STRING Json::valueToString (LargestUInt value)
Definition at line 4195 of file jsoncpp.cpp.
References uintToString().
                                                {
  UIntToStringBuffer buffer;
  char* current = buffer + sizeof(buffer);
  uintToString(value, current);
  assert(current >= buffer);
  return current;
}
valueToString() [5/6]
JSONCPP_STRING Json::valueToString (double value)
Definition at line 4253 of file jsoncpp.cpp.
References valueToString().
{ return valueToString(value, false, 17); }
valueToString() [6/6]
JSONCPP_STRING Json::valueToString (bool value)
Definition at line 4255 of file jsoncpp.cpp.
{ return value ? "true" : "false"; }
writeString()
JSONCPP_STRING Json::writeString (StreamWriter::Factory const & factory, Value const & root)
Write into stringstream, then return string, for convenience. A StreamWriter will be created from the factory, used, and then deleted.
Definition at line 5287 of file jsoncpp.cpp.
References JSONCPP_OSTRINGSTREAM, and Json::StreamWriter::Factory::newStreamWriter().
                                                                                  {
  JSONCPP_OSTRINGSTREAM sout;
  StreamWriterPtr const writer(builder.newStreamWriter());
  writer->write(root, &sout);
  return sout.str();
}
Variable Documentation
maxUInt64AsDouble
const double Json::maxUInt64AsDouble = 18446744073709551615.0 [static]
Definition at line 2508 of file jsoncpp.cpp.