Json::Value::CommentInfo Struct Reference
Public Member Functions
CommentInfo ()
~CommentInfo ()
void setComment (const char *text, size_t len)
Public Attributes
char * comment_
Detailed Description
Definition at line 1030 of file json.h.
Constructor & Destructor Documentation
CommentInfo()
Json::Value::CommentInfo::CommentInfo ()
Definition at line 2672 of file jsoncpp.cpp.
                              : comment_(0)
{}
 CommentInfo()
Json::Value::CommentInfo::~CommentInfo ()
Definition at line 2675 of file jsoncpp.cpp.
References comment_, and Json::releaseStringValue().
                               {
  if (comment_)
    releaseStringValue(comment_, 0u);
}
Member Function Documentation
setComment()
void Json::Value::CommentInfo::setComment (const char * text, size_t len)
Definition at line 2680 of file jsoncpp.cpp.
References comment_, Json::duplicateStringValue(), JSON_ASSERT, JSON_ASSERT_MESSAGE, and Json::releaseStringValue().
Referenced by Json::Value::setComment(), and Json::Value::Value().
                                                              {
  if (comment_) {
    releaseStringValue(comment_, 0u);
    comment_ = 0;
  }
  JSON_ASSERT(text != 0);
  JSON_ASSERT_MESSAGE(
      text[0] == '\0' || text[0] == '/',
      "in Json::Value::setComment(): Comments must start with /");
  // It seems that /**/ style comments are acceptable as well.
  comment_ = duplicateStringValue(text, len);
}
Member Data Documentation
comment_
char* Json::Value::CommentInfo::comment_
Definition at line 1036 of file json.h.
Referenced by Json::Value::getComment(), Json::Value::hasComment(), setComment(), Json::Value::Value(), and ~CommentInfo().
The documentation for this struct was generated from the following files:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/json.h
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/jsoncpp.cpp