Json::BuiltStyledStreamWriter Struct Reference
Public Member Functions
BuiltStyledStreamWriter (JSONCPP_STRING const &indentation, CommentStyle::Enum cs, JSONCPP_STRING const &colonSymbol, JSONCPP_STRING const &nullSymbol, JSONCPP_STRING const &endingLineFeedSymbol, bool useSpecialFloats, unsigned int precision)
int write (Value const &root, JSONCPP_OSTREAM *sout) JSONCPP_OVERRIDE
Private Types
typedef std::vector< JSONCPP_STRING > ChildValues
Private Member Functions
void writeValue (Value const &value)
void writeArrayValue (Value const &value)
bool isMultineArray (Value const &value)
void pushValue (JSONCPP_STRING const &value)
void writeIndent ()
void writeWithIndent (JSONCPP_STRING const &value)
void indent ()
void unindent ()
void writeCommentBeforeValue (Value const &root)
void writeCommentAfterValueOnSameLine (Value const &root)
Static Private Member Functions
static bool hasCommentForValue (const Value &value)
Private Attributes
ChildValues childValues_
JSONCPP_STRING indentString_
unsigned int rightMargin_
JSONCPP_STRING indentation_
CommentStyle::Enum cs_
JSONCPP_STRING colonSymbol_
JSONCPP_STRING nullSymbol_
JSONCPP_STRING endingLineFeedSymbol_
bool addChildValues_: 1
bool indented_: 1
bool useSpecialFloats_: 1
unsigned int precision_
Additional Inherited Members
Detailed Description
Definition at line 4917 of file jsoncpp.cpp.
Member Typedef Documentation
ChildValues
typedef std::vector<JSONCPP_STRING> Json::BuiltStyledStreamWriter::ChildValues [private]
Definition at line 4941 of file jsoncpp.cpp.
Constructor & Destructor Documentation
BuiltStyledStreamWriter()
Json::BuiltStyledStreamWriter::BuiltStyledStreamWriter (JSONCPP_STRING const & indentation, CommentStyle::Enum cs, JSONCPP_STRING const & colonSymbol, JSONCPP_STRING const & nullSymbol, JSONCPP_STRING const & endingLineFeedSymbol, bool useSpecialFloats, unsigned int precision)
Definition at line 4956 of file jsoncpp.cpp.
  : rightMargin_(74)
  , indentation_(indentation)
  , cs_(cs)
  , colonSymbol_(colonSymbol)
  , nullSymbol_(nullSymbol)
  , endingLineFeedSymbol_(endingLineFeedSymbol)
  , addChildValues_(false)
  , indented_(false)
  , useSpecialFloats_(useSpecialFloats)
  , precision_(precision)
{
}
Member Function Documentation
hasCommentForValue()
bool Json::BuiltStyledStreamWriter::hasCommentForValue (const Value & value) [static], [private]
Definition at line 5187 of file jsoncpp.cpp.
References Json::commentAfter, Json::commentAfterOnSameLine, Json::commentBefore, and Json::Value::hasComment().
Referenced by isMultineArray().
                                                                   {
  return value.hasComment(commentBefore) ||
         value.hasComment(commentAfterOnSameLine) ||
         value.hasComment(commentAfter);
}
indent()
void Json::BuiltStyledStreamWriter::indent () [private]
Definition at line 5149 of file jsoncpp.cpp.
References indentation_, and indentString_.
Referenced by writeArrayValue(), and writeValue().
{ indentString_ += indentation_; }
isMultineArray()
bool Json::BuiltStyledStreamWriter::isMultineArray (Value const & value) [private]
Definition at line 5097 of file jsoncpp.cpp.
References addChildValues_, childValues_, hasCommentForValue(), Json::Value::isArray(), Json::Value::isObject(), rightMargin_, Json::Value::size(), and writeValue().
Referenced by writeArrayValue().
                                                               {
  ArrayIndex const size = value.size();
  bool isMultiLine = size * 3 >= rightMargin_;
  childValues_.clear();
  for (ArrayIndex index = 0; index < size && !isMultiLine; ++index) {
    Value const& childValue = value[index];
    isMultiLine = ((childValue.isArray() || childValue.isObject()) &&
                        childValue.size() > 0);
  }
  if (!isMultiLine) // check if line length > max line length
  {
    childValues_.reserve(size);
    addChildValues_ = true;
    ArrayIndex lineLength = 4 + (size - 1) * 2; // '[ ' + ', '*n + ' ]'
    for (ArrayIndex index = 0; index < size; ++index) {
      if (hasCommentForValue(value[index])) {
        isMultiLine = true;
      }
      writeValue(value[index]);
      lineLength += static_cast<ArrayIndex>(childValues_[index].length());
    }
    addChildValues_ = false;
    isMultiLine = isMultiLine || lineLength >= rightMargin_;
  }
  return isMultiLine;
}
pushValue()
void Json::BuiltStyledStreamWriter::pushValue (JSONCPP_STRING const & value) [private]
Definition at line 5124 of file jsoncpp.cpp.
References addChildValues_, childValues_, and Json::StreamWriter::sout_.
Referenced by writeArrayValue(), and writeValue().
                                                                   {
  if (addChildValues_)
    childValues_.push_back(value);
  else
    *sout_ << value;
}
unindent()
void Json::BuiltStyledStreamWriter::unindent () [private]
Definition at line 5151 of file jsoncpp.cpp.
References indentation_, and indentString_.
Referenced by writeArrayValue(), and writeValue().
                                       {
  assert(indentString_.size() >= indentation_.size());
  indentString_.resize(indentString_.size() -
      indentation_.size());
}
write()
int Json::BuiltStyledStreamWriter::write (Value const & root, JSONCPP_OSTREAM * sout) [virtual]
Write Value into document as configured in sub-class. Do not take ownership of sout, but maintain a reference during function.
Precondition
sout != NULL
Returns
zero on success (For now, we always return zero, so check the stream instead.)
Exceptions
std::exception possibly, depending on configuration
Implements Json::StreamWriter.
Definition at line 4976 of file jsoncpp.cpp.
References addChildValues_, endingLineFeedSymbol_, indented_, indentString_, Json::StreamWriter::sout_, writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), and writeValue().
{
  sout_ = sout;
  addChildValues_ = false;
  indented_ = true;
  indentString_ = "";
  writeCommentBeforeValue(root);
  if (!indented_) writeIndent();
  indented_ = true;
  writeValue(root);
  writeCommentAfterValueOnSameLine(root);
  *sout_ << endingLineFeedSymbol_;
  sout_ = NULL;
  return 0;
}
writeArrayValue()
void Json::BuiltStyledStreamWriter::writeArrayValue (Value const & value) [private]
Definition at line 5050 of file jsoncpp.cpp.
References Json::CommentStyle::All, childValues_, cs_, indent(), indentation_, indented_, isMultineArray(), pushValue(), Json::Value::size(), Json::StreamWriter::sout_, unindent(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), writeIndent(), writeValue(), and writeWithIndent().
Referenced by writeValue().
                                                                {
  unsigned size = value.size();
  if (size == 0)
    pushValue("[]");
  else {
    bool isMultiLine = (cs_ == CommentStyle::All) ||
      isMultineArray(value);
    if (isMultiLine) {
      writeWithIndent("[");
      indent();
      bool hasChildValue = !childValues_.empty();
      unsigned index = 0;
      for (;;) {
        Value const& childValue = value[index];
        writeCommentBeforeValue(childValue);
        if (hasChildValue)
          writeWithIndent(childValues_[index]);
        else {
          if (!indented_) writeIndent();
          indented_ = true;
          writeValue(childValue);
          indented_ = false;
        }
        if (++index == size) {
          writeCommentAfterValueOnSameLine(childValue);
          break;
        }
        *sout_ << ",";
        writeCommentAfterValueOnSameLine(childValue);
      }
      unindent();
      writeWithIndent("]");
    } else // output on a single line
    {
      assert(childValues_.size() == size);
      *sout_ << "[";
      if (!indentation_.empty()) *sout_ << " ";
      for (unsigned index = 0; index < size; ++index) {
        if (index > 0)
          *sout_ << ((!indentation_.empty()) ? ", " : ",");
        *sout_ << childValues_[index];
      }
      if (!indentation_.empty()) *sout_ << " ";
      *sout_ << "]";
    }
  }
}
writeCommentAfterValueOnSameLine()
void Json::BuiltStyledStreamWriter::writeCommentAfterValueOnSameLine (Value const & root) [private]
Definition at line 5175 of file jsoncpp.cpp.
References Json::commentAfter, Json::commentAfterOnSameLine, cs_, Json::Value::getComment(), Json::Value::hasComment(), Json::CommentStyle::None, Json::StreamWriter::sout_, and writeIndent().
Referenced by write(), writeArrayValue(), and writeValue().
                                                                                {
  if (cs_ == CommentStyle::None) return;
  if (root.hasComment(commentAfterOnSameLine))
    *sout_ << " " + root.getComment(commentAfterOnSameLine);
  if (root.hasComment(commentAfter)) {
    writeIndent();
    *sout_ << root.getComment(commentAfter);
  }
}
writeCommentBeforeValue()
void Json::BuiltStyledStreamWriter::writeCommentBeforeValue (Value const & root) [private]
Definition at line 5156 of file jsoncpp.cpp.
References Json::commentBefore, cs_, Json::Value::getComment(), Json::Value::hasComment(), indented_, indentString_, JSONCPP_STRING, Json::CommentStyle::None, Json::StreamWriter::sout_, and writeIndent().
Referenced by write(), writeArrayValue(), and writeValue().
                                                                       {
  if (cs_ == CommentStyle::None) return;
  if (!root.hasComment(commentBefore))
    return;
  if (!indented_) writeIndent();
  const JSONCPP_STRING& comment = root.getComment(commentBefore);
  JSONCPP_STRING::const_iterator iter = comment.begin();
  while (iter != comment.end()) {
    *sout_ << *iter;
    if (*iter == '\n' &&
       (iter != comment.end() && *(iter + 1) == '/'))
      // writeIndent(); // would write extra newline
      *sout_ << indentString_;
    ++iter;
  }
  indented_ = false;
}
writeIndent()
void Json::BuiltStyledStreamWriter::writeIndent () [private]
Definition at line 5131 of file jsoncpp.cpp.
References indentation_, indentString_, and Json::StreamWriter::sout_.
Referenced by write(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeWithIndent().
                                          {
  // blep intended this to look at the so-far-written string
  // to determine whether we are already indented, but
  // with a stream we cannot do that. So we rely on some saved state.
  // The caller checks indented_.
  if (!indentation_.empty()) {
    // In this case, drop newlines too.
    *sout_ << '\n' << indentString_;
  }
}
writeValue()
void Json::BuiltStyledStreamWriter::writeValue (Value const & value) [private]
Definition at line 4991 of file jsoncpp.cpp.
References Json::arrayValue, Json::Value::asBool(), Json::Value::asDouble(), Json::Value::asLargestInt(), Json::Value::asLargestUInt(), Json::booleanValue, colonSymbol_, Json::Value::getMemberNames(), Json::Value::getString(), indent(), Json::intValue, JSONCPP_STRING, nullSymbol_, Json::nullValue, Json::objectValue, precision_, pushValue(), Json::realValue, Json::StreamWriter::sout_, Json::stringValue, Json::Value::type(), Json::uintValue, unindent(), useSpecialFloats_, Json::valueToQuotedStringN(), Json::valueToString(), writeArrayValue(), writeCommentAfterValueOnSameLine(), writeCommentBeforeValue(), and writeWithIndent().
Referenced by isMultineArray(), write(), and writeArrayValue().
                                                           {
  switch (value.type()) {
  case nullValue:
    pushValue(nullSymbol_);
    break;
  case intValue:
    pushValue(valueToString(value.asLargestInt()));
    break;
  case uintValue:
    pushValue(valueToString(value.asLargestUInt()));
    break;
  case realValue:
    pushValue(valueToString(value.asDouble(),
      useSpecialFloats_, precision_));
    break;
  case stringValue:
  {
    // Is NULL is possible for value.string_? No.
    char const* str;
    char const* end;
    bool ok = value.getString(&str, &end);
    if (ok) pushValue(valueToQuotedStringN(str, static_cast<unsigned>(end-str)
      ));
    else pushValue("");
    break;
  }
  case booleanValue:
    pushValue(valueToString(value.asBool()));
    break;
  case arrayValue:
    writeArrayValue(value);
    break;
  case objectValue: {
    Value::Members members(value.getMemberNames());
    if (members.empty())
      pushValue("{}");
    else {
      writeWithIndent("{");
      indent();
      Value::Members::iterator it = members.begin();
      for (;;) {
        JSONCPP_STRING const& name = *it;
        Value const& childValue = value[name];
        writeCommentBeforeValue(childValue);
        writeWithIndent(valueToQuotedStringN(name.data(), static_cast<
      unsigned>(name.length())));
        *sout_ << colonSymbol_;
        writeValue(childValue);
        if (++it == members.end()) {
          writeCommentAfterValueOnSameLine(childValue);
          break;
        }
        *sout_ << ",";
        writeCommentAfterValueOnSameLine(childValue);
      }
      unindent();
      writeWithIndent("}");
    }
  } break;
  }
}
writeWithIndent()
void Json::BuiltStyledStreamWriter::writeWithIndent (JSONCPP_STRING const & value) [private]
Definition at line 5143 of file jsoncpp.cpp.
References indented_, Json::StreamWriter::sout_, and writeIndent().
Referenced by writeArrayValue(), and writeValue().
                                                                         {
  if (!indented_) writeIndent();
  *sout_ << value;
  indented_ = false;
}
Member Data Documentation
addChildValues_
bool Json::BuiltStyledStreamWriter::addChildValues_ [private]
Definition at line 4951 of file jsoncpp.cpp.
Referenced by isMultineArray(), pushValue(), and write().
childValues_
ChildValues Json::BuiltStyledStreamWriter::childValues_ [private]
Definition at line 4943 of file jsoncpp.cpp.
Referenced by isMultineArray(), pushValue(), and writeArrayValue().
colonSymbol_
JSONCPP_STRING Json::BuiltStyledStreamWriter::colonSymbol_ [private]
Definition at line 4948 of file jsoncpp.cpp.
Referenced by writeValue().
cs_
CommentStyle::Enum Json::BuiltStyledStreamWriter::cs_ [private]
Definition at line 4947 of file jsoncpp.cpp.
Referenced by writeArrayValue(), writeCommentAfterValueOnSameLine(), and writeCommentBeforeValue().
endingLineFeedSymbol_
JSONCPP_STRING Json::BuiltStyledStreamWriter::endingLineFeedSymbol_ [private]
Definition at line 4950 of file jsoncpp.cpp.
Referenced by write().
indentation_
JSONCPP_STRING Json::BuiltStyledStreamWriter::indentation_ [private]
Definition at line 4946 of file jsoncpp.cpp.
Referenced by indent(), unindent(), writeArrayValue(), and writeIndent().
indented_
bool Json::BuiltStyledStreamWriter::indented_ [private]
Definition at line 4952 of file jsoncpp.cpp.
Referenced by write(), writeArrayValue(), writeCommentBeforeValue(), and writeWithIndent().
indentString_
JSONCPP_STRING Json::BuiltStyledStreamWriter::indentString_ [private]
Definition at line 4944 of file jsoncpp.cpp.
Referenced by indent(), unindent(), write(), writeCommentBeforeValue(), and writeIndent().
nullSymbol_
JSONCPP_STRING Json::BuiltStyledStreamWriter::nullSymbol_ [private]
Definition at line 4949 of file jsoncpp.cpp.
Referenced by writeValue().
precision_
unsigned int Json::BuiltStyledStreamWriter::precision_ [private]
Definition at line 4954 of file jsoncpp.cpp.
Referenced by writeValue().
rightMargin_
unsigned int Json::BuiltStyledStreamWriter::rightMargin_ [private]
Definition at line 4945 of file jsoncpp.cpp.
Referenced by isMultineArray().
useSpecialFloats_
bool Json::BuiltStyledStreamWriter::useSpecialFloats_ [private]
Definition at line 4953 of file jsoncpp.cpp.
Referenced by writeValue().
The documentation for this struct was generated from the following file:
C:/Users/Kyle Tuckey/Documents/Final Year Project/Social_NPCS/Social_NPCS/jsoncpp.cpp